(function(){
 'use strict';
 const el=id=>document.getElementById(id),keys=['cristalwater_jwt','token','adminToken','cristalwater_user','user'];
 const month=el('aiMonth'),scope=el('aiScope'),input=el('messageInput'),messages=el('messages');
 const fingerprint=()=>JSON.stringify(keys.map(key=>localStorage.getItem(key)));
 const decode=token=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))));
 let principal,invalid=false,generation=0,busy=false,loaded=false,threadId=null,selection='';const requests=new Set();
 try{const token=keys.slice(0,3).map(k=>localStorage.getItem(k)).find(Boolean),claims=decode(token),id=Number(claims.userId||claims.id),users=keys.slice(3).map(k=>localStorage.getItem(k)).filter(Boolean).map(JSON.parse);
  if(claims.role!=='ADMIN'||!Number.isSafeInteger(id)||id<=0||!Number.isFinite(claims.exp)||claims.exp*1000<=Date.now()||!users.length||users.some(u=>u.role!=='ADMIN'||Number(u.userId||u.id)!==id)||keys.slice(0,3).some(k=>localStorage.getItem(k)&&localStorage.getItem(k)!==token))throw Error('session');
  principal={token,id,identity:fingerprint(),expires:claims.exp*1000};
 }catch(_){invalid=true;}
 const currentSelection=()=>month.value+':'+scope.value,validMonth=()=>/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(month.value);
 const money=value=>value===null?'Por confirmar':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(value/100);
 const node=(parent,tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;parent.append(n);return n;};
 function state(kind,text){el('aiStatus').dataset.state=kind;el('aiStatus').textContent=text;}
 function cancel(){generation++;for(const r of requests)r.abort();requests.clear();busy=false;}
 function clearData(){loaded=false;for(const id of ['financeMetrics','financeExpenseMetrics','financeExpenseBasis','financeAllocationMetrics','financeAllocationBasis','financeValuationMetrics','financeValuationBasis','financeClients','financeBasis','financeCoverageMetrics','financeCoverageBasis','financeCoverageSourceRows','financeCoverageServiceRows','financeRevenueMetrics','financeRevenueBasis','financeRevenueServiceRows','financeRevenueMaintenanceRows','financeRevenueIssueRows','recommendations','kpis','capabilities','actions'])el(id).replaceChildren();for(const id of ['financeDetails','financeCoverageSources','financeCoverageServices','financeRevenueServices','financeRevenueMaintenance','financeRevenueIssues'])el(id).hidden=true;el('financeStatus').textContent='Dados ainda não consultados.';el('aiMode').textContent='';}
 function controls(){const disabled=invalid||busy||!navigator.onLine||!validMonth();el('refreshBtn').disabled=disabled;el('sendBtn').disabled=disabled||!loaded;document.querySelectorAll('[data-prompt],#actions button').forEach(n=>n.disabled=disabled||!loaded);}
 function active(){try{if(!invalid&&principal.identity===fingerprint()&&principal.expires>Date.now())return true;}catch(_){}invalid=true;cancel();clearData();messages.replaceChildren();input.value='';el('chatStatus').textContent='';threadId=null;state('session','A sessão mudou. Reabra esta página com a conta pretendida.');controls();return false;}
 function changed(){cancel();clearData();messages.replaceChildren();threadId=null;selection=currentSelection();el('chatStatus').textContent='';const finance=scope.value==='finance';el('financePanel').hidden=!finance;el('financialPrompts').hidden=!finance;el('operationalPrompts').hidden=finance;el('operationalContext').hidden=finance;el('actionPanel').hidden=finance;if(active())state('idle','Consulte os dados para a área e mês escolhidos.');controls();}
 function validateFinance(f){const end=new Date(month.value+'-01T00:00:00Z');end.setUTCMonth(end.getUTCMonth()+1);const cents=v=>v===null||Number.isSafeInteger(v)&&v>=0,count=v=>Number.isSafeInteger(v)&&v>=0;
  if(!f||f.version!==1||f.monthRef!==month.value||f.currency!=='EUR'||!['READY','REVIEW','UNAVAILABLE'].includes(f.state)||!Number.isFinite(Date.parse(f.generatedAt))||f.period?.timeZone!=='UTC'||f.period.start!==month.value+'-01T00:00:00.000Z'||f.period.end!==end.toISOString()||f.sourceUnavailable!==(f.state==='UNAVAILABLE')||f.historicalClosingBalance!==false||f.limitApplied!==null||!Array.isArray(f.unavailable))throw Error('Dados financeiros não confirmados para este mês.');
  if(f.state==='UNAVAILABLE'){if(f.cash!==null||f.receivables!==null||f.monthDocuments!==null||f.customerCredit!==null||f.expenses!==null||f.costCoverage!==null||f.revenueCoverage!==null)throw Error('Fonte indisponível com valores inesperados.');return f;}
  if(!f.cash||!f.receivables||!f.monthDocuments||!f.customerCredit||!cents(f.cash.amountCents)||!count(f.cash.paymentCount)||f.cash.internalCreditIncluded!==false||f.cash.basis!=='PAYMENT_PAID_AT_UTC'||f.receivables.basis!=='CURRENT_DOCUMENT_BALANCE'||f.receivables.asOf!==f.generatedAt||!cents(f.receivables.amountCents)||!cents(f.receivables.overdueAmountCents)||!cents(f.customerCredit.amountCents)||!cents(f.monthDocuments.amountCents)||!Array.isArray(f.receivables.topClients)||f.receivables.topClients.length>10)throw Error('Resumo financeiro incompleto.');
  const e=f.expenses; if(!e||e.version!==1||e.monthRef!==f.monthRef||e.generatedAt!==f.generatedAt||e.currency!=='EUR'||!['READY','REVIEW'].includes(e.state)||e.coverage!=='REGISTERED_EXPENSES_ONLY'||e.completeOperatingCosts!==false||e.bankReconciled!==false||e.limitApplied!==null||e.basis?.documents!=='EXPENSE_DOCUMENT_DATE'||e.basis?.payments!=='RECORDED_PAYMENT_DATE'||e.basis?.open!=='CURRENT_REGISTERED_OBLIGATIONS'||!['documentAmountCents','paymentsAmountCents','openAmountCents','overdueAmountCents'].every(k=>cents(e[k]))||!count(e.reviewCount)||e.state==='READY'&&['documentAmountCents','paymentsAmountCents','openAmountCents','overdueAmountCents'].some(k=>e[k]===null)||f.state==='READY'&&e.state!=='READY')throw Error('Despesas registadas incompletas.');
  const a=e.attribution;if(!a||a.version!==1||a.monthRef!==f.monthRef||a.generatedAt!==f.generatedAt||a.currency!=='EUR'||!['READY','REVIEW'].includes(a.state)||a.coverage!=='REGISTERED_EXPENSE_ATTRIBUTION'||a.completeOperatingCosts!==false||a.profit!==null||a.limitApplied!==null||a.basis?.allocated!=='EXPLICIT_ALLOCATION_MONTH'||a.basis?.unallocated!=='CURRENT_EXPENSE_REMAINDER_ALL_MONTHS'||a.basis?.stock!=='PURCHASE_ATTRIBUTION_NOT_CONSUMPTION'||!['allocatedAmountCents','clientAmountCents','companyAmountCents','unallocatedAmountCents'].every(k=>cents(a[k]))||!count(a.reviewCount)||!Array.isArray(a.topClients)||a.topClients.length>10||a.state==='READY'&&['allocatedAmountCents','clientAmountCents','companyAmountCents','unallocatedAmountCents'].some(k=>a[k]===null)||f.state==='READY'&&a.state!=='READY')throw Error('Atribuição de custos incompleta.');
  const v=a.valuations;if(!v||v.version!==1||v.coverage!=='CONFIRMED_EXPENSE_MEASUREMENTS'||v.includedInExpenseAttribution!==true||v.completeOperatingCosts!==false||!cents(v.materialAmountCents)||!cents(v.laborAmountCents)||!count(v.count)||!count(v.reviewCount)||v.basis?.material!=='CONFIRMED_PURCHASE_LINE_NET_VISIT_CONSUMPTION'||v.basis?.labor!=='CONFIRMED_EXPENSE_PAID_TIME'||v.basis?.month!=='COMPLETED_VISIT_END_AT_UTC'||f.state==='READY'&&(v.materialAmountCents===null||v.laborAmountCents===null||v.reviewCount>0))throw Error('Custos valorizados incompletos.');
  for(const row of f.receivables.topClients)if(!Number.isSafeInteger(row.clientId)||row.clientId<=0||typeof row.name!=='string'||!cents(row.amountCents)||!cents(row.overdueAmountCents))throw Error('Lista de saldos inválida.');
  validateCoverage(f.costCoverage,f,count);
  validateRevenue(f.revenueCoverage,f,count);
  if(f.state==='READY'&&[f.cash.amountCents,f.receivables.amountCents,f.receivables.overdueAmountCents,f.customerCredit.amountCents,f.monthDocuments.amountCents].includes(null))throw Error('Totais por confirmar.');return f;
 }
 const sourceReasons={NO_EXPENSE_LINK:'Sem ligação a uma despesa',CANCELLED_EXPENSE:'Despesa ligada anulada',SOURCE_OR_EXPENSE_REVIEW:'Origem ou despesa por rever',UNKNOWN_SOURCE_STATUS:'Estado da origem por confirmar',MISSING_SOURCE_DATE:'Data da origem em falta'};
 const serviceReasons={LABOR_MISSING:'Tempo sem valorização',LABOR_REVIEW:'Tempo ou valorização por rever',MATERIAL_MISSING:'Consumo sem valorização',MATERIAL_PARTIAL:'Consumo parcialmente valorizado',MATERIAL_REVIEW:'Consumo ou valorização por rever',NO_MATERIAL_RECORD:'Sem consumo/devolução registado',MISSING_COMPLETION_DATE:'Data de conclusão em falta'};
 function validateCoverage(c,f,count){
  const fail=()=>{throw Error('Cobertura dos custos incompleta.');},id=v=>Number.isSafeInteger(v)&&v>0;
  if(!c||c.version!==1||c.monthRef!==f.monthRef||c.generatedAt!==f.generatedAt||c.state!=='PARTIAL'||c.completeOperatingCosts!==false||c.profit!==null||c.limitApplied!==null||c.basis?.sources!=='CURRENT_SOURCE_LINKS_ALL_MONTHS'||c.basis?.services!=='COMPLETED_VISIT_END_AT_UTC'||c.basis?.materials!=='CURRENT_NET_CONSUMPTION_PER_VISIT_PRODUCT_UNIT'||c.basis?.undated!=='PLANNED_MONTH_WITHOUT_END_AT')fail();
  for(const s of [c.sources?.stock,c.sources?.vehicles])if(!s||!['total','linked','unlinked','review','excluded','undated'].every(k=>count(s[k]))||s.total!==s.linked+s.unlinked+s.review+s.excluded||s.undated>s.total-s.excluded)fail();
  for(const [row,fields]of [[c.labor,['valued','missing','review']],[c.materials,['valued','partial','missing','review','zeroNet']]])if(!row||!count(row.total)||!fields.every(k=>count(row[k]))||row.total!==fields.reduce((sum,k)=>sum+row[k],0))fail();
  if(!['noMaterialRecordVisits','undatedCompleted','excludedVisitCount','unassignedMovementCount'].every(k=>count(c[k]))||c.noMaterialRecordVisits>c.labor.total)fail();
  for(const [sample,type]of [[c.sourceIssues,'source'],[c.serviceIssues,'service']]){
   if(!sample||!count(sample.total)||sample.limit!==10||sample.sampleOnly!==(sample.total>10)||!Array.isArray(sample.rows)||sample.rows.length!==Math.min(sample.total,10))fail();
   const seen=new Set();for(const row of sample.rows){if(!row||!id(row.id)||seen.has(row.type+':'+row.id))fail();seen.add(row.type+':'+row.id);
    if(type==='source'){if(!['STOCK_PURCHASE','VEHICLE_MAINTENANCE'].includes(row.type)||typeof row.label!=='string'||!Object.hasOwn(sourceReasons,row.reason)||typeof row.undated!=='boolean'||row.expenseId!==null&&!id(row.expenseId))fail();}
    else if(!['REGULAR','EXTRA'].includes(row.type)||row.clientId!==null&&!id(row.clientId)||!Array.isArray(row.reasons)||!row.reasons.length||row.reasons.some(r=>!Object.hasOwn(serviceReasons,r)))fail();
   }
  }
  if(c.sourceIssues.total!==c.sources.stock.unlinked+c.sources.stock.review+c.sources.vehicles.unlinked+c.sources.vehicles.review||c.serviceIssues.total>c.labor.total+c.undatedCompleted||c.serviceIssues.total<c.labor.missing+c.labor.review+c.undatedCompleted)fail();
 }
 function renderCoverage(c){
  for(const id of ['financeCoverageMetrics','financeCoverageBasis','financeCoverageSourceRows','financeCoverageServiceRows'])el(id).replaceChildren();
  for(const id of ['financeCoverageSources','financeCoverageServices'])el(id).hidden=true;
  const cards=[['Compras sem ligação · todos os meses',c?.sources.stock.unlinked],['Manutenções sem ligação · todos os meses',c?.sources.vehicles.unlinked],['Serviços com tempo sem valorização · mês',c?.labor.missing],['Consumos sem valorização completa · mês',c?c.materials.missing+c.materials.partial:undefined]];
  for(const [label,value]of cards){const card=node(el('financeCoverageMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',value===undefined?'Por confirmar':String(value));}
  if(!c){el('financeCoverageBasis').textContent='Fonte indisponível. Não é possível confirmar a cobertura dos custos.';return;}
  el('financeCoverageBasis').textContent=`Cobertura parcial: ${c.sources.stock.review+c.sources.vehicles.review} origens/ligações por rever; ${c.sources.stock.undated+c.sources.vehicles.undated} origens sem data. Nos ${c.labor.total} serviços concluídos no mês, ${c.labor.valued} têm tempo valorizado e ${c.labor.review} precisam de revisão. Os consumos são contados por produto/unidade em cada serviço: ${c.materials.valued} valorizados, ${c.materials.partial} parciais, ${c.materials.review} por rever e ${c.materials.zeroNet} com saldo líquido zero. Há ${c.noMaterialRecordVisits} serviços sem consumo/devolução registado, ${c.undatedCompleted} concluídos sem data no mês planeado e ${c.unassignedMovementCount} movimentos do mês sem um serviço único existente. Ausência de registo não significa custo zero. As devoluções posteriores contam na consulta atual. Confira despesas manuais antes de criar outra: uma origem sem ligação não prova uma dívida. Restantes gastos e repartição das receitas continuam por verificar.`;
  if(c.sourceIssues.total){el('financeCoverageSources').hidden=false;for(const row of c.sourceIssues.rows)node(el('financeCoverageSourceRows'),'p',(row.type==='STOCK_PURCHASE'?'Compra':'Manutenção')+' #'+row.id+' · '+row.label+' · '+sourceReasons[row.reason]+(row.undated?' · Sem data':'')+(row.expenseId?' · Despesa #'+row.expenseId:''));node(el('financeCoverageSourceRows'),'p',c.sourceIssues.sampleOnly?'Primeiras 10 de '+c.sourceIssues.total+' origens a conferir; os totais incluem todas.':'Lista completa das origens a conferir nesta consulta.','ai-note');}
  if(c.serviceIssues.total){el('financeCoverageServices').hidden=false;for(const row of c.serviceIssues.rows)node(el('financeCoverageServiceRows'),'p',(row.type==='REGULAR'?'Visita regular':'Visita extra')+' #'+row.id+' · '+(row.clientId?'Cliente #'+row.clientId:'Cliente por confirmar')+' · '+row.reasons.map(r=>serviceReasons[r]).join('; '));node(el('financeCoverageServiceRows'),'p',c.serviceIssues.sampleOnly?'Primeiros 10 de '+c.serviceIssues.total+' serviços a conferir; os totais incluem todos.':'Lista completa dos serviços a conferir nesta consulta.','ai-note');}
 }
 const revenueReasons={DUPLICATE_MAINTENANCE_REFERENCE:'Intervenção repetida em documentos ativos',MAINTENANCE_DECISION_UNCONFIRMED:'Decisão comercial da intervenção por confirmar',MAINTENANCE_DOCUMENT_CHANGED:'Linha ou valor diferente da decisão comercial original',MISSING_MAINTENANCE_SOURCE:'Intervenção de origem não encontrada',MAINTENANCE_SOURCE_CHANGED:'Execução, piscina ou dados da intervenção alterados',MONTHLY_ALLOCATION_REVIEW:'Mensalidade ou parcelas com origem, período ou serviço por rever',DOCUMENT_VALUES:'Estado ou valores do documento por confirmar',NO_LINES:'Documento sem detalhe de linhas',TAX_UNALLOCATED:'Imposto sem repartição comprovada',ADJUSTED_DOCUMENT:'Crédito, ajuste ou saldo transportado exige revisão',CONFLICTING_LINE_TYPES:'Tipos de linha incompatíveis',UNSUPPORTED_LINE_TYPE:'Tipo de linha sem classificação confirmada',LINE_VALUES:'Valores da linha incompatíveis',LINE_TOTAL_MISMATCH:'Soma das linhas diferente do documento',MONTHLY_UNALLOCATED:'Mensalidade por repartir conforme o contrato',OTHER_SOURCE_UNALLOCATED:'Outra origem ainda sem repartição por visita',MISSING_REFERENCE:'Linha de serviço sem referência',MISSING_SERVICE:'Serviço de origem não encontrado',DUPLICATE_REFERENCE:'Serviço repetido em documentos ativos',CLIENT_MISMATCH:'Cliente original do serviço não coincide',SERVICE_NOT_COMPLETED:'Serviço sem conclusão confirmada',MISSING_COMPLETION_DATE:'Data de conclusão em falta',SERVICE_INCLUDED_OR_UNCONFIRMED:'Serviço incluído ou condição comercial por confirmar'};
 const revenueDocumentReasons=new Set(['DOCUMENT_VALUES','NO_LINES','TAX_UNALLOCATED','ADJUSTED_DOCUMENT','CONFLICTING_LINE_TYPES','UNSUPPORTED_LINE_TYPE','LINE_VALUES','LINE_TOTAL_MISMATCH']);
 function validateRevenue(r,f,count){
  const fail=()=>{throw Error('Repartição dos valores documentados incompleta.');},id=v=>Number.isSafeInteger(v)&&v>0;
  if(!r||r.version!==3||r.monthRef!==f.monthRef||r.generatedAt!==f.generatedAt||r.currency!=='EUR'||r.state!=='PARTIAL'||r.completeRevenueAllocation!==false||r.revenue!==null||r.profit!==null||r.limitApplied!==null||r.basis?.documents!=='DOCUMENT_MONTH_REFERENCE_CURRENT_VALUES'||r.basis?.amounts!=='RECONCILED_DOCUMENT_LINES_ONLY'||r.basis?.services!=='UNIQUE_TYPED_COMPLETED_SERVICE_CURRENT_STATE'||r.basis?.maintenance!=='ORIGINAL_EXTRA_DECISION_AND_CURRENT_COMPLETED_INTERVENTION'||r.basis?.duplicates!=='RECEIVABLE_REFERENCES_ALL_MONTHS'||r.basis?.cashIncluded!==false||r.basis?.historicalClosingBalance!==false)fail();
  const d=r.documents,l=r.lines;if(!d||!l||!['total','reconciled','review','excluded'].every(k=>count(d[k]))||d.total!==d.reconciled+d.review+d.excluded||d.total!==f.monthDocuments.total||!['total','linked','maintenanceLinked','monthly','monthlyAllocated','unassigned','review'].every(k=>count(l[k]))||l.total!==l.linked+l.maintenanceLinked+l.monthly+l.monthlyAllocated+l.unassigned+l.review||f.state==='READY'&&(d.review>0||l.review>0))fail();
  if(!r.monthlyAllocations||r.monthlyAllocations.basis!=='EXPLICIT_CONTRACT_SERVICE_ALLOCATION_CURRENT_STATE_ALL_MONTHS'||!count(r.monthlyAllocations.activeCount)||!count(r.monthlyAllocations.reviewCount)||r.monthlyAllocations.reviewCount>r.monthlyAllocations.activeCount||f.state==='READY'&&r.monthlyAllocations.reviewCount>0)fail();
  const amounts=['maintenanceLinkedAmountCents','linkedServiceAmountCents','monthlyAllocatedAmountCents','monthlyUnallocatedAmountCents','otherUnallocatedAmountCents','serviceReviewAmountCents'];if(!count(r.reconciledDocumentAmountCents)||!amounts.every(k=>count(r[k]))||r.reconciledDocumentAmountCents!==amounts.reduce((sum,k)=>sum+r[k],0))fail();
  for(const [sample,kind,total]of [[r.linkedServices,'services',l.linked],[r.linkedMaintenance,'maintenance',l.maintenanceLinked],[r.issues,'issues',d.review+l.monthly+l.unassigned+l.review]]){
   if(!sample||sample.total!==total||sample.limit!==10||sample.sampleOnly!==(total>10)||!Array.isArray(sample.rows)||sample.rows.length!==Math.min(total,10))fail();
   const seen=new Set(),targets=new Set();for(const row of sample.rows){if(!row||!id(row.invoiceId)||!id(row.clientId)||typeof row.clientName!=='string'||seen.has(row.invoiceId+':'+row.lineId))fail();seen.add(row.invoiceId+':'+row.lineId);
    if(kind==='services'){if(!id(row.lineId)||!['REGULAR','EXTRA'].includes(row.type)||!id(row.id)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(row.serviceMonth)||!count(row.amountCents)||targets.has(row.type+':'+row.id))fail();targets.add(row.type+':'+row.id);}
    else if(kind==='maintenance'){if(!id(row.lineId)||!['EQUIPMENT','REMINDER'].includes(row.kind)||!id(row.id)||!id(row.poolId)||typeof row.label!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(row.completedMonth)||!count(row.amountCents)||targets.has(row.kind+':'+row.id)||row.kind==='REMINDER'&&(row.visitType!==null||row.visitId!==null)||row.kind==='EQUIPMENT'&&(!['REGULAR','EXTRA'].includes(row.visitType)||!id(row.visitId)))fail();targets.add(row.kind+':'+row.id);}
    else {if(!Object.hasOwn(revenueReasons,row.reason))fail();if(revenueDocumentReasons.has(row.reason)?row.lineId!==null:!id(row.lineId))fail();}
   }
  }
  const maintenanceTotal=r.linkedMaintenance.rows.reduce((sum,row)=>sum+row.amountCents,0);if(!count(maintenanceTotal)||maintenanceTotal>r.maintenanceLinkedAmountCents||!r.linkedMaintenance.sampleOnly&&maintenanceTotal!==r.maintenanceLinkedAmountCents)fail();
  const sampled=r.linkedServices.rows.reduce((sum,row)=>sum+row.amountCents,0);if(!count(sampled)||sampled>r.linkedServiceAmountCents||!r.linkedServices.sampleOnly&&sampled!==r.linkedServiceAmountCents)fail();
 }
 function renderRevenue(r){
  for(const id of ['financeRevenueMetrics','financeRevenueBasis','financeRevenueServiceRows','financeRevenueMaintenanceRows','financeRevenueIssueRows'])el(id).replaceChildren();for(const id of ['financeRevenueServices','financeRevenueMaintenance','financeRevenueIssues'])el(id).hidden=true;
  for(const [label,key]of [['Ligado a serviços','linkedServiceAmountCents'],['Manutenções conciliadas','maintenanceLinkedAmountCents'],['Mensalidades repartidas','monthlyAllocatedAmountCents'],['Mensalidades por repartir','monthlyUnallocatedAmountCents'],['Outras linhas por repartir','otherUnallocatedAmountCents'],['Ligações por rever','serviceReviewAmountCents']]){const card=node(el('financeRevenueMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(r?r[key]:null));}
  if(!r){el('financeRevenueBasis').textContent='Fonte indisponível. Os valores documentados não estão confirmados.';return;}
  el('financeRevenueBasis').textContent=`Parcelas de ${money(r.reconciledDocumentAmountCents)} em ${r.documents.reconciled} documentos com linhas conciliadas, pelo mês do documento. ${r.documents.review} documentos por rever ficam fora destes valores; ${r.documents.excluded} rascunhos, documentos retirados ou depósitos de crédito excluídos. Créditos, saldos transportados e impostos exigem revisão. Não é dinheiro recebido nem receita completa do mês de execução: a conclusão do serviço pode pertencer a outro mês. Não somar estas parcelas novamente aos documentos ou recebimentos. Mensalidades dependem de cada contrato e época; não são divididas automaticamente pelo número de visitas. Manutenções conciliadas correspondem à decisão extra original, à linha exata e à intervenção concluída; a data refere-se à execução da intervenção e pode diferir do fim da visita. As parcelas de mensalidades são confirmadas pela administração. Há ${r.monthlyAllocations.reviewCount} parcelas por rever em todos os meses. Cobertura parcial, sem margem apurada.`;
  if(r.linkedServices.total){el('financeRevenueServices').hidden=false;for(const row of r.linkedServices.rows)node(el('financeRevenueServiceRows'),'p',row.clientName+' · Cliente #'+row.clientId+' · '+(row.type==='REGULAR'?'Visita regular':'Visita extra')+' #'+row.id+' · Conclusão '+row.serviceMonth+' · Documento #'+row.invoiceId+'/linha #'+row.lineId+' · '+money(row.amountCents));node(el('financeRevenueServiceRows'),'p',r.linkedServices.sampleOnly?'Primeiras 10 de '+r.linkedServices.total+' ligações; os totais incluem todas.':'Lista completa das ligações comprovadas nesta consulta.','ai-note');}
  if(r.linkedMaintenance.total){el('financeRevenueMaintenance').hidden=false;for(const row of r.linkedMaintenance.rows){const p=node(el('financeRevenueMaintenanceRows'),'p',row.clientName+' · Cliente #'+row.clientId+' · '+(row.kind==='EQUIPMENT'?'Manutenção de equipamento':'Lembrete de serviço')+' #'+row.id+' · '+row.label+' · Execução '+row.completedMonth+' · Documento #'+row.invoiceId+'/linha #'+row.lineId+' · '+money(row.amountCents)+(row.visitId?' · Visita '+(row.visitType==='REGULAR'?'regular':'extra')+' #'+row.visitId:''));const a=node(p,'a',' Consultar intervenções desta piscina');a.href='/admin-operational-settings?'+new URLSearchParams({poolId:String(row.poolId),maintenanceKind:row.kind});}node(el('financeRevenueMaintenanceRows'),'p',r.linkedMaintenance.sampleOnly?'Primeiras 10 de '+r.linkedMaintenance.total+' intervenções; os totais incluem todas.':'Lista completa das intervenções conciliadas nesta consulta.','ai-note');}
  if(r.issues.total){el('financeRevenueIssues').hidden=false;for(const row of r.issues.rows)node(el('financeRevenueIssueRows'),'p',row.clientName+' · Cliente #'+row.clientId+' · Documento #'+row.invoiceId+(row.lineId?' / linha #'+row.lineId:'')+' · '+revenueReasons[row.reason]);node(el('financeRevenueIssueRows'),'p',r.issues.sampleOnly?'Primeiros 10 de '+r.issues.total+' casos; os totais incluem todos.':'Lista completa dos casos por repartir ou rever nesta consulta.','ai-note');}
 }
 function renderFinance(f){el('financeMetrics').replaceChildren();el('financeExpenseMetrics').replaceChildren();el('financeAllocationMetrics').replaceChildren();el('financeValuationMetrics').replaceChildren();el('financeClients').replaceChildren();el('financeDetails').hidden=true;
  el('financeStatus').textContent='Mês de análise: '+f.monthRef+' · Consulta: '+new Date(f.generatedAt).toLocaleString('pt-PT')+' · '+({READY:'Dados disponíveis',REVIEW:'Há registos por rever',UNAVAILABLE:'Fonte indisponível'}[f.state]);
  const rows=[['Recebido no mês',f.cash?.amountCents??null],['Por cobrar agora',f.receivables?.amountCents??null],['Vencido agora',f.receivables?.overdueAmountCents??null],['Crédito dos clientes',f.customerCredit?.amountCents??null]];
  for(const [label,value]of rows){const card=node(el('financeMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeBasis').textContent='Recebimentos: pagamentos registados no mês em UTC, sem movimentos de crédito interno. Saldos em aberto e créditos: valores atuais de todos os meses, incluindo clientes inativos; não são o fecho histórico nem o saldo bancário.';
  for(const [label,value]of [['Despesas registadas no mês',f.expenses?.documentAmountCents??null],['Pagamentos de despesas no mês',f.expenses?.paymentsAmountCents??null],['Por pagar agora',f.expenses?.openAmountCents??null],['Despesas vencidas agora',f.expenses?.overdueAmountCents??null]]){const card=node(el('financeExpenseMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeExpenseBasis').textContent='Cobertura parcial: apenas despesas confirmadas neste registo. Documentos e pagamentos pertencem ao mês selecionado; saldos por pagar incluem todos os meses. Não há conciliação bancária nem custos completos. '+(f.expenses?f.expenses.reviewCount+' despesas por rever.':'Fonte indisponível.');
  const a=f.expenses?.attribution;for(const [label,value]of [['Atribuído no mês',a?.allocatedAmountCents??null],['A clientes e serviços',a?.clientAmountCents??null],['Custos gerais no mês',a?.companyAmountCents??null],['Por atribuir · todos os meses',a?.unallocatedAmountCents??null]]){const card=node(el('financeAllocationMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeAllocationBasis').textContent='Repartição das despesas já registadas, pelo mês confirmado da atribuição. Não se soma novamente às despesas ou aos pagamentos. Compras atribuídas não comprovam consumo; os custos completos e a rentabilidade continuam por apurar.';
  const v=a?.valuations;for(const [label,value]of [['Consumo valorizado',v?.materialAmountCents??null],['Tempo valorizado',v?.laborAmountCents??null]]){const card=node(el('financeValuationMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeValuationBasis').textContent='Parcela já incluída nas despesas atribuídas, pelo mês de conclusão do serviço. Base: compras, consumos, tempos e despesas de trabalho confirmados. Cobertura parcial. '+(v?v.reviewCount+' valorizações por rever.':'Fonte indisponível.');
  renderCoverage(f.costCoverage);
  renderRevenue(f.revenueCoverage);
  if(f.receivables?.topClients.length){el('financeDetails').hidden=false;for(const r of f.receivables.topClients)node(el('financeClients'),'p',r.name+' · #'+r.clientId+' · '+money(r.amountCents));node(el('financeClients'),'p',f.state==='REVIEW'?'Lista dos saldos identificados; existem registos por rever.':f.receivables.sampleOnly?'Dez maiores saldos; o total inclui todos os documentos.':'Lista completa dos clientes com saldo identificado.','ai-note');}
 }
 const allowedLinks=new Set(['/admin-reports','/admin-collection','/invoices','/admin-expenses','/admin-revenue']);
 function recommendations(rows,structured=false){el('recommendations').replaceChildren();if(!Array.isArray(rows))throw Error('Recomendações indisponíveis.');for(const row of rows){const box=node(el('recommendations'),'div','','rec');if(structured){node(box,'strong',String(row.title||''));node(box,'p',String(row.explanation||''));if(allowedLinks.has(row.href)){const a=node(box,'a','Abrir registos');a.href=row.href;}}else node(box,'p',String(row));}if(!rows.length)node(el('recommendations'),'p','Sem recomendações nesta consulta.');}
 function addMessage(role,text){node(messages,'div',text,'msg '+role);messages.scrollTop=messages.scrollHeight;}
 async function api(path,body,revision){const controller=new AbortController();requests.add(controller);const timer=setTimeout(()=>controller.abort(),55000);
  try{const response=await fetch('/api/ai-admin/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+principal.token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal,cache:'no-store',redirect:'error'});
   if(!active()||revision!==generation||selection!==currentSelection())throw Error('Seleção alterada.');
   if((response.headers.get('content-type')||'').split(';')[0].trim()!=='application/json')throw Error('Resposta indisponível.');const result=await response.json();if(response.status!==200||result?.ok!==true)throw Error(result?.error||'Não foi possível confirmar a operação.');return result;
  }finally{clearTimeout(timer);requests.delete(controller);}
 }
 function renderActions(rows){el('actions').replaceChildren();if(!Array.isArray(rows))return;for(const a of rows){if(!Number.isSafeInteger(a.id))continue;const box=node(el('actions'),'div','','action');node(box,'strong',a.title||a.type);node(box,'p',a.description||'');const actions=node(box,'div','','action-buttons');for(const [type,label]of [['approve','Aprovar e executar'],['reject','Rejeitar']]){const b=node(actions,'button',label);b.type='button';b.addEventListener('click',()=>void action(a.id,type));}}}
 async function load(){if(!active()||busy||!validMonth()||!navigator.onLine)return;cancel();clearData();selection=currentSelection();busy=true;controls();state('loading','A consultar os dados…');const revision=generation;
  try{const result=await api('status?'+new URLSearchParams({monthRef:month.value}),null,revision);if(!active()||revision!==generation||selection!==currentSelection())return;const f=validateFinance(result.context?.finance);renderFinance(f);recommendations(result.financialRecommendations,true);
   el('aiMode').textContent=result.externalAiEnabled?'IA externa configurada. Confirme as sugestões com os dados consultados.':'Análise por regras locais e dados da empresa. A IA externa está desligada.';
   for(const [label,key]of [['Visitas hoje','visitsToday'],['Técnicos ativos','techniciansActive'],['Alertas','openAlerts'],['Documentos por cobrar','pendingInvoices']]){const box=node(el('kpis'),'div','','kpi');node(box,'span',label);node(box,'strong',String(result.context.counters?.[key]??'Por confirmar'));}
   node(el('capabilities'),'p',result.context.unavailableSources?.length?'Existem fontes operacionais indisponíveis.':'As listas operacionais são amostras.','ai-note');
   if(scope.value==='operations'){const pending=await api('actions?status=PENDING&take=30',null,revision);if(!active()||revision!==generation)return;renderActions(pending.actions);}
   loaded=true;busy=false;state(f.state==='UNAVAILABLE'?'unavailable':f.state==='REVIEW'?'review':'ready',f.state==='UNAVAILABLE'?'Os dados financeiros estão indisponíveis. Não foram substituídos por zero.':f.state==='REVIEW'?'Há dados por confirmar. Reveja as limitações antes de decidir.':'Dados consultados. Pode conversar sobre a área selecionada.');controls();
  }catch(error){if(active()&&revision===generation){busy=false;clearData();state('error',error.name==='AbortError'?'A consulta demorou demasiado. Tente novamente.':error.message);controls();}}
 }
 async function send(){if(!active()||busy||!loaded||!navigator.onLine)return;const message=input.value.trim();if(!message||message.length>4000)return;const revision=generation,selectedMonth=month.value,selectedScope=scope.value;busy=true;controls();addMessage('user',message);el('chatStatus').textContent='A preparar a resposta…';
  try{const result=await api('chat',{message,threadId,monthRef:selectedMonth,scope:selectedScope},revision);if(!active()||revision!==generation||selection!==currentSelection())return;
   if(result.monthRef!==selectedMonth||result.scope!==selectedScope||!Number.isSafeInteger(result.threadId)||result.threadId<=0||typeof result.answer!=='string'||!result.answer.trim()||!Array.isArray(result.actions)||selectedScope==='finance'&&result.actions.length)throw Error('Resposta não confirmada para esta conversa.');
   const f=validateFinance(result.finance);threadId=result.threadId;renderFinance(f);addMessage('ai',result.answer);recommendations(result.recommendations);if(input.value.trim()===message)input.value='';
   if(selectedScope==='operations')renderActions(result.actions);el('chatStatus').textContent=String(result.mode).startsWith('openai')?'Resposta da IA externa; confirme os valores nas fontes.':'Resposta baseada em regras locais e nos dados disponíveis.';
  }catch(_){if(active()&&revision===generation)el('chatStatus').textContent='Não foi possível confirmar a resposta. A pergunta foi conservada; não foi reenviada automaticamente.';}
  finally{if(active()&&revision===generation){busy=false;controls();}}
 }
 async function action(id,type){if(!active()||busy||scope.value!=='operations'||!loaded)return;if(type==='approve'&&!confirm('Aprovar e executar esta ação?'))return;const revision=generation;busy=true;controls();
  try{const result=await api('actions/'+id+'/'+type,{reason:'Rejeitado pelo administrador'},revision);if(!active()||revision!==generation)return;if(type==='approve'&&result.action?.status!=='EXECUTED')throw Error('Execução não confirmada.');addMessage('ai',type==='approve'?'Ação executada e registada.':'Ação rejeitada.');busy=false;await load();}
  catch(_){if(active()&&revision===generation){busy=false;el('chatStatus').textContent='Resultado da ação não confirmado. Consulte as ações antes de repetir.';controls();}}
 }
 month.value=new Date().toISOString().slice(0,7);el('refreshBtn').addEventListener('click',()=>void load());el('sendBtn').addEventListener('click',()=>void send());
 input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send();}});
 document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{if(active()&&!busy){input.value=b.dataset.prompt;void send();}}));
 month.addEventListener('input',changed);month.addEventListener('change',changed);scope.addEventListener('change',changed);
 for(const event of ['storage','focus'])window.addEventListener(event,active);document.addEventListener('visibilitychange',active);
 for(const method of ['setItem','removeItem','clear']){const original=Storage.prototype[method];Storage.prototype[method]=function(...args){const result=Reflect.apply(original,this,args);if(this===localStorage&&(method==='clear'||keys.includes(String(args[0]))))active();return result;};}
 window.addEventListener('pagehide',changed);window.addEventListener('pageshow',e=>{if(e.persisted)changed();});window.addEventListener('online',controls);window.addEventListener('offline',controls);
 setInterval(()=>{if(active()){if(selection!==currentSelection())changed();else controls();}},500);changed();if(!invalid)void load();
})();
