(function(){
 'use strict';
 const el=id=>document.getElementById(id),keys=['cristalwater_jwt','token','adminToken','cristalwater_user','user'];
 const month=el('aiMonth'),scope=el('aiScope'),input=el('messageInput'),messages=el('messages');
 const fingerprint=()=>JSON.stringify(keys.map(key=>localStorage.getItem(key)));
 const decode=token=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))));
 let principal,invalid=false,generation=0,busy=false,loaded=false,threadId=null,selection='';const requests=new Set();
 try{const token=keys.slice(0,3).map(k=>localStorage.getItem(k)).find(Boolean),claims=decode(token),id=Number(claims.userId||claims.id),users=keys.slice(3).map(k=>localStorage.getItem(k)).filter(Boolean).map(JSON.parse);
  if(claims.role!=='ADMIN'||!Number.isSafeInteger(id)||id<=0||!Number.isFinite(claims.exp)||claims.exp*1000<=Date.now()||!users.length||users.some(u=>u.role!=='ADMIN'||Number(u.userId||u.id)!==id)||keys.slice(0,3).some(k=>localStorage.getItem(k)&&localStorage.getItem(k)!==token))throw Error('session');
  principal={token,id,identity:fingerprint(),expires:claims.exp*1000};
 }catch(_){invalid=true;}
 const currentSelection=()=>month.value+':'+scope.value,validMonth=()=>/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(month.value);
 const money=value=>value===null?'Por confirmar':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(value/100);
 const node=(parent,tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;parent.append(n);return n;};
 function state(kind,text){el('aiStatus').dataset.state=kind;el('aiStatus').textContent=text;}
 function cancel(){generation++;for(const r of requests)r.abort();requests.clear();busy=false;}
 function clearData(){loaded=false;for(const id of ['financeMetrics','financeExpenseMetrics','financeExpenseBasis','financeClients','financeBasis','recommendations','kpis','capabilities','actions'])el(id).replaceChildren();el('financeDetails').hidden=true;el('financeStatus').textContent='Dados ainda não consultados.';el('aiMode').textContent='';}
 function controls(){const disabled=invalid||busy||!navigator.onLine||!validMonth();el('refreshBtn').disabled=disabled;el('sendBtn').disabled=disabled||!loaded;document.querySelectorAll('[data-prompt],#actions button').forEach(n=>n.disabled=disabled||!loaded);}
 function active(){try{if(!invalid&&principal.identity===fingerprint()&&principal.expires>Date.now())return true;}catch(_){}invalid=true;cancel();clearData();messages.replaceChildren();input.value='';el('chatStatus').textContent='';threadId=null;state('session','A sessão mudou. Reabra esta página com a conta pretendida.');controls();return false;}
 function changed(){cancel();clearData();messages.replaceChildren();threadId=null;selection=currentSelection();el('chatStatus').textContent='';const finance=scope.value==='finance';el('financePanel').hidden=!finance;el('financialPrompts').hidden=!finance;el('operationalPrompts').hidden=finance;el('operationalContext').hidden=finance;el('actionPanel').hidden=finance;if(active())state('idle','Consulte os dados para a área e mês escolhidos.');controls();}
 function validateFinance(f){const end=new Date(month.value+'-01T00:00:00Z');end.setUTCMonth(end.getUTCMonth()+1);const cents=v=>v===null||Number.isSafeInteger(v)&&v>=0,count=v=>Number.isSafeInteger(v)&&v>=0;
  if(!f||f.version!==1||f.monthRef!==month.value||f.currency!=='EUR'||!['READY','REVIEW','UNAVAILABLE'].includes(f.state)||!Number.isFinite(Date.parse(f.generatedAt))||f.period?.timeZone!=='UTC'||f.period.start!==month.value+'-01T00:00:00.000Z'||f.period.end!==end.toISOString()||f.sourceUnavailable!==(f.state==='UNAVAILABLE')||f.historicalClosingBalance!==false||f.limitApplied!==null||!Array.isArray(f.unavailable))throw Error('Dados financeiros não confirmados para este mês.');
  if(f.state==='UNAVAILABLE'){if(f.cash!==null||f.receivables!==null||f.monthDocuments!==null||f.customerCredit!==null||f.expenses!==null)throw Error('Fonte indisponível com valores inesperados.');return f;}
  if(!f.cash||!f.receivables||!f.monthDocuments||!f.customerCredit||!cents(f.cash.amountCents)||!count(f.cash.paymentCount)||f.cash.internalCreditIncluded!==false||f.cash.basis!=='PAYMENT_PAID_AT_UTC'||f.receivables.basis!=='CURRENT_DOCUMENT_BALANCE'||f.receivables.asOf!==f.generatedAt||!cents(f.receivables.amountCents)||!cents(f.receivables.overdueAmountCents)||!cents(f.customerCredit.amountCents)||!cents(f.monthDocuments.amountCents)||!Array.isArray(f.receivables.topClients)||f.receivables.topClients.length>10)throw Error('Resumo financeiro incompleto.');
  const e=f.expenses; if(!e||e.version!==1||e.monthRef!==f.monthRef||e.generatedAt!==f.generatedAt||e.currency!=='EUR'||!['READY','REVIEW'].includes(e.state)||e.coverage!=='REGISTERED_EXPENSES_ONLY'||e.completeOperatingCosts!==false||e.bankReconciled!==false||e.limitApplied!==null||e.basis?.documents!=='EXPENSE_DOCUMENT_DATE'||e.basis?.payments!=='RECORDED_PAYMENT_DATE'||e.basis?.open!=='CURRENT_REGISTERED_OBLIGATIONS'||!['documentAmountCents','paymentsAmountCents','openAmountCents','overdueAmountCents'].every(k=>cents(e[k]))||!count(e.reviewCount)||e.state==='READY'&&['documentAmountCents','paymentsAmountCents','openAmountCents','overdueAmountCents'].some(k=>e[k]===null)||f.state==='READY'&&e.state!=='READY')throw Error('Despesas registadas incompletas.');
  for(const row of f.receivables.topClients)if(!Number.isSafeInteger(row.clientId)||row.clientId<=0||typeof row.name!=='string'||!cents(row.amountCents)||!cents(row.overdueAmountCents))throw Error('Lista de saldos inválida.');
  if(f.state==='READY'&&[f.cash.amountCents,f.receivables.amountCents,f.receivables.overdueAmountCents,f.customerCredit.amountCents,f.monthDocuments.amountCents].includes(null))throw Error('Totais por confirmar.');return f;
 }
 function renderFinance(f){el('financeMetrics').replaceChildren();el('financeExpenseMetrics').replaceChildren();el('financeClients').replaceChildren();el('financeDetails').hidden=true;
  el('financeStatus').textContent='Mês dos recebimentos: '+f.monthRef+' · Consulta: '+new Date(f.generatedAt).toLocaleString('pt-PT')+' · '+({READY:'Dados disponíveis',REVIEW:'Há registos por rever',UNAVAILABLE:'Fonte indisponível'}[f.state]);
  const rows=[['Recebido no mês',f.cash?.amountCents??null],['Por cobrar agora',f.receivables?.amountCents??null],['Vencido agora',f.receivables?.overdueAmountCents??null],['Crédito dos clientes',f.customerCredit?.amountCents??null]];
  for(const [label,value]of rows){const card=node(el('financeMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeBasis').textContent='Recebimentos: pagamentos registados no mês em UTC, sem movimentos de crédito interno. Saldos em aberto e créditos: valores atuais de todos os meses, incluindo clientes inativos; não são o fecho histórico nem o saldo bancário.';
  for(const [label,value]of [['Despesas registadas no mês',f.expenses?.documentAmountCents??null],['Pagamentos de despesas no mês',f.expenses?.paymentsAmountCents??null],['Por pagar agora',f.expenses?.openAmountCents??null],['Despesas vencidas agora',f.expenses?.overdueAmountCents??null]]){const card=node(el('financeExpenseMetrics'),'div','','kpi');node(card,'span',label);node(card,'strong',money(value));}
  el('financeExpenseBasis').textContent='Cobertura parcial: apenas despesas confirmadas neste registo. Documentos e pagamentos pertencem ao mês selecionado; saldos por pagar incluem todos os meses. Não há conciliação bancária nem custos completos. '+(f.expenses?f.expenses.reviewCount+' despesas por rever.':'Fonte indisponível.');
  if(f.receivables?.topClients.length){el('financeDetails').hidden=false;for(const r of f.receivables.topClients)node(el('financeClients'),'p',r.name+' · #'+r.clientId+' · '+money(r.amountCents));node(el('financeClients'),'p',f.state==='REVIEW'?'Lista dos saldos identificados; existem registos por rever.':f.receivables.sampleOnly?'Dez maiores saldos; o total inclui todos os documentos.':'Lista completa dos clientes com saldo identificado.','ai-note');}
 }
 const allowedLinks=new Set(['/admin-reports','/admin-collection','/invoices','/admin-expenses']);
 function recommendations(rows,structured=false){el('recommendations').replaceChildren();if(!Array.isArray(rows))throw Error('Recomendações indisponíveis.');for(const row of rows){const box=node(el('recommendations'),'div','','rec');if(structured){node(box,'strong',String(row.title||''));node(box,'p',String(row.explanation||''));if(allowedLinks.has(row.href)){const a=node(box,'a','Abrir registos');a.href=row.href;}}else node(box,'p',String(row));}if(!rows.length)node(el('recommendations'),'p','Sem recomendações nesta consulta.');}
 function addMessage(role,text){node(messages,'div',text,'msg '+role);messages.scrollTop=messages.scrollHeight;}
 async function api(path,body,revision){const controller=new AbortController();requests.add(controller);const timer=setTimeout(()=>controller.abort(),55000);
  try{const response=await fetch('/api/ai-admin/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+principal.token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal,cache:'no-store',redirect:'error'});
   if(!active()||revision!==generation||selection!==currentSelection())throw Error('Seleção alterada.');
   if((response.headers.get('content-type')||'').split(';')[0].trim()!=='application/json')throw Error('Resposta indisponível.');const result=await response.json();if(response.status!==200||result?.ok!==true)throw Error(result?.error||'Não foi possível confirmar a operação.');return result;
  }finally{clearTimeout(timer);requests.delete(controller);}
 }
 function renderActions(rows){el('actions').replaceChildren();if(!Array.isArray(rows))return;for(const a of rows){if(!Number.isSafeInteger(a.id))continue;const box=node(el('actions'),'div','','action');node(box,'strong',a.title||a.type);node(box,'p',a.description||'');const actions=node(box,'div','','action-buttons');for(const [type,label]of [['approve','Aprovar e executar'],['reject','Rejeitar']]){const b=node(actions,'button',label);b.type='button';b.addEventListener('click',()=>void action(a.id,type));}}}
 async function load(){if(!active()||busy||!validMonth()||!navigator.onLine)return;cancel();clearData();selection=currentSelection();busy=true;controls();state('loading','A consultar os dados…');const revision=generation;
  try{const result=await api('status?'+new URLSearchParams({monthRef:month.value}),null,revision);if(!active()||revision!==generation||selection!==currentSelection())return;const f=validateFinance(result.context?.finance);renderFinance(f);recommendations(result.financialRecommendations,true);
   el('aiMode').textContent=result.externalAiEnabled?'IA externa configurada. Confirme as sugestões com os dados consultados.':'Análise por regras locais e dados da empresa. A IA externa está desligada.';
   for(const [label,key]of [['Visitas hoje','visitsToday'],['Técnicos ativos','techniciansActive'],['Alertas','openAlerts'],['Documentos por cobrar','pendingInvoices']]){const box=node(el('kpis'),'div','','kpi');node(box,'span',label);node(box,'strong',String(result.context.counters?.[key]??'Por confirmar'));}
   node(el('capabilities'),'p',result.context.unavailableSources?.length?'Existem fontes operacionais indisponíveis.':'As listas operacionais são amostras.','ai-note');
   if(scope.value==='operations'){const pending=await api('actions?status=PENDING&take=30',null,revision);if(!active()||revision!==generation)return;renderActions(pending.actions);}
   loaded=true;busy=false;state(f.state==='UNAVAILABLE'?'unavailable':f.state==='REVIEW'?'review':'ready',f.state==='UNAVAILABLE'?'Os dados financeiros estão indisponíveis. Não foram substituídos por zero.':f.state==='REVIEW'?'Há dados por confirmar. Reveja as limitações antes de decidir.':'Dados consultados. Pode conversar sobre a área selecionada.');controls();
  }catch(error){if(active()&&revision===generation){busy=false;clearData();state('error',error.name==='AbortError'?'A consulta demorou demasiado. Tente novamente.':error.message);controls();}}
 }
 async function send(){if(!active()||busy||!loaded||!navigator.onLine)return;const message=input.value.trim();if(!message||message.length>4000)return;const revision=generation,selectedMonth=month.value,selectedScope=scope.value;busy=true;controls();addMessage('user',message);el('chatStatus').textContent='A preparar a resposta…';
  try{const result=await api('chat',{message,threadId,monthRef:selectedMonth,scope:selectedScope},revision);if(!active()||revision!==generation||selection!==currentSelection())return;
   if(result.monthRef!==selectedMonth||result.scope!==selectedScope||!Number.isSafeInteger(result.threadId)||result.threadId<=0||typeof result.answer!=='string'||!result.answer.trim()||!Array.isArray(result.actions)||selectedScope==='finance'&&result.actions.length)throw Error('Resposta não confirmada para esta conversa.');
   const f=validateFinance(result.finance);threadId=result.threadId;renderFinance(f);addMessage('ai',result.answer);recommendations(result.recommendations);if(input.value.trim()===message)input.value='';
   if(selectedScope==='operations')renderActions(result.actions);el('chatStatus').textContent=String(result.mode).startsWith('openai')?'Resposta da IA externa; confirme os valores nas fontes.':'Resposta baseada em regras locais e nos dados disponíveis.';
  }catch(_){if(active()&&revision===generation)el('chatStatus').textContent='Não foi possível confirmar a resposta. A pergunta foi conservada; não foi reenviada automaticamente.';}
  finally{if(active()&&revision===generation){busy=false;controls();}}
 }
 async function action(id,type){if(!active()||busy||scope.value!=='operations'||!loaded)return;if(type==='approve'&&!confirm('Aprovar e executar esta ação?'))return;const revision=generation;busy=true;controls();
  try{const result=await api('actions/'+id+'/'+type,{reason:'Rejeitado pelo administrador'},revision);if(!active()||revision!==generation)return;if(type==='approve'&&result.action?.status!=='EXECUTED')throw Error('Execução não confirmada.');addMessage('ai',type==='approve'?'Ação executada e registada.':'Ação rejeitada.');busy=false;await load();}
  catch(_){if(active()&&revision===generation){busy=false;el('chatStatus').textContent='Resultado da ação não confirmado. Consulte as ações antes de repetir.';controls();}}
 }
 month.value=new Date().toISOString().slice(0,7);el('refreshBtn').addEventListener('click',()=>void load());el('sendBtn').addEventListener('click',()=>void send());
 input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send();}});
 document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{if(active()&&!busy){input.value=b.dataset.prompt;void send();}}));
 month.addEventListener('input',changed);month.addEventListener('change',changed);scope.addEventListener('change',changed);
 for(const event of ['storage','focus'])window.addEventListener(event,active);document.addEventListener('visibilitychange',active);
 for(const method of ['setItem','removeItem','clear']){const original=Storage.prototype[method];Storage.prototype[method]=function(...args){const result=Reflect.apply(original,this,args);if(this===localStorage&&(method==='clear'||keys.includes(String(args[0]))))active();return result;};}
 window.addEventListener('pagehide',changed);window.addEventListener('pageshow',e=>{if(e.persisted)changed();});window.addEventListener('online',controls);window.addEventListener('offline',controls);
 setInterval(()=>{if(active()){if(selection!==currentSelection())changed();else controls();}},500);changed();if(!invalid)void load();
})();
