(function(){
 'use strict';
 const R=window.CWAdminCatalogue,copy=window.CWAdminCatalogueCopy,$=id=>document.getElementById(id),panel=$('adminCatalogue'),mode=panel.dataset.catalogueMode,keys=['cristalwater_jwt','token','adminToken','cristalwater_user','user'],fingerprint=()=>JSON.stringify(keys.map(k=>localStorage.getItem(k)));
 let rows=[],filter={q:'',group:'',lang:'pt'},state='ready',session=null,invalid=false,suspended=false,urlValid=true,catalogueValid=false;
 const t=k=>(copy?.[filter.lang]||copy.pt)[k],node=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;return el;};
 function active(){try{if(!invalid&&session.identity===fingerprint()&&session.expires>Date.now())return true;}catch(_){}if(!invalid||state!=='session'){invalid=true;state='session';filter.q='';filter.group='';render();}return false;}
 function address(path=location.pathname){const url=new URL(path,location.origin);if(filter.q)url.searchParams.set('q',filter.q);if(filter.group!=='')url.searchParams.set('group',filter.group);url.searchParams.set('lang',filter.lang);return url.pathname+url.search;}
 function fromUrl(){const parsed=R?.filters(location.search);urlValid=Boolean(parsed);if(parsed)filter=parsed;else filter={q:'',group:'',lang:'pt'};}
 function link(row){const el=node('a',t(row.context==='pool'?'pool':'open'));el.className='button';el.href=R.href(row,filter.lang);el.dataset.catalogueOpen=row.key;return el;}
 function render(){
  const visible=!invalid&&!suspended&&urlValid&&catalogueValid?R.search(rows,filter):[];state=invalid?'session':!catalogueValid?'error':!urlValid?'invalid':visible.length?'ready':'empty';panel.dataset.state=state;
  document.documentElement.lang=filter.lang;const title=t(mode==='index'?'indexTitle':'menuTitle');document.title=title+' · Cristal Water';$('catalogueTitle').textContent=title;$('catalogueIntro').textContent=t(mode==='index'?'indexIntro':'intro');for(const el of panel.querySelectorAll('[data-catalogue-copy]'))el.textContent=t(el.dataset.catalogueCopy);
  $('catalogueLanguage').value=filter.lang;$('catalogueSearch').value=filter.q;$('catalogueGroup').replaceChildren();const all=node('option',t('all'));all.value='';$('catalogueGroup').append(all);for(const [i,labels] of (R?.groups||[]).entries()){const option=node('option',R.label(labels,filter.lang));option.value=String(i);$('catalogueGroup').append(option);}$('catalogueGroup').value=filter.group;
  const blocked=invalid||suspended||!catalogueValid;for(const id of ['catalogueSearch','catalogueGroup','clearCatalogue','catalogueLanguage'])$(id).disabled=blocked;$('catalogueLogin').hidden=!invalid;$('reloadCatalogue').hidden=state!=='error';$('catalogueStatus').textContent=t(state);$('catalogueStatus').dataset.state=state;$('catalogueCount').textContent=['ready','empty'].includes(state)?t('showing')+': '+visible.length+' '+t('of')+' '+rows.length:'';$('catalogueOffline').hidden=navigator.onLine;
  $('catalogueSwitch').textContent=t(mode==='index'?'menu':'index');$('catalogueSwitch').href=address(mode==='index'?'/admin-menu':'/crystal-os-v2-route-index');$('catalogueCenter').href='/admin-master-control?lang='+filter.lang;
  $('catalogueRows').replaceChildren();$('catalogueRows').classList.toggle('index-results',mode==='index');for(const row of visible){const card=node('article','');card.dataset.catalogueKey=row.key;card.setAttribute('role','listitem');card.append(node('h3',R.label(row.labels,filter.lang)));const areas=node('p',row.groups.map(g=>R.label(R.groups[Number(g)],filter.lang)).join(' · '));areas.className='areas';card.append(areas);if(row.context==='pool'){const hint=node('p',t('poolHint'));hint.className='muted';card.append(hint);}if(mode==='index'){const route=node('code',row.href);route.className='route';route.setAttribute('aria-label',t('destination'));card.append(route);}card.append(link(row));$('catalogueRows').append(card);}
  $('shortcutPanel').hidden=mode==='index'||!['ready','empty'].includes(state)||Boolean(filter.q)||filter.group!==''||suspended;$('catalogueShortcuts').replaceChildren();if(!$('shortcutPanel').hidden)for(const key of ['/admin-master-control','/admin-today','/admin-rounds','/admin-clients','/billing-center']){const row=rows.find(r=>r.key===key);if(row){const a=link(row);a.textContent=R.label(row.labels,filter.lang);a.removeAttribute('data-catalogue-open');$('catalogueShortcuts').append(a);}}
 }
 function update(){if(!active()||suspended)return;filter={q:$('catalogueSearch').value,group:$('catalogueGroup').value,lang:$('catalogueLanguage').value};urlValid=Boolean(R.filters(address().split('?')[1]||''));history.replaceState(null,'',address());render();}
 try{const token=keys.slice(0,3).map(k=>localStorage.getItem(k)).find(Boolean),claims=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))),id=Number(claims.userId||claims.id),users=keys.slice(3).map(k=>localStorage.getItem(k)).filter(Boolean).map(JSON.parse);if(claims.role!=='ADMIN'||!Number.isInteger(id)||id<=0||!Number.isFinite(claims.exp)||claims.exp*1000<=Date.now()||!users.length||users.some(u=>u.role!=='ADMIN'||Number(u.userId||u.id)!==id)||keys.slice(0,3).some(k=>localStorage.getItem(k)&&localStorage.getItem(k)!==token))throw Error();session={identity:fingerprint(),expires:claims.exp*1000};}catch(_){invalid=true;}
 try{rows=R.build(window.CWAdminNavigation);catalogueValid=true;}catch(_){}
 $('catalogueFilters').addEventListener('submit',e=>{e.preventDefault();update();});$('catalogueSearch').addEventListener('input',update);$('catalogueGroup').addEventListener('change',update);$('catalogueLanguage').addEventListener('change',update);$('clearCatalogue').addEventListener('click',()=>{if(active()&&!suspended){filter.q='';filter.group='';urlValid=true;history.replaceState(null,'',address());render();$('catalogueSearch').focus();}});$('reloadCatalogue').addEventListener('click',()=>location.reload());
 panel.addEventListener('click',e=>{if(e.target.closest('[data-catalogue-open],#catalogueShortcuts a')&&(!active()||suspended))e.preventDefault();});window.addEventListener('storage',active);window.addEventListener('focus',active);window.addEventListener('online',render);window.addEventListener('offline',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)active();});window.addEventListener('pagehide',()=>{suspended=true;render();});window.addEventListener('pageshow',()=>{suspended=false;if(active()){fromUrl();render();}});window.addEventListener('popstate',()=>{if(active()){fromUrl();render();}});setInterval(active,1000);
 for(const id of ['catalogueStatus','catalogueCount','catalogueRows','catalogueShortcuts'])$(id).dataset.cwStateManaged='manual';fromUrl();render();active();
}());
