(function(){
 'use strict';
 const R=window.CWAdminDayRules,copy=window.CWAdminDayCopy,$=id=>document.getElementById(id),panel=$('adminDay'),keys=['cristalwater_jwt','token','adminToken','cristalwater_user','user'],fingerprint=()=>JSON.stringify(keys.map(k=>localStorage.getItem(k))),filterIds={date:'dayDate',q:'daySearch',group:'dayGroup',kind:'dayKind'};
 let session=null,invalid=false,suspended=false,sequence=0,request=null,data=null,state='loading',page=1,selection=null,urlInvalid=false,language='pt';const t=key=>copy[language][key],node=(tag,content,className)=>{const el=document.createElement(tag);el.textContent=content;if(className)el.className=className;return el;};
 try{const token=keys.slice(0,3).map(k=>localStorage.getItem(k)).find(Boolean),claims=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))),id=Number(claims.userId||claims.id),users=keys.slice(3).map(k=>localStorage.getItem(k)).filter(Boolean).map(JSON.parse);
  if(claims.role!=='ADMIN'||!R.positive(id)||!Number.isFinite(claims.exp)||claims.exp*1000<=Date.now()||!users.length||users.some(u=>u.role!=='ADMIN'||Number(u.userId||u.id)!==id)||keys.slice(0,3).some(k=>localStorage.getItem(k)&&localStorage.getItem(k)!==token))throw Error();session={token,owner:'ADMIN:'+id,identity:fingerprint(),expires:claims.exp*1000};
 }catch(_){invalid=true;state='session';}
 function abort(){sequence++;if(request){request.controller.abort();clearTimeout(request.timer);request=null;}}
 function active(){try{if(!invalid&&session.identity===fingerprint()&&session.expires>Date.now())return true;}catch(_){}invalid=true;abort();data=null;selection=null;page=1;for(const id of Object.values(filterIds))$(id).value='';state='session';render();return false;}
 function current(requestedPage=page){return R.filters({...Object.fromEntries(Object.entries(filterIds).map(([key,id])=>[key,$(id).value])),page:String(requestedPage)});}
 function writeUrl(){const url=new URL(location.href);for(const [key,id] of Object.entries(filterIds))$(id).value?url.searchParams.set(key,$(id).value):url.searchParams.delete(key);url.searchParams.set('page',String(page));url.searchParams.set('lang',language);history.replaceState(null,'',url);}
 function fromUrl(){const url=new URL(location.href),raw=Object.fromEntries([...Object.keys(filterIds),'page'].filter(k=>url.searchParams.has(k)).map(k=>[k,url.searchParams.get(k)]));for(const [key,id] of Object.entries(filterIds))$(id).value=raw[key]||'';const f=R.filters(raw);page=f?.page??NaN;urlInvalid=!f||[...Object.keys(filterIds),'page'].some(k=>url.searchParams.getAll(k).length>1);language=Object.hasOwn(copy,url.searchParams.get('lang'))?url.searchParams.get('lang'):'pt';}
 const locale=()=>({pt:'pt-PT',en:'en-GB',fr:'fr-FR',es:'es-ES',de:'de-DE'})[language],date=value=>value?new Intl.DateTimeFormat(locale(),{dateStyle:'medium',timeStyle:'short',timeZone:R.timeZone}).format(new Date(value)):t('notGiven'),name=value=>value?((value.name??t('notGiven'))+' · #'+value.id):t('notGiven');
 function fact(parent,label,value){const p=node('div','');p.append(node('dt',label),node('dd',value));parent.append(p);}
 function link(parent,label,url){const a=node('a',label,'button');a.href=url;a.addEventListener('click',event=>{if(!active()||!data||state!=='ready'||!R.equal(current(),selection))event.preventDefault();});parent.append(a);}
 function render(){
  document.documentElement.lang=language;document.title=t('title')+' · Cristal Water';$('dayLanguage').value=language;for(const el of panel.querySelectorAll('[data-day-copy]'))el.textContent=t(el.dataset.dayCopy);$('daySearch').placeholder=t('searchHint');panel.dataset.state=state;panel.setAttribute('aria-busy',String(state==='loading'));
  $('dayStatus').dataset.state=state;$('dayStatus').textContent=state==='ready'?t('ready').replace('{page}',page).replace('{pages}',data.pages).replace('{total}',data.total):t(state);$('dayStatus').setAttribute('role',['error','invalid','session'].includes(state)?'alert':'status');$('daySelected').textContent=data?t('selectedDay')+': '+data.day+' · '+R.timeZone:'';$('dayChecked').textContent=data?t('asOf')+' '+date(data.asOf)+' · '+R.timeZone:'';
  const usable=!!data&&['ready','outside','empty'].includes(state);for(const suffix of ['', 'Bottom']){$('dayFirst'+suffix).disabled=invalid||suspended||!usable||page===1;$('dayPrevious'+suffix).disabled=invalid||suspended||!usable||!data.hasPrevious;$('dayNext'+suffix).disabled=invalid||suspended||!usable||!data.hasNext;}
  for(const id of ['refreshDay','selectToday',...Object.values(filterIds)])$(id).disabled=invalid||suspended;const summary=$('daySummary');summary.replaceChildren();for(const group of ['total',...R.groups]){const box=node('div',''),value=node('strong',data?String(data.totals[group]):'—');value.dataset.dayTotal=group;box.append(node('span',t(group)),value);summary.append(box);}
  const list=$('dayRows');list.replaceChildren();if(!data)return;for(const row of data.rows){const card=node('article','','visit-card');card.dataset.visitKey=row.key;card.dataset.visitGroup=row.group;card.setAttribute('role','listitem');card.append(node('h2',t(row.kind)+' #'+row.id+' · '+name(row.pool)),node('p',t(row.group),'visit-state'));const facts=node('dl','');fact(facts,t('client'),name(row.client));fact(facts,t('technician'),name(row.technician));if(row.recordedTechnicianName!==null)fact(facts,t('recordedName'),row.recordedTechnicianName);if(row.legacyUser)fact(facts,t('legacyUser'),name(row.legacyUser));fact(facts,t('scheduled'),date(row.scheduledAt)+(row.scheduleSource==='date'?' · '+t('fallbackDate'):''));fact(facts,t('start'),date(row.startAt));fact(facts,t('end'),date(row.endAt));fact(facts,t('originalStatus'),row.status);card.append(facts);const actions=node('nav','','toolbar');if(row.pool)link(actions,t('poolSheet'),'/admin-pool-technical?poolId='+row.pool.id);if(row.group==='DONE'&&row.endAt)link(actions,t('review'),'/visit-report-review?'+new URLSearchParams({visitType:row.kind,visitId:String(row.id)}));card.append(actions);list.append(card);}
 }
 async function load(requestedPage=1){
  if(!active()||suspended)return;abort();data=null;page=requestedPage;selection=current();if(urlInvalid||!selection){state='invalid';render();return;}const chosen=selection,generation=sequence;writeUrl();state='loading';render();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);request={controller,timer};
  try{const query=new URLSearchParams();for(const [key,value] of Object.entries(chosen))if(value!=='')query.set(key,String(value));const response=await fetch('/api/core/visits/day/page?'+query,{headers:{Authorization:'Bearer '+session.token},signal:controller.signal,cache:'no-store',redirect:'error'});if(!active()||suspended||generation!==sequence)return;if([401,403].includes(response.status)){invalid=true;active();return;}if(response.status!==200||response.headers.get('x-cw-admin-day')!=='admin-day-v1'||response.headers.get('x-cw-owner')!==session.owner||response.headers.get('cache-control')!=='private, no-store'||!(response.headers.get('content-type')||'').startsWith('application/json'))throw Error('Unconfirmed daily visits');const result=await response.json();if(!active()||suspended||generation!==sequence)return;if(!R.equal(chosen,current())||!R.packet(result,chosen,session.owner))throw Error('Invalid daily visits');data=result;if(!chosen.date){$('dayDate').value=result.day;selection=current();writeUrl();}state=result.rows.length?'ready':result.total===0?'empty':'outside';render();
  }catch(_){if(active()&&!suspended&&generation===sequence){data=null;state='error';render();}}finally{clearTimeout(timer);if(generation===sequence){request=null;render();}}
 }
 function changed(){if(!active()||suspended)return;abort();data=null;urlInvalid=false;page=1;state='filters';render();}
 for(const id of Object.values(filterIds))$(id).addEventListener('input',changed);$('dayFilters').addEventListener('submit',event=>{event.preventDefault();load(1);});$('selectToday').addEventListener('click',()=>{if(active()){$('dayDate').value='';urlInvalid=false;load(1);}});
 for(const suffix of ['', 'Bottom']){$('dayFirst'+suffix).addEventListener('click',()=>load(1));$('dayPrevious'+suffix).addEventListener('click',()=>load(page-1));$('dayNext'+suffix).addEventListener('click',()=>load(page+1));}
 $('dayLanguage').addEventListener('change',()=>{language=$('dayLanguage').value;const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);render();});window.addEventListener('storage',()=>active());window.addEventListener('focus',()=>active());document.addEventListener('visibilitychange',()=>{if(!document.hidden)active();});window.addEventListener('pagehide',()=>{suspended=true;abort();data=null;state='loading';render();});window.addEventListener('pageshow',()=>{suspended=false;if(active()){fromUrl();load(page);}});window.addEventListener('popstate',()=>{if(active()){fromUrl();load(page);}});setInterval(()=>{if(active()&&data&&!R.equal(current(),selection))changed();},1000);
 for(const id of ['dayStatus','daySelected','dayChecked','daySummary','dayRows'])$(id).dataset.cwStateManaged='manual';fromUrl();render();active();
}());
