(function () {
  'use strict';
  const el=id=>document.getElementById(id),proof=window.CWReminderVisitRules,keys=['cristalwater_jwt','token','adminToken','cristalwater_user','user'];
  const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().filter(k=>v[k]!==undefined).map(k=>[k,canonical(v[k])])):v;
  const equal=(a,b)=>JSON.stringify(canonical(a))===JSON.stringify(canonical(b));
  const hash=async v=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(v)))))].map(n=>n.toString(16).padStart(2,'0')).join('');
  const check=(ok,message='Os dados precisam de revisão.')=>{if(!ok)throw Error(message);};
  const identity=()=>JSON.stringify(keys.map(k=>localStorage.getItem(k))),reminderId=Number(new URLSearchParams(location.search).get('reminderId'));
  const controllers=new Set();let principal,db,pending,detail,reviewed,invalid=false,storageFailed=false,busy=false,loading=false,candidateLoading=false,hydrated=false,editEpoch=0,readEpoch=0,candidateEpoch=0,candidateRows=[],page=1,total=0;
  let draft={action:'LINK',visitType:'',visitId:'',reason:''};
  const node=(p,tag,text)=>{const n=document.createElement(tag);n.textContent=text;p.append(n);return n;};
  const status=s=>{el('status').textContent=s;},note=s=>{el('writeStatus').textContent=s;},date=s=>new Date(s).toLocaleString('pt-PT');
  const visitText=v=>(v.type==='REGULAR'?'Visita regular #':'Visita extra #')+v.id+'\nCliente #'+v.clientId+' · Piscina #'+v.poolId+' · Técnico #'+v.technicianId+'\n'+date(v.startAt)+' → '+date(v.endAt)+'\nUTC: '+v.startAt+' → '+v.endAt;
  el('resourcesLink').href='/reminder-resources?associated=1&reminderId='+reminderId;el('resourcesLink').textContent='Parcelas de materiais e trabalho';el('materialsLink').href='/reminder-materials?reminderId='+reminderId;
  function active(){
    if(!invalid&&principal&&principal.expires>Date.now()&&principal.fingerprint===identity())return true;
    if(!invalid){invalid=true;editEpoch++;readEpoch++;candidateEpoch++;for(const c of controllers)c.abort();controllers.clear();detail=null;reviewed=null;pending=null;candidateRows=[];draft={action:'LINK',visitType:'',visitId:'',reason:''};
      for(const id of ['detailSection','editSection','historySection','pendingPanel','previewSection'])el(id).hidden=true;
      for(const id of ['title','origin','current','history','preview','pendingText','blockers','eligibility','selectedVisit','visit','candidateStatus'])el(id).replaceChildren();for(const id of ['reason','search','visitType'])el(id).value='';note('');}
    status('A sessão mudou. Reabra com a conta original para recuperar os pedidos guardados.');controls();return false;
  }
  const editable=()=>!!detail&&(detail.canLink||detail.canUnlink);
  function controls(){
    const blocked=invalid||busy||loading||!navigator.onLine;el('refresh').disabled=blocked;
    el('editSection').querySelectorAll('button,input,select,textarea').forEach(n=>{n.disabled=blocked||!editable()||!!pending||storageFailed||!db;});
    el('submit').disabled||=!reviewed||candidateLoading;el('calculate').disabled||=candidateLoading;
    el('previous').disabled||=page<=1||candidateLoading;el('next').disabled||=page*10>=total||candidateLoading;el('searchVisits').disabled||=!draft.visitType||candidateLoading;el('visit').disabled||=candidateLoading;
    el('action').querySelector('[value=LINK]').disabled=!detail?.canLink;el('action').querySelector('[value=UNLINK]').disabled=!detail?.canUnlink;
    for(const id of ['checkPending','retryPending'])el(id).disabled=blocked||!pending||storageFailed||!db;
    el('pendingPanel').hidden=!pending||invalid;
    if(pending&&!invalid){const p=pending.preview,v=p.selection.action==='LINK'?p.parent:p.original.event.preview.parent;el('pendingText').textContent='Lembrete #'+pending.reminderId+'\n'+(p.selection.action==='LINK'?'Associar a ':'Anular a associação a ')+visitText(v)+'\nMotivo: '+pending.body.reason;}
  }
  function clearPreview(){editEpoch++;reviewed=null;el('confirmed').checked=false;el('preview').replaceChildren();el('previewSection').hidden=true;controls();}
  const draftKey=()=>'cw-reminder-visit-draft:'+principal.owner+':'+reminderId;
  function validDraft(v){return proof.fields(v,['action','visitType','visitId','reason'])&&['LINK','UNLINK'].includes(v.action)&&['','REGULAR','EXTRA'].includes(v.visitType)&&typeof v.visitId==='string'&&v.visitId.length<=10&&(v.visitId===''||proof.positive(Number(v.visitId))&&String(Number(v.visitId))===v.visitId)&&typeof v.reason==='string'&&v.reason.length<=500;}
  function saveDraft(){if(!active())return;hydrated=true;try{sessionStorage.setItem(draftKey(),JSON.stringify(draft));}catch(_){storageFailed=true;note('Não foi possível conservar o rascunho neste navegador.');controls();}}
  function form(){el('submit').textContent=draft.action==='UNLINK'?'Confirmar anulação':'Confirmar associação';el('action').value=draft.action;el('visitType').value=draft.visitType;el('visit').value=draft.visitId;el('reason').value=draft.reason;el('visitFields').hidden=draft.action!=='LINK';el('unlinkNote').hidden=draft.action!=='UNLINK';const v=candidateRows.find(r=>String(r.id)===draft.visitId);el('selectedVisit').textContent=v?visitText(v):'';controls();}
  function selection(){if(draft.action==='UNLINK'){check(detail?.canUnlink&&detail.active,'Escolha uma associação ativa verificável.');return {action:'UNLINK',associationId:detail.active.id,visitType:null,visitId:null};}check(candidateRows.some(v=>v.type===draft.visitType&&String(v.id)===draft.visitId),'Escolha uma visita da lista e confira a sua origem.');return proof.input({action:'LINK',associationId:null,visitType:draft.visitType,visitId:Number(draft.visitId)});}
  async function request(path,body){const c=new AbortController(),timer=setTimeout(()=>c.abort(),40000);controllers.add(c);try{const r=await fetch('/api/equipment-maintenance'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+principal.token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',redirect:'error',signal:c.signal});check(active());check((r.headers.get('content-type')||'').split(';')[0]==='application/json','Resposta do servidor por confirmar.');const value=await r.json();check(active());if(r.status!==200||value?.ok!==true)throw Error(value?.error||'Operação por confirmar.');return value;}finally{clearTimeout(timer);controllers.delete(c);}}
  async function candidates(){
    if(!active()||!detail?.canLink||!draft.visitType)return;const ticket=++candidateEpoch,read=readEpoch,type=draft.visitType,q=el('search').value.trim(),selectedPage=page;clearPreview();candidateLoading=true;candidateRows=[];el('visit').replaceChildren();node(el('visit'),'option','Escolha a visita').value='';el('selectedVisit').textContent='';el('candidateStatus').textContent='A consultar as visitas…';controls();
    try{const v=(await request('/reminders/'+reminderId+'/visit-candidates?'+new URLSearchParams({visitType:type,page:selectedPage,q}))).candidates;if(!active()||ticket!==candidateEpoch||read!==readEpoch)return;
      check(v?.available&&v.reminderId===reminderId&&v.visitType===type&&v.page===selectedPage&&v.q===q&&v.pageSize===10&&Number.isSafeInteger(v.total)&&v.total>=0&&v.contextHash===detail.contextHash&&v.sourceHash===detail.sourceHash&&Array.isArray(v.rows)&&v.rows.length<=10,'O lembrete ou a lista de visitas mudou. Atualize antes de escolher.');
      check(new Set(v.rows.map(r=>r.id)).size===v.rows.length&&v.rows.every(r=>proof.parent(r)&&r.type===type&&r.clientId===detail.source.clientId&&r.poolId===detail.source.poolId&&(detail.source.technicianId===null||r.technicianId===detail.source.technicianId)&&(!q||String(r.id)===q)));
      candidateRows=v.rows;total=v.total;for(const row of v.rows){const option=node(el('visit'),'option',(type==='REGULAR'?'Regular #':'Extra #')+row.id+' · '+date(row.endAt)+' · Técnico #'+row.technicianId);option.value=String(row.id);}el('candidateStatus').textContent=total?'Página '+page+' · '+total+' visita(s) disponíveis. Escolha a origem.':'Não existem visitas compatíveis com esta pesquisa.';form();
    }catch(error){if(active()&&ticket===candidateEpoch)el('candidateStatus').textContent=error.message;}finally{if(ticket===candidateEpoch){candidateLoading=false;controls();}}
  }
  async function load(){
    if(!active())return;const ticket=++readEpoch;candidateEpoch++;candidateLoading=false;clearPreview();detail=null;candidateRows=[];loading=true;
    for(const id of ['detailSection','editSection','historySection'])el(id).hidden=true;for(const id of ['current','history','blockers','visit','selectedVisit'])el(id).replaceChildren();controls();status('A consultar o lembrete…');
    try{check(proof.positive(reminderId),'Abra o lembrete a partir das manutenções.');const v=(await request('/reminders/'+reminderId+'/visit-association')).detail;if(!active()||ticket!==readEpoch)return;
      check(v?.available,v?.message);check(v.reminderId===reminderId&&proof.sha(v.contextHash)&&proof.sha(v.sourceHash)&&Array.isArray(v.records)&&Array.isArray(v.blockers)&&typeof v.journalValid==='boolean'&&typeof v.canLink==='boolean'&&typeof v.canUnlink==='boolean');
      check(await hash(v.source)===v.sourceHash&&equal(v.active,v.records.find(r=>!r.voidResult)||null)&&(!v.canLink||!v.active&&v.journalValid&&!v.blockers.length)&&(!v.canUnlink||!!v.active&&v.journalValid&&!v.blockers.length));
      let head=null;for(const row of v.records){await proof.response(row.result,row.result.envelope,row.result.event.owner,reminderId,hash);check(row.id===row.result.event.id&&row.hash===row.result.eventHash&&['CONFIRMED','REVIEW','VOIDED'].includes(row.state));if(v.journalValid)check(row.result.event.preview.previousHash===head);head=row.hash;if(row.voidResult){await proof.response(row.voidResult,row.voidResult.envelope,row.voidResult.event.owner,reminderId,hash);check(equal(row.voidResult.event.preview.original,row.result));head=row.voidResult.eventHash;}}
      if(v.journalValid)check(head===v.previousHash);if(!active()||ticket!==readEpoch)return;detail=v;
      if(!hydrated){draft.action=v.active?'UNLINK':'LINK';hydrated=true;}form();const origin=v.source||v.records[0]?.result.event.preview.origin;el('title').textContent=v.title;el('origin').textContent='Lembrete #'+reminderId+' · Cliente: '+v.clientName+' (#'+origin?.clientId+') · Piscina: '+v.poolName+' (#'+origin?.poolId+')'+(v.source?.completedAt?' · Conclusão registada: '+date(v.source.completedAt):'');el('back').href='/admin-operational-settings?poolId='+origin?.poolId+'&maintenanceKind=REMINDER#equipmentMaintenancePanel';
      if(v.active){node(el('current'),'strong',v.active.state==='CONFIRMED'?'Associação confirmada':'Associação por rever');node(el('current'),'pre',visitText(v.active.result.event.preview.parent));if(v.active.state==='REVIEW')node(el('current'),'p','A origem ou o histórico mudou. Consulte os registos; a associação original continua conservada.');}else node(el('current'),'p','Não existe associação ativa a uma visita.');
      for(const b of v.blockers){const a=node(el('blockers'),'article','');node(a,'p',b.message);let href,label;if(b.code==='ACTIVE_COST'){check(proof.positive(b.expenseId)&&proof.positive(b.allocationId)&&proof.positive(b.amountCents));node(a,'p',new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(b.amountCents/100));href='/admin-expenses?expenseId='+b.expenseId;label='Rever despesa #'+b.expenseId;}else if(b.code==='ACTIVE_MATERIALS'){href=el('materialsLink').href;label='Rever consumo e reposição';}else if(b.code==='ACTIVE_RESOURCES'){href='/reminder-resources?reminderId='+reminderId;label='Rever declaração própria';}else if(b.code==='ACTIVE_ASSOCIATED_RESOURCES'){href=el('resourcesLink').href;label='Rever parcelas da visita';}if(href)node(a,'a',label).href=href;if(b.groupId){check(proof.positive(b.groupId));node(a,'a',' · Rever custo conjunto #'+b.groupId).href='/labor-cost-bases';}}
      el('eligibility').textContent=v.canLink?'Pode escolher a visita de origem e confirmar a associação.':v.canUnlink?'Pode anular a associação com um motivo, conservando o original.':v.blockers.length?'Resolva os registos indicados antes de alterar a associação.':'Confirme a conclusão e a decisão comercial do lembrete antes de associar uma visita.';
      for(const row of [...v.records].reverse()){const a=node(el('history'),'article',''),e=row.result.event;node(a,'h3',row.voidResult?'Associação anulada':row.state==='CONFIRMED'?'Associação confirmada':'Associação por rever');node(a,'p',e.owner+' · '+date(e.createdAt));node(a,'pre',visitText(e.preview.parent));node(a,'p',e.reason);if(row.voidResult){const u=row.voidResult.event;node(a,'p','Anulada por '+u.owner+' · '+date(u.createdAt)+' · '+u.reason);}}
      if(!v.records.length)node(el('history'),'p','Ainda não existem associações.');el('detailSection').hidden=false;el('editSection').hidden=!editable();el('historySection').hidden=false;status(v.journalValid?'Lembrete consultado. Confira a visita e o histórico abaixo.':'Histórico por confirmar. Alterações bloqueadas.');
      if(v.canLink&&draft.visitType){page=1;el('search').value=draft.visitId;await candidates();}
    }catch(error){if(active()&&ticket===readEpoch)status(error.message);}finally{if(ticket===readEpoch){loading=false;controls();}}
  }
  async function calculate(){if(!active()||busy||pending||!editable()||candidateLoading||!navigator.onLine)return;clearPreview();note('A conferir a associação e os registos atuais…');const ticket=editEpoch,read=readEpoch;
    try{const body=selection(),p=(await request('/reminders/'+reminderId+'/visit-preview',body)).preview;if(!active()||ticket!==editEpoch||read!==readEpoch)return;check(p?.available,p?.message);await proof.preview(p,hash);check(p.reminderId===reminderId&&p.contextHash===detail.contextHash&&p.previousHash===detail.previousHash&&equal(p.selection,body));
      if(body.action==='LINK')check(p.sourceHash===detail.sourceHash&&p.targetHash===detail.targetHash&&equal(p.source,detail.source)&&equal(p.target,detail.target)&&equal(p.parent,candidateRows.find(r=>r.type===body.visitType&&r.id===body.visitId)),'A visita mudou. Atualize e volte a conferir a origem.');else check(equal(p.original,detail.active?.result));
      if(!active()||ticket!==editEpoch||read!==readEpoch)return;reviewed=p;node(el('preview'),'strong',body.action==='LINK'?'Associar este lembrete à visita':'Anular a associação e conservar o original');node(el('preview'),'pre',visitText(body.action==='LINK'?p.parent:p.original.event.preview.parent));node(el('preview'),'p','Lembrete #'+reminderId+' · Motivo: '+draft.reason.trim());if(p.source)node(el('preview'),'p','Conclusão do lembrete registada em '+date(p.source.completedAt));node(el('preview'),'p',body.action==='LINK'?'Os recursos e custos próprios do lembrete ficarão bloqueados enquanto esta associação estiver ativa.':'A associação original fica no histórico. Reveja os recursos antes de uma nova declaração independente.');el('previewSection').hidden=false;note('Confira a visita, a origem e o motivo antes de confirmar.');
    }catch(error){if(active()&&ticket===editEpoch)note(error.message);}finally{controls();}
  }
  function access(mode,work){return new Promise((resolve,reject)=>{const tx=db.transaction('state',mode),q=work(tx.objectStore('state'));tx.oncomplete=()=>resolve(q?.result);tx.onerror=tx.onabort=()=>reject(tx.error||Error('Não foi possível guardar o pedido.'));});}
  const readLocal=kind=>access('readonly',s=>s.get(principal.owner+':'+kind));
  async function validPending(row){check(row?.owner===principal.owner&&proof.positive(row.reminderId)&&row.hash===await hash({owner:row.owner,reminderId:row.reminderId,body:row.body,preview:row.preview}));proof.command(row.body);await proof.preview(row.preview,hash);check(row.preview.reminderId===row.reminderId&&row.preview.hash===row.body.previewHash&&equal(row.preview.selection,Object.fromEntries(proof.selectionFields.map(k=>[k,row.body[k]]))));return row;}
  async function syncPending(){if(!db||!active()||busy)return;try{const row=await readLocal('pending');if(row)await validPending(row);if(active())pending=row||null;}catch(_){storageFailed=true;note('O pedido guardado precisa de revisão. Novas confirmações estão bloqueadas.');}controls();}
  async function accept(result,row){await proof.response(result,row.body,row.owner,row.reminderId,hash);check(active());
    await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite'),s=tx.objectStore('state'),get=s.get(principal.owner+':pending');get.onsuccess=()=>{if(!active()||!equal(get.result,row)){tx.abort();return;}s.put({record:row,result},principal.owner+':confirmed');s.delete(principal.owner+':pending');};tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(Error('O resultado não pôde ser conservado. Mantenha o pedido.'));});check(active());pending=null;
    if(result.applied&&row.reminderId===reminderId&&draft.reason.trim()===row.body.reason&&draft.action===row.body.action&&(draft.action==='UNLINK'||draft.visitType===row.body.visitType&&Number(draft.visitId)===row.body.visitId)){draft.reason='';draft.action=row.body.action==='LINK'?'UNLINK':'LINK';saveDraft();}
    note(result.applied?(row.body.action==='LINK'?'Associação confirmada.':'Associação anulada.')+' O pedido e o histórico ficaram conservados.':result.message+' O resultado ficou guardado.');await load();
  }
  async function execute(mode){if(!active()||busy||storageFailed||!db||!navigator.onLine)return;const ticket=editEpoch,read=readEpoch;let prepared;
    if(mode==='create'){if(!reviewed||pending||!el('confirmForm').reportValidity())return;check(proof.reason(draft.reason.trim()),'Indique um motivo entre três e 500 caracteres.');prepared={owner:principal.owner,reminderId,body:{requestId:crypto.randomUUID(),...selection(),previewHash:reviewed.hash,reason:draft.reason.trim(),confirmed:true},preview:reviewed};}
    busy=true;controls();try{await navigator.locks.request('cw-reminder-visits:'+principal.owner,{ifAvailable:true},async lock=>{check(lock,'Existe uma confirmação noutra janela. Consulte novamente.');check(active());let stored=await readLocal('pending');if(stored)await validPending(stored);check(active());
      if(mode==='create'){if(stored){pending=stored;throw Error('Existe um pedido por confirmar nesta conta.');}check(ticket===editEpoch&&read===readEpoch&&reviewed===prepared.preview,'A seleção mudou. Reveja a associação.');prepared.hash=await hash(prepared);await validPending(prepared);check(active()&&ticket===editEpoch&&read===readEpoch);await access('readwrite',s=>s.add(prepared,principal.owner+':pending'));stored=await readLocal('pending');check(equal(stored,prepared),'A gravação do pedido não ficou confirmada.');}
      check(active());pending=stored||null;if(!stored){await load();note('Não existe pedido pendente nesta conta.');return;}controls();const result=mode==='check'?await request('/reminder-visit-requests/'+stored.body.requestId):await request('/reminders/'+stored.reminderId+'/visit-association',stored.body);await accept(result,stored);
    });}catch(error){if(active())note(error.message+(pending?' O pedido original foi conservado; consulte o resultado ou reenvie-o.':''));}finally{busy=false;if(active())controls();}
  }
  el('refresh').onclick=load;el('calculate').onclick=calculate;
  el('action').onchange=()=>{if(!active()||busy||pending)return;draft.action=el('action').value;clearPreview();saveDraft();form();};
  el('visitType').onchange=()=>{if(!active()||busy||pending)return;candidateEpoch++;candidateLoading=false;el('candidateStatus').textContent='';el('visit').replaceChildren();node(el('visit'),'option','Escolha a visita').value='';draft.visitType=el('visitType').value;draft.visitId='';candidateRows=[];el('search').value='';page=1;total=0;clearPreview();saveDraft();form();void candidates();};
  el('visit').onchange=()=>{if(!active()||busy||pending)return;draft.visitId=el('visit').value;clearPreview();saveDraft();form();};
  el('reason').oninput=()=>{if(!active()||busy||pending)return;draft.reason=el('reason').value;clearPreview();saveDraft();};
  el('search').oninput=()=>{if(active()&&!busy&&!pending){candidateEpoch++;candidateLoading=false;clearPreview();}};
  el('searchVisits').onclick=()=>{page=1;draft.visitId='';saveDraft();void candidates();};el('previous').onclick=()=>{page--;draft.visitId='';saveDraft();void candidates();};el('next').onclick=()=>{page++;draft.visitId='';saveDraft();void candidates();};
  el('confirmForm').onsubmit=e=>{e.preventDefault();void execute('create').catch(error=>{if(active())note(error.message);});};el('checkPending').onclick=()=>execute('check');el('retryPending').onclick=()=>execute('retry');
  for(const event of ['storage','focus'])window.addEventListener(event,()=>{if(active())void syncPending();});document.addEventListener('visibilitychange',active);window.addEventListener('offline',clearPreview);window.addEventListener('online',controls);window.addEventListener('popstate',()=>location.reload());
  for(const method of ['setItem','removeItem','clear']){const original=Storage.prototype[method];Storage.prototype[method]=function(...args){const value=Reflect.apply(original,this,args);if(this===localStorage&&(method==='clear'||keys.includes(String(args[0]))))active();return value;};}setInterval(()=>{if(active())controls();},500);
  (async()=>{try{const token=keys.slice(0,3).map(k=>localStorage.getItem(k)).find(Boolean),claims=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)))),user=Number(claims.userId||claims.id),users=keys.slice(3).map(k=>localStorage.getItem(k)).filter(Boolean).map(JSON.parse);
    check(claims.role==='ADMIN'&&proof.positive(user)&&users.length&&users.every(u=>u.role==='ADMIN'&&Number(u.userId||u.id)===user)&&Number.isFinite(claims.exp)&&claims.exp*1000>Date.now()&&!keys.slice(0,3).some(k=>localStorage.getItem(k)&&localStorage.getItem(k)!==token));principal={token,owner:'ADMIN:'+user,expires:claims.exp*1000,fingerprint:identity()};
    try{check(navigator.locks&&crypto.subtle&&crypto.randomUUID);db=await new Promise((resolve,reject)=>{const q=indexedDB.open('cw-reminder-visits-v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('state');q.onsuccess=()=>resolve(q.result);q.onerror=q.onblocked=()=>reject(Error('Storage'));});await syncPending();const last=await readLocal('confirmed');if(last){await validPending(last.record);await proof.response(last.result,last.record.body,last.record.owner,last.record.reminderId,hash);if(active())note('Último resultado guardado: '+(last.result.applied?(last.record.body.action==='LINK'?'associação confirmada.':'associação anulada.'):'pedido não aplicado.'));}}catch(_){storageFailed=true;note('Não foi possível verificar os pedidos guardados. Pode consultar; novas confirmações estão bloqueadas.');}
    if(!active())return;const saved=sessionStorage.getItem(draftKey());if(saved){const v=JSON.parse(saved);check(validDraft(v),'O rascunho guardado precisa de revisão.');draft=v;hydrated=true;}form();await load();
  }catch(error){if(!principal)active();else if(active()){storageFailed=true;status(error.message);}}finally{controls();}})();
})();
