const express = require('express');
const router = express.Router();
const auth = require('../middlewares/authMiddleware');
const { prepareReports, previewReports, sendReportsNow } = require('../controllers/adminReportController');
router.use(auth('ADMIN'));
router.post('/reports/prepare', prepareReports);
router.get('/reports/email-preview', previewReports);
router.post('/reports/send-now', sendReportsNow);
const reviews=require('../controllers/adminReportController');
router.get('/reports/email-reviews',reviews.listEmailReviews);
router.get('/reports/email-reviews/:id',reviews.emailReviewDetail);
router.post('/reports/email-reviews/:id',reviews.reviewEmail);
router.get('/reports/email-reviews/:id/requests/:requestId',reviews.lookupEmailReview);
router.get('/reports/email-reviews/:id/retry',reviews.previewEmailRetry);
router.post('/reports/email-reviews/:id/retry',reviews.retryReviewedEmail);
module.exports = router;
