const router = require('express').Router();
const auth = require('../middlewares/authMiddleware');
const controller = require('../controllers/equipmentMaintenanceController');
router.use((req, res, next) => { res.set('Cache-Control', 'private, no-store'); next(); });
router.get('/notifications/config', auth('ADMIN'), controller.reminderConfiguration);
router.put('/notifications/config', auth('ADMIN'), controller.configureReminders);
router.post('/notifications/check', auth('ADMIN'), controller.checkReminders);
router.get('/pools/:poolId/billing', auth('ADMIN'), controller.listBilling);
router.post('/billing/:kind/:id/review', auth('ADMIN'), controller.reviewBilling);
router.get('/time-review-requests/:requestId', auth('ADMIN'), controller.recoverWorkTime);
router.get('/completions/:id/work-time', auth('ADMIN'), controller.workTime);
router.post('/completions/:id/time-preview', auth('ADMIN'), controller.previewWorkTime);
router.post('/completions/:id/time-review', auth('ADMIN'), controller.reviewWorkTime);
router.get('/material-review-requests/:requestId', auth('ADMIN'), controller.recoverMaterials);
router.get('/completions/:id/materials', auth('ADMIN'), controller.materials);
router.post('/completions/:id/material-preview', auth('ADMIN'), controller.previewMaterials);
router.post('/completions/:id/material-review', auth('ADMIN'), controller.reviewMaterials);
router.get('/reminder-resource-requests/:requestId', auth('ADMIN'), controller.recoverReminderResources);
router.get('/reminder-visit-resource-requests/:requestId', auth('ADMIN'), controller.recoverVisitResources);
router.get('/reminders/:id/visit-resources', auth('ADMIN'), controller.visitResources);
router.post('/reminders/:id/visit-resource-preview', auth('ADMIN'), controller.previewVisitResources);
router.post('/reminders/:id/visit-resources', auth('ADMIN'), controller.declareVisitResources);
router.get('/reminder-visit-requests/:requestId', auth('ADMIN'), controller.recoverReminderVisit);
router.get('/reminders/:id/visit-association', auth('ADMIN'), controller.reminderVisits);
router.get('/reminders/:id/visit-candidates', auth('ADMIN'), controller.reminderVisitCandidates);
router.post('/reminders/:id/visit-preview', auth('ADMIN'), controller.previewReminderVisit);
router.post('/reminders/:id/visit-association', auth('ADMIN'), controller.associateReminderVisit);
router.get('/reminder-material-requests/:requestId', auth('ADMIN'), controller.recoverReminderMaterials);
router.get('/reminders/:id/materials', auth('ADMIN'), controller.reminderMaterials);
router.post('/reminders/:id/material-preview', auth('ADMIN'), controller.previewReminderMaterials);
router.post('/reminders/:id/materials', auth('ADMIN'), controller.consumeReminderMaterials);
router.get('/reminders/:id/resources', auth('ADMIN'), controller.reminderResources);
router.post('/reminders/:id/resource-preview', auth('ADMIN'), controller.previewReminderResources);
router.post('/reminders/:id/resources', auth('ADMIN'), controller.declareReminderResources);
router.get('/pools/:poolId', auth('ADMIN'), controller.listPool);
router.post('/pools/:poolId', auth('ADMIN'), controller.create);
router.put('/plans/:id', auth('ADMIN'), controller.update);
router.get('/visits/:visitId', auth('TECHNICIAN'), controller.listVisit);
router.post('/plans/:id/complete', auth('TECHNICIAN'), controller.complete);
module.exports = router;
