'use strict';
const router=require('express').Router();
const auth=require('../middlewares/authMiddleware');
const {roleMatches}=require('../utils/roles');
const service=require('../services/fieldClientIntakeService');
router.use(auth());
router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');if(!roleMatches(req.user?.role,'TECHNICIAN'))return res.status(403).json({ok:false,error:'Sem permissão'});next();});
const handle=fn=>async(req,res)=>{try{res.json(await fn(req));}catch(error){res.status(error.statusCode||503).json({ok:false,code:error.code||'FIELD_INTAKE_UNCONFIRMED',error:error.statusCode?error.message:'Operação por confirmar. Conserve e repita o pedido original.'});}};
router.get('/settings',handle(async()=>({ok:true,...await service.settings()})));
router.post('/client-with-pool',handle(req=>service.create(req.user,req.body)));
router.get('/pending-review',handle(req=>service.pending(req.user)));
router.get('/clients/:id/review',handle(req=>service.getState(req.user,Number(req.params.id))));
router.post('/clients/:id/approve',handle(req=>service.approve(req.user,Number(req.params.id),req.body)));
module.exports=router;
