'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-onboarding-rules');
const audience='cristalwater-admin-onboarding-v1',scope='ADMIN_ONBOARDING',fail=(code,statusCode=400,field=null)=>{throw Object.assign(Error(code),{code,statusCode,field});};
function owner(actor){const id=Number(actor?.userId||actor?.id);if(actor?.role!=='ADMIN'||!R.positive(id)||actor.principalType==='ENV_ADMIN')fail('ONBOARD_ADMIN_REQUIRED',403);return 'ADMIN:'+id;}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('onboarding\0'+JSON.stringify(v)).digest('hex'),trim=v=>v.trim()||null;
function query(q){if(!R.object(q)||Object.keys(q).length)fail('ONBOARD_INVALID_REQUEST');}
function fields(v){const error=R.validate(v);if(error)fail('ONBOARD_INVALID_FIELDS',400,error.field);return Object.fromEntries(R.fields.map(k=>[k,v[k]]));}
async function choices(db,p,lock=false){
 const roundId=R.id(p.roundId),technicianId=R.id(p.technicianId);if(lock&&roundId)await db.$queryRaw`SELECT id FROM "Round" WHERE id=${roundId} FOR UPDATE`;if(lock&&technicianId)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${technicianId} FOR SHARE`;
 const round=roundId?await db.round.findUnique({where:{id:roundId},select:{id:true,name:true,active:true,dayOfWeek:true,recurrence:true,startsOn:true,endsOn:true,updatedAt:true}}):null,technician=technicianId?await db.technician.findUnique({where:{id:technicianId},select:{id:true,name:true,active:true,updatedAt:true}}):null;
 if(roundId&&!round?.active||technicianId&&!technician?.active)fail('ONBOARD_CHOICE_UNAVAILABLE',409);return {round,technician};
}
async function options(actor,q={},db=prisma){owner(actor);query(q);return db.$transaction(async tx=>({...envelope(actor),rounds:await tx.round.findMany({where:{active:true},select:{id:true,name:true,dayOfWeek:true},orderBy:[{name:'asc'},{id:'asc'}]}),technicians:await tx.technician.findMany({where:{active:true},select:{id:true,name:true},orderBy:[{name:'asc'},{id:'asc'}]})}),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(actor,body={},q={},db=prisma){const subject=owner(actor);query(q);if(!R.object(body)||Object.keys(body).length!==1||!Object.hasOwn(body,'fields'))fail('ONBOARD_INVALID_REQUEST');const p=fields(body.fields),selected=await choices(db,p),requestId=randomUUID(),reviewToken=jwt.sign({payloadDigest:digest(p),choiceDigest:digest(selected)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(actor),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),fields:p,plannedAt:p.createVisit?R.resolve(p.plannedDate,p.timeChoice):null,round:selected.round?{id:selected.round.id,name:selected.round.name}:null,technician:selected.technician?{id:selected.technician.id,name:selected.technician.name}:null};}
const packet=(actor,requestId,result)=>({...envelope(actor),requestId,status:result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,requestId,q={},db=prisma){const subject=owner(actor);query(q);if(!R.uuid(requestId))fail('ONBOARD_INVALID_REQUEST');const row=await db.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId:requestId.toLowerCase()}}});return packet(actor,requestId,row?.scope===scope?row.response:null);}
async function create(actor,body={},q={},db=prisma){
 const subject=owner(actor);query(q);if(!R.object(body)||typeof body.reviewToken!=='string')fail('ONBOARD_REVIEW_REQUIRED',409);if(Object.keys(body).length!==3||!R.uuid(body.requestId)||body.reviewToken.length>3000)fail('ONBOARD_INVALID_REQUEST');const p=fields(body.fields);let claims;
 try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('ONBOARD_REVIEW_REQUIRED',409);}
 if(claims.jti!==body.requestId||claims.payloadDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('ONBOARD_REVIEW_REQUIRED',409);
 const request=requests.context(actor,scope,Number(actor.userId||actor.id),body.requestId,{fields:p,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{
  const previous=await requests.recover(tx,request);if(previous)return packet(actor,body.requestId,previous);if(claims.exp*1000<=Date.now())fail('ONBOARD_REVIEW_EXPIRED',409);
  const selected=await choices(tx,p,true);if(digest(selected)!==claims.choiceDigest)fail('ONBOARD_CHOICE_CHANGED',409);
  const address=trim(p.poolAddress)||trim(p.clientAddress),location=trim(p.poolLocation)||trim(p.clientZone),serialNumber=trim(p.serialNumber);
  // Serialize duplicate checks for this creation flow without rewriting historical records.
  await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${ 'admin-onboard-pool:'+JSON.stringify([address,location,p.poolType]) }))::text`;
  if(serialNumber)await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${ 'admin-onboard-serial:'+serialNumber }))::text`;
  if(address&&location&&await tx.pool.findFirst({where:{address,location,type:p.poolType},select:{id:true}})||serialNumber&&await tx.pool.findUnique({where:{serialNumber},select:{id:true}}))fail('ONBOARD_DUPLICATE_POOL',409);
  let round=selected.round;if(p.roundMode==='new'){
   await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${ 'admin-onboard-round:'+JSON.stringify([p.roundName.trim(),Number(p.roundDay)]) }))::text`;
   if(await tx.round.findFirst({where:{name:p.roundName.trim(),dayOfWeek:Number(p.roundDay)},select:{id:true}}))fail('ONBOARD_DUPLICATE_ROUND',409);
   round=await tx.round.create({data:{name:p.roundName.trim(),dayOfWeek:Number(p.roundDay),active:true}});
  }
  const amount=R.decimal(p.poolMonthly),client=await tx.client.create({data:{name:p.clientName.trim(),phone:trim(p.clientPhone),email:trim(p.clientEmail),address:trim(p.clientAddress),zone:trim(p.clientZone),fiscalNif:trim(p.clientNif),requiresInvoice:p.requiresInvoice,status:'SETUP',active:true,billingActive:false,paymentStatus:'BILLING_DISABLED',monthlyFee:amount,monthlyAmount:amount,source:'OPERATIONAL_FLOW'}});
  const pool=await tx.pool.create({data:{clientId:client.id,name:p.poolName.trim(),type:p.poolType,address,location,zone:trim(p.clientZone),serialNumber,volumeM3:R.decimal(p.volumeM3),monthlyAmount:amount,serviceFrequency:R.decimal(p.serviceFrequency),estimatedMinutes:R.decimal(p.estimatedMinutes),scheduleMode:'FLOW_CONTROLLED',active:true,notes:trim(p.specialObservations),source:'OPERATIONAL_FLOW'}});
  const technicalSheet=await tx.technicalSheet.create({data:{poolId:pool.id,volumeM3:pool.volumeM3,disinfectionType:p.disinfectionType,...Object.fromEntries(['targetPhMin','targetPhMax','targetChlorineMin','targetChlorineMax','targetAlkalinityMin','targetAlkalinityMax','targetOrpMinMv','pumpHorsePower'].map(k=>[k,R.decimal(p[k])])),...Object.fromEntries(['filterBrandModel','chlorinatorModel','technicalRoomLocation','specialObservations'].map(k=>[k,trim(p[k])]))}});
  if(round){const maximum=await tx.roundPool.aggregate({where:{roundId:round.id},_max:{order:true}});await tx.roundPool.create({data:{roundId:round.id,poolId:pool.id,order:(maximum._max.order||0)+1}});}
  const planned=p.createVisit?new Date(R.resolve(p.plannedDate,p.timeChoice)):null,visit=p.createVisit?await tx.serviceVisit.create({data:{clientId:client.id,poolId:pool.id,roundId:round?.id||null,technicianId:selected.technician?.id||null,plannedDate:planned,date:planned,status:selected.technician?'PLANNED':'PENDING_TECHNICIAN',reason:'FIRST_SERVICE',notes:'Visita criada pela entrada guiada; valor de execução não apurado.',revenue:0}}):null;
  const pending=[];if(!round)pending.push('ROUND_REQUIRED');if(visit&&!selected.technician)pending.push('TECHNICIAN_REQUIRED');for(const step of pending)await tx.notification.create({data:{clientId:client.id,type:'OPERATIONAL_PENDING',eventType:'OPERATIONAL_FLOW',title:'Pendência operacional',message:step==='ROUND_REQUIRED'?'Piscina sem ronda atribuída.':'Primeira visita sem técnico atribuído.',role:'ADMIN',severity:'WARNING',metadata:{step,poolId:pool.id,visitId:visit?.id||null,requestId:body.requestId}}});
  const audit=await tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:subject,action:'ADMIN_ONBOARDING_CREATED',entity:'Client',entityId:String(client.id),metadata:{version:1,requestId:body.requestId,clientId:client.id,poolId:pool.id,technicalSheetId:technicalSheet.id,roundId:round?.id||null,visitId:visit?.id||null,pending}}});
  const saved=await requests.confirm(tx,request,{client:{id:client.id,name:client.name,status:client.status,billingActive:client.billingActive},pool:{id:pool.id,clientId:client.id,name:pool.name},technicalSheetId:technicalSheet.id,round:round?{id:round.id,name:round.name}:null,technician:selected.technician?{id:selected.technician.id,name:selected.technician.name}:null,visit:visit?{id:visit.id,plannedDate:visit.plannedDate.toISOString(),status:visit.status,revenue:visit.revenue}:null,pending,auditId:audit.id});return packet(actor,body.requestId,saved);
 },{maxWait:15000,timeout:20000});}catch(error){if(error.code==='FIELD_REQUEST_REUSED')fail('ONBOARD_REQUEST_CONFLICT',409);if(error.code==='P2002')fail('ONBOARD_DUPLICATE_POOL',409);throw error;}
}
module.exports={options,review,result,create,owner};
