'use strict';
const {prisma}=require('../prismaClient'),{normalizeRole}=require('../utils/roles'),R=require('../../frontend/cw-vehicle-consumption-rules'),P=require('../../frontend/cw-field-guide-projection');
const field=a=>['TECHNICIAN','TEAM_LEADER'].includes(normalizeRole(a?.role)),fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){const id=Number(a?.technicianId||a?.id),userId=Number(a?.userId||a?.id);if(!field(a)||!R.positive(id)||a.principalType==='USER'&&(!R.positive(userId)||!R.positive(Number(a.technicianId))))fail('FIELD_GUIDES_FORBIDDEN',403);return a.principalType==='USER'?'USER:'+userId+':TECH:'+id:'TECH:'+id;}
const itemSelect=Object.fromEntries(P.fields.item.filter(k=>!['workGuideId','initialQty','usedQty','createdAt','updatedAt'].includes(k)).map(k=>[k,true]));
const transportSelect={...P.select('transport'),vehicle:{select:P.select('vehicle')},items:{select:itemSelect,orderBy:{id:'asc'}}};
const workSelect={...P.select('work'),vehicle:{select:P.select('vehicle')},technician:{select:P.select('technician')},guide:{select:transportSelect},items:{select:Object.fromEntries(P.fields.item.filter(k=>k!=='guideId').map(k=>[k,true])),orderBy:{id:'asc'}}};
const order=[{createdAt:'desc'},{id:'desc'}],movementSelect={...P.select('movement'),notes:true};
function query(kind,q){const allowed=['vehicleId','technicianId',...(['transport','work','maintenance','movements'].includes(kind)?['limit','offset']:[]),...(['transport','work','maintenance'].includes(kind)?['status']:[]),...(kind==='movements'?['workGuideId','transportGuideId','movementType','maxId']:[]),...(kind==='vehicles'?['active']:[]),...(kind==='stock'?['includeMovements']:[])];if(!R.object(q)||Object.keys(q).some(k=>!allowed.includes(k)))fail('FIELD_GUIDES_INVALID_QUERY');const out={limit:200,offset:0};for(const [k,v]of Object.entries(q)){if(k==='maxId'){if(typeof v!=='string'||! /^(?:0|[1-9]\d{0,9})$/.test(v)||Number(v)>2147483647)fail('FIELD_GUIDES_INVALID_QUERY');out[k]=Number(v);}else if(k==='includeMovements'){if(!['true','false'].includes(v))fail('FIELD_GUIDES_INVALID_QUERY');out[k]=v==='true';}else if(k.endsWith('Id')||k==='limit'){const id=R.id(v);if(!id||k==='limit'&&id>200)fail('FIELD_GUIDES_INVALID_QUERY');out[k]=id;}else if(k==='offset'){if(typeof v!=='string'||! /^(?:0|[1-9]\d{0,7})$/.test(v)||Number(v)>10000000)fail('FIELD_GUIDES_INVALID_QUERY');out[k]=Number(v);}else{if(!R.text(v,80)||k==='active'&&!['all','true'].includes(v))fail('FIELD_GUIDES_INVALID_QUERY');out[k]=v;}}return out;}
async function context(tx,a,q,pathId){const technicianId=Number(a.technicianId||a.id),tech=await tx.technician.findUnique({where:{id:technicianId},select:{id:true,vehicleId:true,active:true,deletedAt:true}});if(!tech?.active||tech.deletedAt)fail('FIELD_GUIDES_FORBIDDEN',403);const vehicleId=tech.vehicleId;if(q.technicianId&&q.technicianId!==technicianId||q.vehicleId&&q.vehicleId!==vehicleId||pathId&&pathId!==vehicleId)fail('FIELD_GUIDES_FORBIDDEN',403);const vehicle=vehicleId?await tx.vehicle.findUnique({where:{id:vehicleId},select:P.select('vehicle')}):null;if(vehicleId&&(!vehicle||!vehicle.active||vehicle.deletedAt))fail('FIELD_GUIDES_FORBIDDEN',403);return {technicianId,vehicleId:vehicle?.id??null,vehicle};}
async function documents(tx,rows){if(!rows.length)return rows;const records=await tx.systemSetting.findMany({where:{key:{in:rows.map(r=>'transport_guide_at_document_'+r.id)}},select:{key:true,value:true}});return rows.map(r=>{const raw=records.find(v=>v.key==='transport_guide_at_document_'+r.id);let doc=null;if(raw){try{const value=JSON.parse(raw.value);if(!R.object(value)||typeof value.url!=='string'||!value.url.trim()||value.guideId!==undefined&&value.guideId!==r.id||value.vehicleId!==undefined&&value.vehicleId!==r.vehicleId)throw Error();doc=P.document({...value,guideId:r.id,url:value.storage==='DATABASE'&&R.positive(value.versionId)?'/api/transport-guide-documents/'+r.id+'/files/'+value.versionId:'/api/transport-guide-documents/current/'+r.id});}catch(_){fail('FIELD_GUIDES_DATA_REVIEW',409);}}return {...r,officialDocument:doc};});}
function workCheck(rows,c){for(const r of rows)if(r.technicianId!==c.technicianId||r.vehicleId!==c.vehicleId||r.guide&&r.guide.vehicleId!==c.vehicleId)fail('FIELD_GUIDES_DATA_REVIEW',409);return rows;}
async function movementScope(tx,c,q={}){const works=await tx.workGuide.findMany({where:{vehicleId:c.vehicleId??-1,technicianId:c.technicianId},select:{id:true}}),ids=works.map(r=>r.id);if(q.workGuideId&&!ids.includes(q.workGuideId))fail('FIELD_GUIDES_FORBIDDEN',403);if(q.transportGuideId&&!await tx.transportGuide.findFirst({where:{id:q.transportGuideId,vehicleId:c.vehicleId??-1},select:{id:true}}))fail('FIELD_GUIDES_FORBIDDEN',403);return {vehicleId:c.vehicleId??-1,AND:[{OR:[{technicianId:c.technicianId},{technicianId:null}]},{OR:[{workGuideId:{in:ids}},{workGuideId:null,technicianId:c.technicianId}]}],...(q.workGuideId?{workGuideId:q.workGuideId}:{}),...(q.transportGuideId?{transportGuideId:q.transportGuideId}:{}),...(q.movementType?{movementType:q.movementType}:{})};}
async function movements(tx,rows,c){const visits=await tx.serviceVisit.findMany({where:{id:{in:rows.map(r=>r.visitId).filter(Boolean)}},select:{id:true,technicianId:true,pool:{select:{name:true,address:true,location:true,zone:true}},client:{select:{name:true,address:true}}}}),extras=await tx.extraVisit.findMany({where:{id:{in:rows.map(r=>r.extraVisitId).filter(Boolean)}},select:{id:true,technicianId:true}});return rows.map(row=>{const visit=visits.find(v=>v.id===row.visitId),extra=extras.find(v=>v.id===row.extraVisitId);if(row.visitId&&(!visit||visit.technicianId!==c.technicianId)||row.extraVisitId&&(!extra||extra.technicianId!==c.technicianId))fail('FIELD_GUIDES_DATA_REVIEW',409);const meta=P.metadata(row.notes),poolName=meta.poolName||visit?.pool?.name||'',clientName=meta.clientName||visit?.client?.name||'',location=meta.location||visit?.pool?.address||visit?.pool?.location||visit?.pool?.zone||visit?.client?.address||'';return P.movement({...row,poolName,clientName,location,locationLabel:[poolName,clientName,location].filter(Boolean).join(' - ')||(row.visitId?'Visita '+row.visitId:'Movimento manual'),readings:meta.readings,userNotes:meta.userNotes});});}
async function read(a,kind,rawId,raw={},db=prisma){const subject=owner(a),q=query(kind,raw),id=rawId===undefined?null:R.id(rawId);if(rawId!==undefined&&!id)fail('FIELD_GUIDES_INVALID_QUERY');return db.$transaction(async tx=>{const pathVehicle=['stock','latest','latest-pdf','insurance','insurance-pdf'].includes(kind)?id:null,c=await context(tx,a,q,pathVehicle),base={ok:true,scope:{version:1,owner:subject,technicianId:c.technicianId,vehicleId:c.vehicleId}},vehicleId=c.vehicleId??-1;
 const paged=async(model,where,select,transform)=>{const total=await tx[model].count({where}),rows=await tx[model].findMany({where,select,orderBy:order,skip:q.offset,take:q.limit});return {total,limit:q.limit,offset:q.offset,hasMore:q.offset+rows.length<total,rows:await transform(rows)};};
 if(kind==='transport'){const p=await paged('transportGuide',{vehicleId,...(q.status?{status:q.status}:{})},{...transportSelect,workGuides:{where:{technicianId:c.technicianId,vehicleId},select:P.select('work'),orderBy:order}},rows=>documents(tx,rows));return {...base,...P.pick(p,['total','limit','offset','hasMore']),guides:p.rows.map(P.transport)};}
 if(kind==='work'){const p=await paged('workGuide',{vehicleId,technicianId:c.technicianId,...(q.status?{status:q.status}:{})},workSelect,rows=>workCheck(rows,c));return {...base,...P.pick(p,['total','limit','offset','hasMore']),workGuides:p.rows.map(P.work)};}
 if(kind==='movements'){const where=await movementScope(tx,c,q),maxId=q.maxId??(await tx.vehicleStockMovement.aggregate({where,_max:{id:true}}))._max.id??0;where.id={lte:maxId};const p=await paged('vehicleStockMovement',where,movementSelect,rows=>movements(tx,rows,c));return {...base,...P.pick(p,['total','limit','offset','hasMore']),maxId,filters:{workGuideId:q.workGuideId??null,transportGuideId:q.transportGuideId??null,movementType:q.movementType??null},movements:p.rows};}
 if(kind==='stock'||kind==='work-pdf'){let rows;if(kind==='stock')rows=await tx.workGuide.findMany({where:{vehicleId,technicianId:c.technicianId,status:'OPEN'},select:workSelect,orderBy:order,take:2});else rows=await tx.workGuide.findMany({where:{id,vehicleId,technicianId:c.technicianId},select:workSelect});if(rows.length>1)fail('FIELD_GUIDES_DATA_REVIEW',409);if(kind==='work-pdf'&&!rows.length)fail('FIELD_GUIDES_FORBIDDEN',403);const workGuide=workCheck(rows,c)[0]||null;let document=null,used=[];if(workGuide){if(workGuide.guide){const [g]=await documents(tx,[workGuide.guide]);workGuide.guide=g;document=g.officialDocument;}if(q.includeMovements!==false){const where=await movementScope(tx,c,{workGuideId:workGuide.id,movementType:'CONSUMPTION'});used=await movements(tx,await tx.vehicleStockMovement.findMany({where,select:movementSelect,orderBy:[{createdAt:'asc'},{id:'asc'}]}),c);}}return {...base,workGuide:P.work(workGuide),stock:workGuide?.items.map(P.item)||[],itemCount:workGuide?.items.length||0,movementsIncluded:q.includeMovements!==false,movements:used,transportGuideDocument:document,missingTransportGuide:!!workGuide&&!workGuide.guideId};}
 if(['latest','latest-pdf','transport-pdf','document'].includes(kind)){const rows=await tx.transportGuide.findMany({where:{vehicleId,...(['latest','latest-pdf'].includes(kind)?{status:'ACTIVE'}:{id})},select:transportSelect,orderBy:order,take:['latest','latest-pdf'].includes(kind)?2:1});if(rows.length>1)fail('FIELD_GUIDES_DATA_REVIEW',409);if(!rows.length&&!['latest'].includes(kind))fail('FIELD_GUIDES_FORBIDDEN',403);const guide=(await documents(tx,rows))[0]||null;if(kind==='document')return {...base,document:guide.officialDocument};return {...base,guide:P.transport(guide),items:guide?.items.map(P.item)||[],officialDocument:guide?.officialDocument||null};}
 if(kind==='vehicles'){if(!c.vehicle)return {...base,vehicles:[]};const work=await tx.workGuide.findMany({where:{vehicleId,technicianId:c.technicianId},select:workSelect,orderBy:order,take:1}),transport=await tx.transportGuide.findMany({where:{vehicleId},select:transportSelect,orderBy:order,take:1}),technician=await tx.technician.findUnique({where:{id:c.technicianId},select:P.select('technician')});return {...base,vehicles:[{...c.vehicle,workGuides:workCheck(work,c).map(P.work),transportGuides:transport.map(P.transport),assignedTechnicians:[technician]}]};}
 if(kind==='maintenance'){const p=await paged('vehicleMaintenanceRecord',{vehicleId,...(q.status?{status:q.status}:{})},P.select('maintenance'),rows=>rows);return {...base,...P.pick(p,['total','limit','offset','hasMore']),records:p.rows.map(P.maintenance)};}
 if(kind==='insurance'||kind==='insurance-pdf'){const records=await tx.vehicleMaintenanceRecord.findMany({where:{vehicleId},select:P.select('maintenance'),orderBy:[{dueDate:'desc'},{createdAt:'desc'},{id:'desc'}]}),insurance=records.find(r=>/insurance|seguro|apolice|apol/i.test((r.type+' '+r.title+' '+(r.notes||'')).normalize('NFD').replace(/[\u0300-\u036f]/g,'')))||null,inspection=records.find(r=>/INSPE|IPO/i.test(r.type+' '+r.title))||null;return {...base,vehicle:c.vehicle?{...c.vehicle,inspection:P.maintenance(inspection),inspectionDueDate:inspection?.dueDate||null,inspectionStatus:inspection?.status||null}:null,insurance:P.maintenance(insurance)};}
 fail('FIELD_GUIDES_INVALID_QUERY');},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:25000});}
module.exports={field,owner,query,read};
