'use strict';
const {prisma}=require('../prismaClient'),R=require('../../frontend/cw-fleet-history-rules');
const fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){const id=Number(a?.userId||a?.id);if(a?.role!=='ADMIN'||a.principalType==='ENV_ADMIN'||!R.positive(id))fail('FLEET_HISTORY_FORBIDDEN',403);return 'ADMIN:'+id;}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),serial=v=>JSON.parse(JSON.stringify(v));
const vehicleSelect={id:true,plate:true,active:true,deletedAt:true},technicianSelect={id:true,name:true},transportRef={id:true,codeAT:true,status:true};
const shared={id:true,vehicleId:true,status:true,isDraft:true,createdAt:true,updatedAt:true,closedAt:true,vehicle:{select:vehicleSelect}};
const selects={transport:{...shared,codeAT:true,validFrom:true,validUntil:true,_count:{select:{items:true,workGuides:true}}},work:{...shared,technicianId:true,guideId:true,startKm:true,endKm:true,technician:{select:technicianSelect},guide:{select:transportRef},_count:{select:{items:true}}},movement:{id:true,vehicleId:true,technicianId:true,workGuideId:true,transportGuideId:true,visitId:true,extraVisitId:true,itemName:true,itemType:true,unit:true,quantity:true,movementType:true,source:true,createdAt:true}};
const models={transport:'transportGuide',work:'workGuide',movement:'vehicleStockMovement'};
function document(row,id){if(!row)return {state:'MISSING',url:null,name:null};try{const v=JSON.parse(row.value);if(!R.object(v)||typeof v.url!=='string'||!v.url.trim()||v.guideId!==undefined&&v.guideId!==id||v.originalName!==undefined&&!R.text(v.originalName,10000)||v.filename!==undefined&&!R.text(v.filename,10000))throw Error();return {state:'RECORDED',url:'/api/transport-guide-documents/current/'+id,name:v.originalName??v.filename??null};}catch(_){return {state:'INVALID',url:null,name:null};}}
async function project(db,kind,rows){
 if(kind==='transport'){const records=await db.systemSetting.findMany({where:{key:{in:rows.map(r=>'transport_guide_at_document_'+r.id)}},select:{key:true,value:true}}),map=new Map(records.map(r=>[r.key,r]));return rows.map(({_count,...r})=>({...r,itemCount:_count.items,workCount:_count.workGuides,document:document(map.get('transport_guide_at_document_'+r.id),r.id)}));}
 if(kind==='work')return rows.map(({_count,guide,...r})=>({...r,transport:guide,itemCount:_count.items}));
 const vehicles=await db.vehicle.findMany({where:{id:{in:[...new Set(rows.map(r=>r.vehicleId).filter(Boolean))]}},select:vehicleSelect}),technicians=await db.technician.findMany({where:{id:{in:[...new Set(rows.map(r=>r.technicianId).filter(Boolean))]}},select:technicianSelect});return rows.map(r=>({...r,vehicle:vehicles.find(v=>v.id===r.vehicleId)||null,technician:technicians.find(t=>t.id===r.technicianId)||null}));
}
function whereFor(q,maxId){const where={id:{lte:maxId},...(q.recordId?{AND:[{id:q.recordId}]}:{}),...(q.vehicleId?{vehicleId:q.vehicleId}:{}),...(q.technicianId?{technicianId:q.technicianId}:{}),...(q.transportGuideId?{[q.kind==='work'?'guideId':'transportGuideId']:q.transportGuideId}:{}),...(q.workGuideId?{workGuideId:q.workGuideId}:{}),...(q.status?{[q.kind==='movement'?'movementType':'status']:q.status}:{})};
 const dates=R.bounds(q.from,q.to);if(dates.from||dates.to)where.createdAt={...(dates.from?{gte:new Date(dates.from)}:{}),...(dates.to?{lt:new Date(dates.to)}:{})};
 if(q.q){const contains=q.q.replace(/[\\%_]/g,'\\$&'),filter={contains,mode:'insensitive'};where.OR=q.kind==='transport'?[{codeAT:filter},{vehicle:{plate:filter}}]:q.kind==='work'?[{vehicle:{plate:filter}},{technician:{name:filter}}]:[{itemName:filter},{itemType:filter},{unit:filter},{source:filter}];}return where;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('FLEET_HISTORY_INVALID_QUERY');return db.$transaction(async tx=>{const model=tx[models[q.kind]],maxId=q.maxId??(await model.aggregate({_max:{id:true}}))._max.id??0,where=whereFor(q,maxId),total=await model.count({where}),rows=await project(tx,q.kind,await model.findMany({where,select:selects[q.kind],orderBy:[{createdAt:'desc'},{id:'desc'}],skip:(q.page-1)*25,take:25})),packet=serial({...envelope(a),kind:q.kind,query:q,page:q.page,size:25,total,maxId,rows});if(!R.listPacket(packet,owner(a),raw))fail('FLEET_HISTORY_DATA_REVIEW',409);return packet;},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:20000});}
async function detail(a,kind,rawId,query={},db=prisma){owner(a);const id=R.id(rawId),page=query.page===undefined?1:R.id(query.page);if(!R.kinds.includes(kind)||!id||!page||page>1000000||!R.object(query)||Object.keys(query).some(k=>k!=='page'))fail('FLEET_HISTORY_INVALID_QUERY');return db.$transaction(async tx=>{const detailSelect={...selects[kind],notes:true,...(kind==='transport'?{origin:true,destination:true,inheritedFromId:true}:kind==='work'?{inheritedFromId:true}:{})},row=await tx[models[kind]].findUnique({where:{id},select:detailSelect});if(!row)fail('FLEET_HISTORY_NOT_FOUND',404);const [record]=await project(tx,kind,[row]);let items=[];const total=kind==='movement'?0:record.itemCount;
 if(kind!=='movement')items=await tx[kind==='transport'?'transportGuideItem':'workGuideItem'].findMany({where:{[kind==='transport'?'guideId':'workGuideId']:id},select:{id:true,[kind==='transport'?'guideId':'workGuideId']:true,name:true,type:true,unit:true,quantity:true,...(kind==='work'?{initialQty:true,usedQty:true,updatedAt:true}:{})},orderBy:{id:'asc'},skip:(page-1)*25,take:25});const packet=serial({...envelope(a),kind,id,record,items,page,size:25,total});if(!R.detailPacket(packet,owner(a),kind,id,page))fail('FLEET_HISTORY_DATA_REVIEW',409);return packet;},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:20000});}
module.exports={owner,list,detail};
