'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-fleet-management-rules');
const scope='FLEET_MANAGEMENT',audience='cristalwater-fleet-management-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(actor){const id=Number(actor?.userId||actor?.id);if(actor?.role!=='ADMIN'||actor.principalType==='ENV_ADMIN'||!R.positive(id))fail('FLEET_ADMIN_REQUIRED',403);return 'ADMIN:'+id;}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('fleet-management\0'+JSON.stringify(v)).digest('hex');
const selection={id:true,plate:true,name:true,brand:true,model:true,year:true,currentKm:true,notes:true,status:true,active:true,archiveStatus:true,deletedAt:true,updatedAt:true};
const usageKeys=['technicians','workGuides','openWorkGuides','transportGuides','activeTransportGuides','movements','maintenance','logs'];
function noQuery(q){if(!R.object(q)||Object.keys(q).length)fail('FLEET_INVALID_REQUEST');}
function proposal(body){if(!R.object(body)||Object.keys(body).sort().join(',')!=='fields,operation,vehicleId'||!R.operations.includes(body.operation)||(body.operation==='CREATE'?body.vehicleId!==null:!R.positive(body.vehicleId)))fail('FLEET_INVALID_REQUEST');const fields=R.fields(body.operation,body.fields);if(!fields)fail('FLEET_INVALID_FIELDS');return {operation:body.operation,vehicleId:body.vehicleId,fields};}
async function selected(db,p,lock=false){
 let before=null;if(p.vehicleId){if(lock)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${p.vehicleId} FOR UPDATE`;before=await db.vehicle.findUnique({where:{id:p.vehicleId},select:selection});if(!before)fail('FLEET_NOT_FOUND',404);if(p.operation==='RESTORE'&&before.active&&!before.deletedAt||p.operation==='STATUS'&&(!before.active||before.deletedAt)||p.operation==='ARCHIVE'&&!before.active&&before.deletedAt)fail('FLEET_STATE_CHANGED',409);}
 if(p.fields.plate){const duplicate=await db.$queryRaw`SELECT id FROM "Vehicle" WHERE UPPER(BTRIM("plate"))=${p.fields.plate} AND id<>${p.vehicleId||0} LIMIT 1`;if(duplicate.length)fail('FLEET_PLATE_IN_USE',409);}
 const usage=Object.fromEntries(usageKeys.map(k=>[k,0]));if(p.vehicleId){const where={vehicleId:p.vehicleId};const counts=await Promise.all([db.technician.count({where}),db.workGuide.count({where}),db.workGuide.count({where:{...where,status:'OPEN'}}),db.transportGuide.count({where}),db.transportGuide.count({where:{...where,status:'ACTIVE'}}),db.vehicleStockMovement.count({where}),db.vehicleMaintenanceRecord.count({where}),db.technicianVehicleLog.count({where})]);usageKeys.forEach((k,i)=>usage[k]=counts[i]);}return {before,usage};
}
async function list(actor,raw={},db=prisma){owner(actor);const q=R.query(raw);if(!q)fail('FLEET_INVALID_QUERY');const where={...(q.active==='all'?{}:{active:q.active==='true'}),...(q.q?{OR:['plate','name','brand','model'].map(k=>({[k]:{contains:q.q,mode:'insensitive'}}))}:{})};return db.$transaction(async tx=>({...envelope(actor),page:q.page,size:25,total:await tx.vehicle.count({where}),vehicles:await tx.vehicle.findMany({where,select:selection,orderBy:[{plate:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25})}),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);const p=proposal(body),choice=await selected(db,p),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(choice)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});
 const proposed={...(choice.before||{active:true,archiveStatus:'ATIVO',deletedAt:null}),...p.fields};if(p.operation==='ARCHIVE'){proposed.active=false;proposed.status='ARCHIVED';proposed.archiveStatus='ARQUIVADO';}if(p.operation==='RESTORE'){proposed.active=true;proposed.archiveStatus='ATIVO';proposed.deletedAt=null;}
 return {...envelope(actor),operation:p.operation,vehicleId:p.vehicleId,requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),before:choice.before,proposed,usage:choice.usage};
}
const packet=(actor,requestId,result)=>({...envelope(actor),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,requestId,q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId))fail('FLEET_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const row=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(actor,requestId,row?.scope===scope?row.response:null);},{maxWait:15000,timeout:15000});}
async function commit(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.object(body)||typeof body.reviewToken!=='string')fail('FLEET_REVIEW_REQUIRED',409);if(Object.keys(body).sort().join(',')!=='fields,operation,requestId,reviewToken,vehicleId'||!R.uuid(body.requestId)||body.reviewToken.length>4000)fail('FLEET_INVALID_REQUEST');const p=proposal({operation:body.operation,vehicleId:body.vehicleId,fields:body.fields});let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('FLEET_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('FLEET_REVIEW_REQUIRED',409);
 const request=requests.context(actor,scope,Number(actor.userId||actor.id),body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const previous=await requests.recover(tx,request);if(previous)return packet(actor,body.requestId,previous);if(claims.exp*1000<=Date.now())fail('FLEET_REVIEW_EXPIRED',409);await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext('fleet-management-write'))::text`;const choice=await selected(tx,p,true);if(digest(choice)!==claims.choiceDigest)fail('FLEET_CHANGED',409);
  const data={};for(const [k,v]of Object.entries(p.fields))data[k]=v===''?null:v;
  if(p.operation==='ARCHIVE'){data.active=false;data.status='ARCHIVED';data.archiveStatus='ARQUIVADO';data.deletedAt=new Date();}if(p.operation==='RESTORE'){data.active=true;data.archiveStatus='ATIVO';data.deletedAt=null;}
  if(choice.before)data.updatedAt=new Date(Math.max(Date.now(),choice.before.updatedAt.getTime()+1));const row=p.operation==='CREATE'?await tx.vehicle.create({data:{...data,active:true},select:selection}):await tx.vehicle.update({where:{id:p.vehicleId},data,select:selection});
  const audit=await tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:subject,action:'FLEET_'+p.operation,entity:'Vehicle',entityId:String(row.id),metadata:{requestId:body.requestId,operation:p.operation,changedFields:Object.keys(data).filter(k=>k!=='updatedAt'),usage:choice.usage}}});
  return packet(actor,body.requestId,await requests.confirm(tx,request,{operation:p.operation,vehicleId:p.vehicleId,vehicle:row,auditId:audit.id}));
 },{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('FLEET_REQUEST_CONFLICT',409);if(e.code==='P2002')fail('FLEET_PLATE_IN_USE',409);throw e;}
}
async function cancel(actor,requestId,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId)||!R.object(body)||Object.keys(body).sort().join(',')!=='operation,vehicleId'||!R.operations.includes(body.operation)||(body.operation==='CREATE'?body.vehicleId!==null:!R.positive(body.vehicleId)))fail('FLEET_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope)fail('FLEET_REQUEST_CONFLICT',409);return packet(actor,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:subject,action:'FLEET_REQUEST_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:{...body}}});return packet(actor,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:Number(actor.userId||actor.id),payloadHash:'cancelled'},{...body,vehicle:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,result,commit,cancel};
