'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-operational-risk-rules');
const scope='OPERATIONAL_RISK_RULES_REVIEW',audience='cristalwater-operational-risk-rules-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){const id=Number(a?.userId||a?.id);if(a?.role!=='ADMIN'||a.principalType==='ENV_ADMIN'||!R.positive(id))fail('RISK_RULES_FORBIDDEN',403);return 'ADMIN:'+id;}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('operational-risk-rules\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
function noQuery(q){if(!R.keys(q,[]))fail('RISK_RULES_INVALID_REQUEST');}
async function selected(db,lock=false){if(lock){await db.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${'operational-risk-rules'}))::text`;await db.$queryRaw`SELECT id FROM "SystemSetting" WHERE key=${R.key} FOR UPDATE`;}const c=json({record:await db.systemSetting.findUnique({where:{key:R.key}})});if(!R.choice(c))fail('RISK_RULES_VOLUME_REVIEW',409);return c;}
async function read(a,q={},db=prisma){owner(a);noQuery(q);return {...envelope(a),choice:await selected(db)};}
async function effective(db=prisma){const record=await db.systemSetting.findUnique({where:{key:R.key},select:{value:true}}),parsed=R.parse(record?.value??null);if(!parsed.rules)fail('RISK_RULES_DATA_REVIEW',409);return {rules:parsed.rules,rulesState:parsed.state,defaultKeys:parsed.defaultKeys};}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('RISK_RULES_INVALID_FIELDS');const c=await db.$transaction(tx=>selected(tx),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});if(!R.plan(c,p))fail('RISK_RULES_REVIEW_REQUIRED',409);const requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:c,plan:R.plan(c,p)};}
const packet=(a,requestId,result)=>({...envelope(a),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(a,requestId,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId))fail('RISK_RULES_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const r=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(a,requestId,r?.scope===scope?r.response:null);},{maxWait:15000,timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('RISK_RULES_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('RISK_RULES_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('RISK_RULES_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('RISK_RULES_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,R.resourceId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('RISK_RULES_REVIEW_EXPIRED',409);const c=await selected(tx,true);if(digest(c)!==claims.choiceDigest)fail('RISK_RULES_CHANGED',409);const plan=R.plan(c,p);if(!plan)fail('RISK_RULES_REVIEW_REQUIRED',409);
 const record=c.record?await tx.systemSetting.update({where:{id:c.record.id},data:{value:plan.afterValue,updatedAt:new Date(Math.max(Date.now(),Date.parse(c.record.updatedAt)+1))}}):await tx.systemSetting.create({data:{key:R.key,value:plan.afterValue,notes:null}});
 const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:scope,entity:'SystemSetting',entityId:R.key,metadata:{requestId:body.requestId,reason:p.reason,before:c,plan,after:json(record)}}});
 return packet(a,body.requestId,await requests.confirm(tx,request,{resourceId:R.resourceId,record,proposal:p,before:c,plan,auditId:audit.id}));},{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('RISK_RULES_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(a,requestId,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['resourceId'])||!R.pending(JSON.stringify({version:1,owner:subject,requestId,...body}),subject))fail('RISK_RULES_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==body.resourceId)fail('RISK_RULES_REQUEST_CONFLICT',409);return packet(a,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:'OPERATIONAL_RISK_RULES_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(a,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.resourceId,payloadHash:'cancelled'},{...body,record:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,read,effective,review,commit,result,cancel};
