'use strict';
const {prisma}=require('../prismaClient'),{createHmac}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),vault=require('./credentialVaultService'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-supplier-rules');
const fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});},scopes={supplier:'SUPPLIER_CREATE',link:'SUPPLIER_LINK_CREATE'};
function owner(actor){const id=Number(actor?.userId||actor?.id);if(actor?.role!=='ADMIN'||actor.principalType==='ENV_ADMIN'||!R.positive(id))fail('SUPPLIER_ADMIN_REQUIRED',403);return 'ADMIN:'+id;}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()});
const selection={id:true,...Object.fromEntries(Object.keys(R.limits).filter(k=>k!=='password').map(k=>[k,true])),encryptedPassword:true,favorite:true,active:true,lastAccessAt:true,createdAt:true,updatedAt:true};
function safe(row){const {encryptedPassword,...rest}=row;return {...rest,hasPassword:!!encryptedPassword};}
function noQuery(q){if(!R.object(q)||Object.keys(q).length)fail('SUPPLIER_INVALID_REQUEST');}
async function list(actor,kind,raw={},db=prisma){owner(actor);const q=R.query(raw);if(!q)fail('SUPPLIER_INVALID_QUERY');const where={};if(q.active!=='all')where.active=q.active==='true';if(q.category)where.category=q.category;
 if(q.q)where.OR=(kind==='supplier'?['name','category','username','notes']:['title','category','notes']).map(k=>({[k]:{contains:q.q,mode:'insensitive'}}));
 const table=kind==='supplier'?'supplierAccount':'supplierQuickLink',name=kind==='supplier'?'suppliers':'links';
 return db.$transaction(async tx=>{const total=await tx[table].count({where}),rows=await tx[table].findMany({where,orderBy:[{favorite:'desc'},{[kind==='supplier'?'name':'title']:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25,...(kind==='supplier'?{select:selection}:{include:{supplier:{select:{id:true,name:true,active:true}}}})});return {...envelope(actor),page:q.page,size:25,total,[name]:kind==='supplier'?rows.map(safe):rows};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});
}
const packet=(actor,kind,requestId,result)=>({...envelope(actor),kind,requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,kind,requestId,q={},db=prisma){const subject=owner(actor);noQuery(q);if(!scopes[kind]||!R.uuid(requestId))fail('SUPPLIER_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const row=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(actor,kind,requestId,row?.scope===scopes[kind]?row.response:null);},{maxWait:15000,timeout:15000});}
async function audit(tx,actor,action,entity,id,metadata={}){return tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:owner(actor),action,entity,entityId:String(id),metadata}});}
async function create(actor,kind,body={},q={},db=prisma){owner(actor);noQuery(q);if(!R.object(body)||!R.uuid(body.requestId))fail('SUPPLIER_REQUEST_REQUIRED',409);if(Object.keys(body).sort().join(',')!=='fields,requestId'||!scopes[kind])fail('SUPPLIER_INVALID_REQUEST');const p=kind==='supplier'?R.supplier(body.fields):R.link(body.fields);if(!p)fail('SUPPLIER_INVALID_FIELDS');
 // A keyed digest prevents the receipt table from becoming a password-guessing oracle.
 const digest=createHmac('sha256',getJwtSecret()).update('supplier-write\0'+JSON.stringify(Object.fromEntries(Object.entries(p).sort(([a],[b])=>a.localeCompare(b))))).digest('hex'),request=requests.context(actor,scopes[kind],Number(actor.userId||actor.id),body.requestId,{digest});
 try{return await db.$transaction(async tx=>{const previous=await requests.recover(tx,request);if(previous)return packet(actor,kind,body.requestId,previous);let row;
  if(kind==='supplier'){const {password,...fields}=p;row=await tx.supplierAccount.create({data:{...fields,encryptedPassword:vault.encryptSecret(password),loginUrl:fields.loginUrl||fields.website||null}});}
  else{const {supplierVersion,...fields}=p;if(fields.supplierId){await tx.$queryRaw`SELECT id FROM "SupplierAccount" WHERE id=${fields.supplierId} FOR SHARE`;const selected=await tx.supplierAccount.findUnique({where:{id:fields.supplierId},select:{id:true,active:true,updatedAt:true}});if(!selected?.active||selected.updatedAt.toISOString()!==supplierVersion)fail('SUPPLIER_SELECTION_CHANGED',409);}row=await tx.supplierQuickLink.create({data:fields});}
  const entry=await audit(tx,actor,kind==='supplier'?'SUPPLIER_CREATED':'SUPPLIER_LINK_CREATED',kind==='supplier'?'SupplierAccount':'SupplierQuickLink',row.id,{requestId:body.requestId});
  return packet(actor,kind,body.requestId,await requests.confirm(tx,request,{kind,id:row.id,auditId:entry.id}));
 },{maxWait:15000,timeout:15000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('SUPPLIER_REQUEST_CONFLICT',409);throw e;}
}
async function update(actor,rawId,body={},q={},db=prisma){owner(actor);noQuery(q);const id=R.id(rawId);if(!id)fail('SUPPLIER_INVALID_ID');if(!R.object(body)||!R.iso(body.expectedUpdatedAt))fail('SUPPLIER_VERSION_REQUIRED',409);if(Object.keys(body).sort().join(',')!=='expectedUpdatedAt,fields')fail('SUPPLIER_INVALID_REQUEST');const p=R.supplier(body.fields,true);if(!p)fail('SUPPLIER_INVALID_FIELDS');
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "SupplierAccount" WHERE id=${id} FOR UPDATE`;const prior=await tx.supplierAccount.findUnique({where:{id}});if(!prior)fail('SUPPLIER_NOT_FOUND',404);if(prior.updatedAt.toISOString()!==body.expectedUpdatedAt)fail('SUPPLIER_CHANGED',409);const {password,...data}=p;if(Object.hasOwn(p,'password'))data.encryptedPassword=password?vault.encryptSecret(password):null;data.updatedAt=new Date(Math.max(Date.now(),prior.updatedAt.getTime()+1));const row=await tx.supplierAccount.update({where:{id},data,select:selection});await audit(tx,actor,'SUPPLIER_UPDATED','SupplierAccount',id,{fields:Object.keys(p)});return {...envelope(actor),supplier:safe(row)};},{maxWait:15000,timeout:15000});
}
async function reveal(actor,rawId,body={},q={},db=prisma){owner(actor);noQuery(q);const id=R.id(rawId);if(!id)fail('SUPPLIER_INVALID_ID');if(!R.object(body)||Object.keys(body).length!==1||!R.iso(body.expectedUpdatedAt))fail('SUPPLIER_VERSION_REQUIRED',409);
 return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "SupplierAccount" WHERE id=${id} FOR UPDATE`;const row=await tx.supplierAccount.findUnique({where:{id},select:{id:true,active:true,encryptedPassword:true,updatedAt:true}});if(!row)fail('SUPPLIER_NOT_FOUND',404);if(!row.active||row.updatedAt.toISOString()!==body.expectedUpdatedAt)fail('SUPPLIER_CHANGED',409);let password;try{password=vault.decryptSecret(row.encryptedPassword);}catch(_){fail('SUPPLIER_CREDENTIAL_UNAVAILABLE',409);}if(typeof password!=='string'||!password.length)fail('SUPPLIER_CREDENTIAL_UNAVAILABLE',409);
  const entry=await audit(tx,actor,'SUPPLIER_CREDENTIAL_READ','SupplierAccount',id);const saved=await tx.supplierAccount.update({where:{id},data:{lastAccessAt:new Date(),updatedAt:new Date(Math.max(Date.now(),row.updatedAt.getTime()+1))},select:{updatedAt:true,lastAccessAt:true}});return {...envelope(actor),id,password,...saved,auditId:entry.id};
 },{maxWait:15000,timeout:15000});
}
async function cancel(actor,kind,requestId,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!scopes[kind]||!R.uuid(requestId)||!R.object(body)||Object.keys(body).length)fail('SUPPLIER_INVALID_REQUEST');return db.$transaction(async tx=>{
 await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;
 const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scopes[kind])fail('SUPPLIER_REQUEST_CONFLICT',409);return packet(actor,kind,requestId,saved.response);}
 const entry=await audit(tx,actor,'SUPPLIER_REQUEST_CANCELLED','FieldWriteRequest',requestId,{kind});
 const result=await requests.confirm(tx,{owner:subject,requestId,scope:scopes[kind],resourceId:Number(actor.userId||actor.id),payloadHash:'cancelled'},{kind,cancelled:true,id:null,auditId:entry.id});return packet(actor,kind,requestId,result);
 },{maxWait:15000,timeout:15000});}
module.exports={owner,list,create,result,update,reveal,cancel};
