'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),pins=require('./technicianPinService'),R=require('../../frontend/cw-technician-management-rules');
const scope='TECHNICIAN_MANAGEMENT',audience='cristalwater-technician-management-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(actor){const id=Number(actor?.userId||actor?.id);if(actor?.role!=='ADMIN'||actor.principalType==='ENV_ADMIN'||!R.positive(id))fail('TECH_MANAGE_ADMIN_REQUIRED',403);return 'ADMIN:'+id;}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('technician-management\0'+JSON.stringify(v)).digest('hex');
const selection={id:true,name:true,email:true,phone:true,zone:true,vehicleId:true,role:true,active:true,archiveStatus:true,deletedAt:true,updatedAt:true,pin:true,authVersion:true};
const safe=row=>{if(!row)return null;const {pin,authVersion,...value}=row;return {...value,hasPin:!!pin};};
function noQuery(q){if(!R.object(q)||Object.keys(q).length)fail('TECH_MANAGE_INVALID_REQUEST');}
function proposal(body){if(!R.object(body)||Object.keys(body).sort().join(',')!=='fields,operation,technicianId'||!R.operations.includes(body.operation)||(body.operation==='CREATE'?body.technicianId!==null:!R.positive(body.technicianId)))fail('TECH_MANAGE_INVALID_REQUEST');const fields=R.fields(body.operation,body.fields);if(!fields)fail('TECH_MANAGE_INVALID_FIELDS');return {operation:body.operation,technicianId:body.technicianId,fields};}
async function selected(db,p,lock=false){let before=null;if(p.technicianId){if(lock)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${p.technicianId} FOR UPDATE`;before=await db.technician.findUnique({where:{id:p.technicianId},select:selection});if(!before)fail('TECH_MANAGE_NOT_FOUND',404);if(p.operation==='ACTIVATE'&&before.active&&!before.deletedAt||p.operation==='DEACTIVATE'&&(!before.active||before.deletedAt)||p.operation==='ARCHIVE'&&before.deletedAt)fail('TECH_MANAGE_STATE_CHANGED',409);}
 const vehicleId=['CREATE','EDIT'].includes(p.operation)?p.fields.vehicleId:before?.vehicleId||null;
 if(lock&&vehicleId)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${vehicleId} FOR SHARE`;
 const vehicle=vehicleId?await db.vehicle.findUnique({where:{id:vehicleId},select:{id:true,plate:true,name:true,active:true,updatedAt:true}}):null;
 if(vehicleId&&(!vehicle||!vehicle.active&&vehicleId!==before?.vehicleId))fail('TECH_MANAGE_VEHICLE_CHANGED',409);
 const email=['CREATE','EDIT'].includes(p.operation)?p.fields.email:before?.email;
 const linked=email?await db.user.findMany({where:{email:{equals:email,mode:'insensitive'}},select:{id:true,name:true,email:true,role:true,active:true,updatedAt:true},orderBy:{id:'asc'}}):[];
 if(['CREATE','EDIT'].includes(p.operation)&&email){if(await db.technician.findFirst({where:{email:{equals:email,mode:'insensitive'},...(p.technicianId?{id:{not:p.technicianId}}:{})},select:{id:true}}))fail('TECH_MANAGE_EMAIL_IN_USE',409);if(linked.length>1||linked.some(u=>!['TECH','TECHNICIAN','TEAM_LEADER'].includes(u.role)||u.email!==email))fail('TECH_MANAGE_ACCOUNT_REVIEW',409);}
 return {before,vehicle,user:linked.length===1?linked[0]:null};
}
async function list(actor,raw={},db=prisma){owner(actor);const q=R.query(raw);if(!q)fail('TECH_MANAGE_INVALID_QUERY');const where={...(q.active==='all'?{}:{active:q.active==='true'}),...(q.q?{OR:['name','email','phone','zone'].map(k=>({[k]:{contains:q.q,mode:'insensitive'}}))}:{})};return db.$transaction(async tx=>({...envelope(actor),page:q.page,size:25,total:await tx.technician.count({where}),technicians:(await tx.technician.findMany({where,select:selection,orderBy:[{name:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25})).map(safe)}),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function options(actor,q={},db=prisma){owner(actor);noQuery(q);return {...envelope(actor),vehicles:await db.vehicle.findMany({where:{active:true},select:{id:true,name:true,plate:true},orderBy:[{plate:'asc'},{id:'asc'}]})};}
async function review(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);const p=proposal(body),choice=await selected(db,p),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(choice)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});
 const {pin,...fields}=p.fields,proposed={...(safe(choice.before)||{role:'TECHNICIAN',active:true,archiveStatus:'ATIVO',deletedAt:null,hasPin:false}),...fields,hasPin:p.operation==='CREATE'||p.operation==='PIN'?!!pin:!!choice.before?.pin};if(['DEACTIVATE','ARCHIVE'].includes(p.operation))proposed.active=false;if(p.operation==='ACTIVATE'){proposed.active=true;proposed.archiveStatus='ATIVO';proposed.deletedAt=null;}if(p.operation==='ARCHIVE')proposed.archiveStatus='ARQUIVADO';
 return {...envelope(actor),operation:p.operation,technicianId:p.technicianId,requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),before:safe(choice.before),proposed,vehicle:choice.vehicle?{id:choice.vehicle.id,name:choice.vehicle.name,plate:choice.vehicle.plate,active:choice.vehicle.active}:null,user:choice.user?{id:choice.user.id,name:choice.user.name,email:choice.user.email,role:choice.user.role,active:choice.user.active}:null,revokesSessions:['PIN','ACTIVATE','DEACTIVATE','ARCHIVE'].includes(p.operation)||p.operation==='EDIT'&&(choice.before.email||'')!==p.fields.email};
}
const packet=(actor,requestId,result)=>({...envelope(actor),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,requestId,q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId))fail('TECH_MANAGE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const row=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(actor,requestId,row?.scope===scope?row.response:null);},{maxWait:15000,timeout:15000});}
async function commit(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.object(body)||typeof body.reviewToken!=='string')fail('TECH_MANAGE_REVIEW_REQUIRED',409);if(Object.keys(body).sort().join(',')!=='fields,operation,requestId,reviewToken,technicianId'||!R.uuid(body.requestId)||body.reviewToken.length>4000)fail('TECH_MANAGE_INVALID_REQUEST');const p=proposal({operation:body.operation,technicianId:body.technicianId,fields:body.fields});let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('TECH_MANAGE_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('TECH_MANAGE_REVIEW_REQUIRED',409);
 const request=requests.context(actor,scope,Number(actor.userId||actor.id),body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const previous=await requests.recover(tx,request);if(previous)return packet(actor,body.requestId,previous);if(claims.exp*1000<=Date.now())fail('TECH_MANAGE_REVIEW_EXPIRED',409);await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext('technician-management-write'))::text`;const choice=await selected(tx,p,true);if(digest(choice)!==claims.choiceDigest)fail('TECH_MANAGE_CHANGED',409);
  const data={};if(['CREATE','EDIT'].includes(p.operation))for(const k of ['name','email','phone','zone','vehicleId'])data[k]=p.fields[k]===''?null:p.fields[k];
  if((p.operation==='CREATE'||p.operation==='PIN')&&p.fields.pin){if((await pins.findMatches(tx,p.fields.pin,{excludeId:p.technicianId,stopAfter:1})).length)fail('TECH_MANAGE_PIN_IN_USE',409);data.pin=await pins.hash(p.fields.pin);}
  const revoke=['PIN','ACTIVATE','DEACTIVATE','ARCHIVE'].includes(p.operation)||p.operation==='EDIT'&&(choice.before.email||'')!==p.fields.email;
  if(revoke)data.authVersion={increment:1};if(['DEACTIVATE','ARCHIVE'].includes(p.operation))data.active=false;if(p.operation==='ACTIVATE'){data.active=true;data.archiveStatus='ATIVO';data.deletedAt=null;}if(p.operation==='ARCHIVE'){data.archiveStatus='ARQUIVADO';data.deletedAt=new Date();}
  if(choice.before)data.updatedAt=new Date(Math.max(Date.now(),choice.before.updatedAt.getTime()+1));const row=p.operation==='CREATE'?await tx.technician.create({data:{...data,active:true,role:'TECHNICIAN'},select:selection}):await tx.technician.update({where:{id:p.technicianId},data,select:selection});
  const audit=await tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:subject,action:'TECHNICIAN_'+p.operation,entity:'Technician',entityId:String(row.id),metadata:{requestId:body.requestId,operation:p.operation,changedFields:Object.keys(data).filter(k=>k!=='updatedAt'),revokesSessions:revoke}}});
  return packet(actor,body.requestId,await requests.confirm(tx,request,{operation:p.operation,technicianId:p.technicianId,technician:safe(row),auditId:audit.id,revokesSessions:revoke}));
 },{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('TECH_MANAGE_REQUEST_CONFLICT',409);if(e.code==='P2002')fail('TECH_MANAGE_EMAIL_IN_USE',409);throw e;}
}
async function cancel(actor,requestId,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId)||!R.object(body)||Object.keys(body).sort().join(',')!=='operation,technicianId'||!R.operations.includes(body.operation)||(body.operation==='CREATE'?body.technicianId!==null:!R.positive(body.technicianId)))fail('TECH_MANAGE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope)fail('TECH_MANAGE_REQUEST_CONFLICT',409);return packet(actor,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(actor.userId||actor.id),actor:subject,action:'TECHNICIAN_REQUEST_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:{...body}}});return packet(actor,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:Number(actor.userId||actor.id),payloadHash:'cancelled'},{...body,technician:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,safe,list,options,review,result,commit,cancel};
