'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-transport-guide-rules');
const scope='TRANSPORT_GUIDE_CREATE',audience='cristalwater-transport-create-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){if(a?.role!=='ADMIN'||a.principalType==='ENV_ADMIN'||!R.positive(Number(a.userId||a.id)))fail('TRANSPORT_FORBIDDEN',403);return requests.owner(a);}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('transport-create\0'+JSON.stringify(v)).digest('hex');
const vehicleSelect={id:true,plate:true,name:true,active:true,deletedAt:true,status:true,updatedAt:true},techSelect={id:true,name:true,vehicleId:true,authVersion:true},workSelect={id:true,vehicleId:true,guideId:true,technicianId:true,startKm:true,endKm:true,notes:true,isDraft:true,status:true,updatedAt:true,items:{orderBy:{id:'asc'},take:101,select:{id:true,workGuideId:true,name:true,type:true,unit:true,initialQty:true,quantity:true,usedQty:true,updatedAt:true}}},transportSelect={id:true,vehicleId:true,codeAT:true,status:true,isDraft:true,validFrom:true,validUntil:true,updatedAt:true};
const serial=v=>JSON.parse(JSON.stringify(v));
function noQuery(q){if(!R.keys(q,[]))fail('TRANSPORT_INVALID_REQUEST');}
async function lockVehicle(tx,id){await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`guide-vehicle:${id}`}))::text`;}
async function choices(db,id,lock=false){
 if(lock){await lockVehicle(db,id);await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE "vehicleId"=${id} AND status='OPEN' ORDER BY id FOR UPDATE`;await db.$queryRaw`SELECT id FROM "Technician" WHERE "vehicleId"=${id} ORDER BY id FOR SHARE`;await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${id} FOR UPDATE`;await db.$queryRaw`SELECT id FROM "TransportGuide" WHERE "vehicleId"=${id} AND status='ACTIVE' ORDER BY id FOR UPDATE`;await db.$queryRaw`SELECT i.id FROM "WorkGuideItem" i JOIN "WorkGuide" w ON w.id=i."workGuideId" WHERE w."vehicleId"=${id} AND w.status='OPEN' ORDER BY i.id FOR UPDATE OF i`;}
 const vehicle=await db.vehicle.findUnique({where:{id},select:vehicleSelect});if(!vehicle?.active||vehicle.deletedAt)fail('TRANSPORT_VEHICLE_UNAVAILABLE',409);
 const technicians=await db.technician.findMany({where:{vehicleId:id,active:true,deletedAt:null},select:techSelect,orderBy:{id:'asc'},take:101}),workGuides=await db.workGuide.findMany({where:{vehicleId:id,status:'OPEN'},select:workSelect,orderBy:{id:'asc'},take:101}),transportGuides=await db.transportGuide.findMany({where:{vehicleId:id,status:'ACTIVE'},select:transportSelect,orderBy:{id:'asc'},take:101});
 if([technicians,workGuides,transportGuides].some(a=>a.length>100)||workGuides.some(w=>w.items.length>100))fail('TRANSPORT_VOLUME_REVIEW',409);
 const value=serial({...vehicle,technicians,workGuides,transportGuides});if(!R.choice(value))fail('TRANSPORT_DATA_REVIEW',409);return value;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('TRANSPORT_INVALID_QUERY');return db.$transaction(async tx=>{const where={active:true,deletedAt:null,...(q.vehicleId?{id:q.vehicleId}:{}),...(q.q?{OR:[{plate:{contains:q.q,mode:'insensitive'}},{name:{contains:q.q,mode:'insensitive'}}]}:{})},rows=await tx.vehicle.findMany({where,select:{id:true},orderBy:{id:'desc'},skip:(q.page-1)*25,take:25}),vehicles=[];for(const row of rows)vehicles.push(await choices(tx,row.id));return {...envelope(a),page:q.page,size:25,total:await tx.vehicle.count({where}),vehicles};},{isolationLevel:'RepeatableRead',timeout:20000});}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('TRANSPORT_INVALID_FIELDS');const choice=await db.$transaction(async tx=>{const c=await choices(tx,p.vehicleId);if(p.codeAT&&await tx.transportGuide.findUnique({where:{codeAT:p.codeAT},select:{id:true}}))fail('TRANSPORT_CODE_EXISTS',409);return c;},{isolationLevel:'RepeatableRead',timeout:15000}),plan=R.plan(p,choice);if(!plan)fail('TRANSPORT_ASSOCIATION_REVIEW',409);const requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(choice)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice,plan};}
const packet=(a,id,result)=>({...envelope(a),requestId:id,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(a,id,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(id))fail('TRANSPORT_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${id}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId:id}}});return packet(a,id,saved?.scope===scope?saved.response:null);},{timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('TRANSPORT_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('TRANSPORT_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('TRANSPORT_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('TRANSPORT_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,p.vehicleId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('TRANSPORT_REVIEW_EXPIRED',409);if(p.codeAT)await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`transport-code:${p.codeAT}`}))::text`;const c=await choices(tx,p.vehicleId,true);if(digest(c)!==claims.choiceDigest)fail('TRANSPORT_CHANGED',409);const plan=R.plan(p,c);if(!plan)fail('TRANSPORT_ASSOCIATION_REVIEW',409);if(p.codeAT&&await tx.transportGuide.findUnique({where:{codeAT:p.codeAT},select:{id:true}}))fail('TRANSPORT_CODE_EXISTS',409);
  const now=new Date(),guide=await tx.transportGuide.create({data:{vehicleId:p.vehicleId,codeAT:p.codeAT||null,origin:p.origin,destination:p.destination,notes:p.notes,validFrom:new Date(p.validFrom),validUntil:p.validUntil?new Date(p.validUntil):null,isDraft:p.isDraft,status:'ACTIVE',items:{create:p.items.map(i=>({name:i.name,type:i.type,unit:i.unit,quantity:Number(i.quantity)}))}},include:{items:{orderBy:{id:'asc'}}}});
  let work;if(p.workGuideId){work=await tx.workGuide.update({where:{id:p.workGuideId},data:{guideId:guide.id,isDraft:false,inheritedFromId:guide.id}});for(const row of plan.rows){if(row.workItemId)await tx.workGuideItem.update({where:{id:row.workItemId},data:{initialQty:row.after.initialQty,quantity:row.after.quantity,updatedAt:new Date(Math.max(Date.now(),Date.parse(c.workGuides.find(w=>w.id===p.workGuideId).items.find(i=>i.id===row.workItemId).updatedAt)+1))}});else await tx.workGuideItem.create({data:{workGuideId:work.id,name:row.name,type:row.type,unit:row.unit,...row.after}});}await tx.operationalLock.updateMany({where:{lockType:'MISSING_TRANSPORT_GUIDE',entity:'WorkGuide',entityId:work.id,status:'PENDING'},data:{status:'RESOLVED',resolvedAt:now,approvedBy:subject}});}
  else work=await tx.workGuide.create({data:{vehicleId:p.vehicleId,guideId:guide.id,technicianId:p.technicianId,startKm:p.startKm,notes:'Criada a partir da guia de transporte revista #'+guide.id,status:'OPEN',isDraft:false,inheritedFromId:guide.id,items:{create:plan.rows.map(r=>({name:r.name,type:r.type,unit:r.unit,...r.after}))}}});
  if(plan.closeWorkGuideIds.length)await tx.workGuide.updateMany({where:{id:{in:plan.closeWorkGuideIds}},data:{status:'CLOSED',closedAt:now}});
  if(plan.closeTransportGuideIds.length)await tx.transportGuide.updateMany({where:{id:{in:plan.closeTransportGuideIds}},data:{status:'CLOSED',closedAt:now}});
  const movementIds=[];for(const i of guide.items){const m=await tx.vehicleStockMovement.create({data:{vehicleId:p.vehicleId,transportGuideId:guide.id,workGuideId:work.id,technicianId:p.technicianId,itemName:i.name,itemType:i.type,unit:i.unit,quantity:i.quantity,movementType:'LOAD',source:p.workGuideId?'REVIEWED_PROVISIONAL_LINK':'REVIEWED_INITIAL_STOCK',notes:JSON.stringify({requestId:body.requestId,owner:subject,initialQuantity:true})}});movementIds.push(m.id);}
  const workGuide=await tx.workGuide.findUniqueOrThrow({where:{id:work.id},include:{items:{orderBy:{id:'asc'}}}}),audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:scope,entity:'TransportGuide',entityId:String(guide.id),metadata:{requestId:body.requestId,vehicleId:p.vehicleId,workGuideId:work.id,linkedProvisional:!!p.workGuideId,closeWorkGuideIds:plan.closeWorkGuideIds,closeTransportGuideIds:plan.closeTransportGuideIds,movementIds}}});
  return packet(a,body.requestId,await requests.confirm(tx,request,{vehicleId:p.vehicleId,guide,workGuide,movementIds,auditId:audit.id,closedWorkGuideIds:plan.closeWorkGuideIds,closedTransportGuideIds:plan.closeTransportGuideIds}));
 },{maxWait:15000,timeout:30000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('TRANSPORT_REQUEST_CONFLICT',409);if(e.code==='P2002')fail('TRANSPORT_CODE_EXISTS',409);throw e;}
}
async function cancel(a,id,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(id)||!R.keys(body,['vehicleId'])||!R.positive(body.vehicleId))fail('TRANSPORT_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${id}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId:id}}});if(saved){if(saved.scope!==scope)fail('TRANSPORT_REQUEST_CONFLICT',409);return packet(a,id,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:'TRANSPORT_CREATE_CANCELLED',entity:'FieldWriteRequest',entityId:id,metadata:body}});return packet(a,id,await requests.confirm(tx,{owner:subject,scope,requestId:id,resourceId:body.vehicleId,payloadHash:'cancelled'},{vehicleId:body.vehicleId,guide:null,cancelled:true,auditId:audit.id}));},{timeout:15000});}
module.exports={owner,list,review,commit,result,cancel,lockVehicle};
