'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-vehicle-consumption-rules');
const scope='VEHICLE_MANUAL_CONSUMPTION',audience='cristalwater-vehicle-consumption-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(actor){if(!['ADMIN','TECHNICIAN','TEAM_LEADER'].includes(actor?.role)||actor.principalType==='ENV_ADMIN'||actor.principalType==='USER'&&actor.role!=='ADMIN'&&!R.positive(actor.technicianId))fail('CONSUME_FORBIDDEN',403);return requests.owner(actor);}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('vehicle-consumption\0'+JSON.stringify(v)).digest('hex');
const workSelect={id:true,vehicleId:true,technicianId:true,guideId:true,status:true,isDraft:true,createdAt:true,updatedAt:true},vehicleSelect={id:true,plate:true,status:true,active:true,deletedAt:true,updatedAt:true},itemSelect={id:true,workGuideId:true,name:true,type:true,unit:true,quantity:true,usedQty:true,initialQty:true,updatedAt:true};
function noQuery(q){if(!R.keys(q,[]))fail('CONSUME_INVALID_REQUEST');}
async function permission(db,actor,lock=false){owner(actor);if(actor.role==='ADMIN')return null;const id=Number(actor.technicianId||actor.id);if(lock)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${id} FOR SHARE`;const tech=await db.technician.findUnique({where:{id},select:{id:true,vehicleId:true,active:true,deletedAt:true,authVersion:true}});if(!tech?.active||tech.deletedAt||!tech.vehicleId)fail('CONSUME_ASSIGNMENT_REQUIRED',403);return tech;}
async function selected(db,actor,p,lock=false){
 if(lock&&p.visitId)await db.$queryRaw`SELECT id FROM "ServiceVisit" WHERE id=${p.visitId} FOR SHARE`;
 if(lock)await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE id=${p.workGuideId} FOR UPDATE`;
 const permit=await permission(db,actor,lock),work=await db.workGuide.findUnique({where:{id:p.workGuideId},select:workSelect});
 if(!work||permit&&(work.vehicleId!==permit.vehicleId||work.technicianId!==permit.id))fail('CONSUME_NOT_FOUND',404);
 if(work.status!=='OPEN'||!work.vehicleId)fail('CONSUME_GUIDE_CHANGED',409);
 if(lock)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${work.vehicleId} FOR SHARE`;
 const vehicle=await db.vehicle.findUnique({where:{id:work.vehicleId},select:vehicleSelect});if(!vehicle?.active||vehicle.deletedAt)fail('CONSUME_VEHICLE_CHANGED',409);
 if(lock&&work.guideId)await db.$queryRaw`SELECT id FROM "TransportGuide" WHERE id=${work.guideId} FOR SHARE`;
 const transport=work.guideId?await db.transportGuide.findUnique({where:{id:work.guideId},select:{id:true,vehicleId:true,codeAT:true,status:true,isDraft:true,updatedAt:true}}):null;
 if(work.guideId&&(!transport||transport.vehicleId!==work.vehicleId||transport.status!=='ACTIVE'))fail('CONSUME_GUIDE_CHANGED',409);
 if(lock)await db.$queryRaw`SELECT id FROM "WorkGuideItem" WHERE id=${p.itemId} FOR UPDATE`;
 const item=await db.workGuideItem.findUnique({where:{id:p.itemId},select:itemSelect});if(!item||item.workGuideId!==work.id)fail('CONSUME_ITEM_CHANGED',409);
 if(!R.item({...item,updatedAt:item.updatedAt.toISOString()})||!item.name.trim()||!item.unit?.trim())fail('CONSUME_ITEM_REVIEW',409);
 if(!R.after(item,p.quantity))fail('CONSUME_BALANCE_REVIEW',409);
 const technician=work.technicianId?await db.technician.findUnique({where:{id:work.technicianId},select:{id:true,name:true}}):null;
 let visit=null;if(p.visitId){visit=await db.serviceVisit.findUnique({where:{id:p.visitId},select:{id:true,technicianId:true,poolId:true,clientId:true,status:true,updatedAt:true,pool:{select:{id:true,name:true,clientId:true}},client:{select:{id:true,name:true}}}});if(!visit||!work.technicianId||visit.technicianId!==work.technicianId||!visit.poolId||!visit.clientId||visit.pool?.clientId!==visit.clientId||visit.client?.id!==visit.clientId)fail('CONSUME_VISIT_REVIEW',409);}
 return {work,vehicle,transport,technician,item,visit,permission:permit};
}
async function list(actor,raw={},db=prisma){owner(actor);const q=R.query(raw);if(!q)fail('CONSUME_INVALID_QUERY');return db.$transaction(async tx=>{const permit=await permission(tx,actor),where={status:'OPEN',vehicle:{is:{active:true,deletedAt:null}},...(permit?{vehicleId:permit.vehicleId,technicianId:permit.id}:{}),...(q.workGuideId?{id:q.workGuideId}:{}),...(q.q?{OR:[{vehicle:{plate:{contains:q.q,mode:'insensitive'}}},{items:{some:{name:{contains:q.q,mode:'insensitive'}}}}]}:{})};const guides=await tx.workGuide.findMany({where,select:{...workSelect,vehicle:{select:vehicleSelect},technician:{select:{id:true,name:true}},guide:{select:{id:true,codeAT:true,status:true,isDraft:true}},items:{select:itemSelect,orderBy:{id:'asc'}}},orderBy:{id:'desc'},skip:(q.page-1)*25,take:25});return {...envelope(actor),page:q.page,size:25,total:await tx.workGuide.count({where}),guides};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);const p=R.input(body);if(!p)fail('CONSUME_INVALID_FIELDS');const choice=await db.$transaction(tx=>selected(tx,actor,p),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000}),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(choice)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});const {permission:_,...visible}=choice,n=R.quantity(p.quantity);return {...envelope(actor),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:visible,after:R.after(choice.item,p.quantity)};}
const packet=(actor,requestId,result)=>({...envelope(actor),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,requestId,q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId))fail('CONSUME_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(actor,requestId,saved?.scope===scope?saved.response:null);},{maxWait:15000,timeout:15000});}
async function commit(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('CONSUME_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('CONSUME_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('CONSUME_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('CONSUME_REVIEW_REQUIRED',409);
 const request=requests.context(actor,scope,p.workGuideId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(actor,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('CONSUME_REVIEW_EXPIRED',409);const choice=await selected(tx,actor,p,true);if(digest(choice)!==claims.choiceDigest)fail('CONSUME_CHANGED',409);const {item,work,visit}=choice,n=R.quantity(p.quantity),updated=await tx.workGuideItem.update({where:{id:item.id},data:{...R.after(item,p.quantity),updatedAt:new Date(Math.max(Date.now(),item.updatedAt.getTime()+1))},select:itemSelect});
  const notes=JSON.stringify({cwGuideMovement:true,userNotes:p.notes,location:p.location,poolId:visit?.poolId||null,poolName:visit?.pool?.name||'',clientId:visit?.clientId||null,clientName:visit?.client?.name||'',readings:null,manualReview:true,requestId:body.requestId,owner:subject});
  const common={vehicleId:work.vehicleId,transportGuideId:work.guideId,workGuideId:work.id,visitId:p.visitId,technicianId:work.technicianId,unit:item.unit,quantity:n,movementType:'CONSUMPTION',notes};
  const vehicleMovement=await tx.vehicleStockMovement.create({data:{...common,itemName:item.name,itemType:item.type,source:'MANUAL_REVIEW'}}),stockMovement=await tx.stockMovement.create({data:{...common,productName:item.name,category:item.type,scopeFrom:'VEHICLE',clientId:visit?.clientId||null,poolId:visit?.poolId||null,createdBy:subject}});
  const audit=await tx.userAuditLog.create({data:{userId:actor.role==='ADMIN'||actor.principalType==='USER'?Number(actor.userId||actor.id):null,actor:subject,action:scope,entity:'WorkGuideItem',entityId:String(item.id),metadata:{requestId:body.requestId,workGuideId:work.id,itemId:item.id,quantity:p.quantity,visitId:p.visitId,vehicleMovementId:vehicleMovement.id,stockMovementId:stockMovement.id}}});
  return packet(actor,body.requestId,await requests.confirm(tx,request,{workGuideId:work.id,itemId:item.id,quantity:p.quantity,item:updated,vehicleMovementId:vehicleMovement.id,stockMovementId:stockMovement.id,auditId:audit.id}));
 },{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('CONSUME_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(actor,requestId,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['workGuideId','itemId'])||!R.positive(body.workGuideId)||!R.positive(body.itemId))fail('CONSUME_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope)fail('CONSUME_REQUEST_CONFLICT',409);return packet(actor,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:actor.role==='ADMIN'||actor.principalType==='USER'?Number(actor.userId||actor.id):null,actor:subject,action:'VEHICLE_CONSUMPTION_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(actor,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.workGuideId,payloadHash:'cancelled'},{...body,item:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,commit,result,cancel};
