'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),sources=require('./expenseSourceService'),R=require('../../frontend/cw-vehicle-maintenance-rules');
const scope='VEHICLE_MAINTENANCE_REVIEW',audience='cristalwater-vehicle-maintenance-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(actor){if(!['ADMIN','TECHNICIAN','TEAM_LEADER'].includes(actor?.role)||actor.principalType==='ENV_ADMIN'||actor.principalType==='USER'&&actor.role!=='ADMIN'&&!R.positive(actor.technicianId))fail('MAINTENANCE_FORBIDDEN',403);return requests.owner(actor);}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('vehicle-maintenance\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
const recordSelect={id:true,vehicleId:true,type:true,title:true,status:true,dueDate:true,completedAt:true,km:true,cost:true,notes:true,createdAt:true,updatedAt:true},vehicleSelect={id:true,plate:true,active:true,deletedAt:true,currentKm:true,updatedAt:true},expenseSelect={id:true,version:true,sourceHash:true,cancelledAt:true,updatedAt:true};
function noQuery(q){if(!R.keys(q,[]))fail('MAINTENANCE_INVALID_REQUEST');}
async function permission(db,a,lock=false){owner(a);if(a.role==='ADMIN')return null;const id=Number(a.technicianId||a.id);if(lock)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${id} FOR SHARE`;const t=await db.technician.findUnique({where:{id},select:{id:true,vehicleId:true,active:true,deletedAt:true,authVersion:true}});if(!t?.active||t.deletedAt||!t.vehicleId)fail('MAINTENANCE_ASSIGNMENT_REQUIRED',403);return t;}
const visible=c=>{const{permission:_,...v}=c;return v;};
const withoutCost=r=>{if(!r)return r;const{cost:_,...safe}=r;return safe;};
function publicChoice(a,c){const value=visible(c);return a.role==='ADMIN'?value:{...value,financialAccess:false,record:withoutCost(value.record),expense:null,sourceHash:value.sourceHash?digest(value.sourceHash):null};}
function publicResult(a,r){if(!r||r.cancelled||a.role==='ADMIN')return r;const before=publicChoice(a,r.before);return {...r,record:withoutCost(r.record),before,plan:R.plan(before,r.proposal)};}
function checkFields(a,p){if(a.role!=='ADMIN'&&Object.hasOwn(p.changes,'cost')&&!(p.operation==='CREATE'&&p.changes.cost===null))fail('MAINTENANCE_FORBIDDEN',403);}
async function selected(db,a,p,lock=false){
 const initial=p.maintenanceId?await db.companyExpense.findUnique({where:{maintenanceId:p.maintenanceId},select:{id:true}}):null;
 if(lock&&p.maintenanceId){
  // The expense ledger locks expense -> source. Never invert that order.
  if(initial)await db.$queryRaw`SELECT id FROM "CompanyExpense" WHERE id=${initial.id} FOR SHARE`;
  await db.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${ 'expense-source:VEHICLE_MAINTENANCE:'+p.maintenanceId }))::text`;
  await db.$queryRaw`SELECT id FROM "VehicleMaintenanceRecord" WHERE id=${p.maintenanceId} FOR UPDATE`;
 }
 const permit=await permission(db,a,lock),record=p.maintenanceId?await db.vehicleMaintenanceRecord.findUnique({where:{id:p.maintenanceId},select:recordSelect}):null;
 if(p.maintenanceId&&!record||record&&record.vehicleId!==p.vehicleId||permit&&p.vehicleId!==permit.vehicleId)fail('MAINTENANCE_NOT_FOUND',404);
 if(lock&&p.vehicleId)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${p.vehicleId} FOR SHARE`;
 const vehicle=p.vehicleId?await db.vehicle.findUnique({where:{id:p.vehicleId},select:vehicleSelect}):null;
 if(permit&&(!vehicle?.active||vehicle.deletedAt))fail('MAINTENANCE_ASSIGNMENT_REQUIRED',403);
 const expense=p.maintenanceId?await db.companyExpense.findUnique({where:{maintenanceId:p.maintenanceId},select:expenseSelect}):null;
 if(lock&&expense?.id!==initial?.id)fail('MAINTENANCE_CHANGED',409);
 const source=record?await sources.source(db,'VEHICLE_MAINTENANCE',record.id):null,c=json({record,vehicle,expense,sourceHash:source?.hash||null,permission:permit});
 if(!R.plan(c,p))fail('MAINTENANCE_REVIEW_REQUIRED',409);return c;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('MAINTENANCE_INVALID_QUERY');return db.$transaction(async tx=>{const permit=await permission(tx,a);if(permit&&q.vehicleId&&q.vehicleId!==permit.vehicleId)fail('MAINTENANCE_NOT_FOUND',404);const vehicleId=permit?.vehicleId||q.vehicleId;let rows,total;
 if(q.kind==='vehicles'){const where={active:true,deletedAt:null,...(vehicleId?{id:vehicleId}:{}),...(q.q?{plate:{contains:q.q,mode:'insensitive'}}:{})};total=await tx.vehicle.count({where});rows=(await tx.vehicle.findMany({where,select:vehicleSelect,orderBy:{id:'desc'},skip:(q.page-1)*25,take:25})).map(vehicle=>({vehicle,record:null,expense:null,sourceHash:null}));}
 else{if(permit){const vehicle=await tx.vehicle.findUnique({where:{id:permit.vehicleId},select:vehicleSelect});if(!vehicle?.active||vehicle.deletedAt)fail('MAINTENANCE_ASSIGNMENT_REQUIRED',403);}const where={...(vehicleId?{vehicleId}:{}),...(q.maintenanceId?{id:q.maintenanceId}:{}),...(q.q?{title:{contains:q.q,mode:'insensitive'}}:{})};total=await tx.vehicleMaintenanceRecord.count({where});const records=await tx.vehicleMaintenanceRecord.findMany({where,select:recordSelect,orderBy:{id:'desc'},skip:(q.page-1)*25,take:25});rows=await Promise.all(records.map(async record=>({record,vehicle:record.vehicleId?await tx.vehicle.findUnique({where:{id:record.vehicleId},select:vehicleSelect}):null,expense:await tx.companyExpense.findUnique({where:{maintenanceId:record.id},select:expenseSelect}),sourceHash:(await sources.source(tx,'VEHICLE_MAINTENANCE',record.id)).hash})));}
 return {...envelope(a),kind:q.kind,page:q.page,size:25,total,rows:rows.map(c=>publicChoice(a,c))};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('MAINTENANCE_INVALID_FIELDS');checkFields(a,p);const c=await db.$transaction(tx=>selected(tx,a,p),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000}),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:publicChoice(a,c),plan:R.plan(publicChoice(a,c),p)};}
const packet=(a,requestId,result)=>({...envelope(a),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:publicResult(a,result)||null});
async function result(a,requestId,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId))fail('MAINTENANCE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const r=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(a,requestId,r?.scope===scope?r.response:null);},{maxWait:15000,timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('MAINTENANCE_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('MAINTENANCE_INVALID_FIELDS');checkFields(a,p);let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('MAINTENANCE_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('MAINTENANCE_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,p.maintenanceId||p.vehicleId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('MAINTENANCE_REVIEW_EXPIRED',409);const c=await selected(tx,a,p,true);if(digest(c)!==claims.choiceDigest)fail('MAINTENANCE_CHANGED',409);const plan=R.plan(c,p),now=new Date(),data={...plan.after,completedAt:p.operation==='COMPLETE'?now:plan.after.completedAt};
 const record=p.operation==='CREATE'?await tx.vehicleMaintenanceRecord.create({data:{...data,vehicleId:p.vehicleId},select:recordSelect}):await tx.vehicleMaintenanceRecord.update({where:{id:p.maintenanceId},data:{...data,updatedAt:new Date(Math.max(Date.now(),Date.parse(c.record.updatedAt)+1))},select:recordSelect});
 const audit=await tx.userAuditLog.create({data:{userId:a.role==='ADMIN'||a.principalType==='USER'?Number(a.userId||a.id):null,actor:subject,action:scope,entity:'VehicleMaintenanceRecord',entityId:String(record.id),metadata:{requestId:body.requestId,operation:p.operation,reason:p.reason,before:visible(c),plan,record:json(record)}}});
 return packet(a,body.requestId,await requests.confirm(tx,request,{operation:p.operation,maintenanceId:p.maintenanceId,vehicleId:p.vehicleId,record,proposal:p,before:visible(c),plan,appliedAt:now.toISOString(),auditId:audit.id}));},{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('MAINTENANCE_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(a,requestId,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['operation','maintenanceId','vehicleId'])||!R.pending(JSON.stringify({version:1,owner:subject,requestId,...body}),subject))fail('MAINTENANCE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==(body.maintenanceId||body.vehicleId))fail('MAINTENANCE_REQUEST_CONFLICT',409);return packet(a,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:a.role==='ADMIN'||a.principalType==='USER'?Number(a.userId||a.id):null,actor:subject,action:'VEHICLE_MAINTENANCE_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(a,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.maintenanceId||body.vehicleId,payloadHash:'cancelled'},{...body,record:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,commit,result,cancel};
