'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-vehicle-assignment-rules');
const scope='VEHICLE_ASSIGNMENT_REVIEW',audience='cristalwater-vehicle-assignment-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){const id=Number(a?.userId||a?.id);if(a?.role!=='ADMIN'||a.principalType==='ENV_ADMIN'||!R.positive(id))fail('ASSIGNMENT_FORBIDDEN',403);return 'ADMIN:'+id;}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('vehicle-assignment\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
const technicianSelect={id:true,name:true,vehicleId:true,active:true,deletedAt:true,updatedAt:true},vehicleSelect={id:true,plate:true,active:true,deletedAt:true,currentKm:true,updatedAt:true},workSelect={id:true,technicianId:true,vehicleId:true,status:true,updatedAt:true};
function noQuery(q){if(!R.keys(q,[]))fail('ASSIGNMENT_INVALID_REQUEST');}
async function selected(db,p,lock=false){
 const initial=await db.technician.findUnique({where:{id:p.technicianId},select:technicianSelect});if(!initial)fail('ASSIGNMENT_NOT_FOUND',404);
 const vehicleIds=[...new Set([initial.vehicleId,p.vehicleId].filter(Boolean))].sort((a,b)=>a-b);
 if(lock){
  // Match guide creation/closing: vehicle advisory -> work -> technician -> vehicle.
  for(const id of vehicleIds)await db.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${ 'guide-vehicle:'+id }))::text`;
  await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE "technicianId"=${p.technicianId} AND status='OPEN' ORDER BY id FOR UPDATE`;
  await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${p.technicianId} FOR UPDATE`;
 }
 const technician=await db.technician.findUnique({where:{id:p.technicianId},select:technicianSelect});if(!technician||technician.vehicleId!==initial.vehicleId)fail('ASSIGNMENT_CHANGED',409);
 if(await db.workGuide.count({where:{technicianId:p.technicianId,status:'OPEN'}}))fail('ASSIGNMENT_OPEN_WORK',409);
 if(lock)for(const id of vehicleIds)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${id} FOR UPDATE`;
 const currentVehicle=technician.vehicleId?await db.vehicle.findUnique({where:{id:technician.vehicleId},select:vehicleSelect}):null,targetVehicle=p.vehicleId?await db.vehicle.findUnique({where:{id:p.vehicleId},select:vehicleSelect}):null;
 if(lock)await db.$queryRaw`SELECT id FROM "TechnicianVehicleLog" WHERE "technicianId"=${p.technicianId} AND "endAt" IS NULL ORDER BY id FOR UPDATE`;
 const logs=await db.technicianVehicleLog.findMany({where:{technicianId:p.technicianId,endAt:null},orderBy:{id:'asc'},take:2}),latest=await db.technicianVehicleLog.findFirst({where:{technicianId:p.technicianId,endAt:{not:null}},orderBy:[{endAt:'desc'},{id:'desc'}],select:{endAt:true}}),openLog=logs[0]||null;
 if(logs.length>1||openLog&&(openLog.vehicleId!==technician.vehicleId||openLog.startAt.getTime()>Date.now()||latest&&latest.endAt>openLog.startAt)||latest&&latest.endAt.getTime()>Date.now())fail('ASSIGNMENT_HISTORY_REVIEW',409);
 const targetWork=p.vehicleId?await db.workGuide.findMany({where:{vehicleId:p.vehicleId,status:'OPEN'},select:workSelect,orderBy:{id:'asc'},take:101}):[];
 const c=json({technician,currentVehicle,targetVehicle,openLog,latestEndAt:latest?.endAt||null,targetWork});
 if(!R.plan(c,p))fail('ASSIGNMENT_REVIEW_REQUIRED',409);return c;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('ASSIGNMENT_INVALID_QUERY');return db.$transaction(async tx=>{
 let rows,total;if(q.kind==='vehicles'){const where={active:true,deletedAt:null,...(q.q?{plate:{contains:q.q,mode:'insensitive'}}:{})};total=await tx.vehicle.count({where});rows=await tx.vehicle.findMany({where,select:vehicleSelect,orderBy:[{plate:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25});}
 else{const where={...(q.technicianId?{id:q.technicianId}:{}),...(q.q?{name:{contains:q.q,mode:'insensitive'}}:{})};total=await tx.technician.count({where});const technicians=await tx.technician.findMany({where,select:technicianSelect,orderBy:[{name:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25});rows=await Promise.all(technicians.map(async technician=>({technician,vehicle:technician.vehicleId?await tx.vehicle.findUnique({where:{id:technician.vehicleId},select:vehicleSelect}):null,openWorkCount:await tx.workGuide.count({where:{technicianId:technician.id,status:'OPEN'}}),firstOpenWorkId:(await tx.workGuide.findFirst({where:{technicianId:technician.id,status:'OPEN'},select:{id:true},orderBy:{id:'asc'}}))?.id||null})));}
 return {...envelope(a),kind:q.kind,page:q.page,size:25,total,rows};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('ASSIGNMENT_INVALID_FIELDS');const c=await db.$transaction(tx=>selected(tx,p),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000}),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:c,plan:R.plan(c,p)};}
const packet=(a,requestId,result)=>({...envelope(a),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(a,requestId,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId))fail('ASSIGNMENT_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const r=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(a,requestId,r?.scope===scope?r.response:null);},{maxWait:15000,timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('ASSIGNMENT_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('ASSIGNMENT_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('ASSIGNMENT_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('ASSIGNMENT_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,p.technicianId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('ASSIGNMENT_REVIEW_EXPIRED',409);const c=await selected(tx,p,true);if(digest(c)!==claims.choiceDigest)fail('ASSIGNMENT_CHANGED',409);const plan=R.plan(c,p),now=new Date();
 const closedLog=c.openLog?await tx.technicianVehicleLog.update({where:{id:c.openLog.id},data:{endAt:now}}):null;
 const technician=await tx.technician.update({where:{id:p.technicianId},data:{vehicleId:p.vehicleId,updatedAt:new Date(Math.max(now.getTime(),Date.parse(c.technician.updatedAt)+1))},select:technicianSelect});
 const openedLog=p.vehicleId?await tx.technicianVehicleLog.create({data:{technicianId:p.technicianId,vehicleId:p.vehicleId,startAt:now}}):null;
 const vehicle=plan.updateKm?await tx.vehicle.update({where:{id:p.vehicleId},data:{currentKm:plan.kmAfter,updatedAt:new Date(Math.max(now.getTime(),Date.parse(c.targetVehicle.updatedAt)+1))},select:vehicleSelect}):c.targetVehicle;
 const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:scope,entity:'Technician',entityId:String(p.technicianId),metadata:{requestId:body.requestId,reason:p.reason,before:c,plan,closedLog:json(closedLog),openedLog:json(openedLog)}}});
 return packet(a,body.requestId,await requests.confirm(tx,request,{technicianId:p.technicianId,vehicleId:p.vehicleId,technician,vehicle,closedLog,openedLog,proposal:p,before:c,plan,appliedAt:now.toISOString(),auditId:audit.id}));},{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('ASSIGNMENT_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(a,requestId,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['technicianId','vehicleId'])||!R.pending(JSON.stringify({version:1,owner:subject,requestId,...body}),subject))fail('ASSIGNMENT_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==body.technicianId)fail('ASSIGNMENT_REQUEST_CONFLICT',409);return packet(a,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:'VEHICLE_ASSIGNMENT_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(a,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.technicianId,payloadHash:'cancelled'},{...body,technician:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,commit,result,cancel};
