'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-vehicle-stock-preset-rules');
const scope='VEHICLE_STOCK_PRESET_REVIEW',audience='cristalwater-vehicle-stock-preset-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){const id=Number(a?.userId||a?.id);if(a?.role!=='ADMIN'||a.principalType==='ENV_ADMIN'||!R.positive(id))fail('PRESET_FORBIDDEN',403);return 'ADMIN:'+id;}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('vehicle-stock-preset\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
const vehicleSelect={id:true,plate:true,active:true,deletedAt:true,updatedAt:true},relatedSelect={id:true,vehicleId:true,status:true,updatedAt:true};
function noQuery(q){if(!R.keys(q,[]))fail('PRESET_INVALID_REQUEST');}
async function selected(db,vehicleId,lock=false){
 const key='vehicle_preset_'+vehicleId;
 if(lock){await require('./transportGuideCreationService').lockVehicle(db,vehicleId);await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE "vehicleId"=${vehicleId} AND status='OPEN' ORDER BY id FOR SHARE`;await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${vehicleId} FOR SHARE`;await db.$queryRaw`SELECT id FROM "TransportGuide" WHERE "vehicleId"=${vehicleId} AND (status='ACTIVE' OR id=(SELECT id FROM "TransportGuide" WHERE "vehicleId"=${vehicleId} ORDER BY "createdAt" DESC,id DESC LIMIT 1)) ORDER BY id FOR SHARE`;await db.$queryRaw`SELECT id FROM "SystemSetting" WHERE key=${key} FOR UPDATE`;}
 const vehicle=await db.vehicle.findUnique({where:{id:vehicleId},select:vehicleSelect});if(!vehicle)fail('PRESET_NOT_FOUND',404);
 const record=await db.systemSetting.findUnique({where:{key}}),openWorks=await db.workGuide.findMany({where:{vehicleId,status:'OPEN'},select:{...relatedSelect,guideId:true},orderBy:{id:'asc'},take:101}),activeGuides=await db.transportGuide.findMany({where:{vehicleId,status:'ACTIVE'},select:relatedSelect,orderBy:{id:'asc'},take:101}),lastGuide=await db.transportGuide.findFirst({where:{vehicleId},select:relatedSelect,orderBy:[{createdAt:'desc'},{id:'desc'}]});
 const c=json({vehicle,record,openWorks,activeGuides,lastGuide});if(!R.choice(c))fail('PRESET_VOLUME_REVIEW',409);return c;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('PRESET_INVALID_QUERY');return db.$transaction(async tx=>{const where={active:true,deletedAt:null,...(q.vehicleId?{id:q.vehicleId}:{}),...(q.q?{plate:{contains:q.q,mode:'insensitive'}}:{})},total=await tx.vehicle.count({where}),vehicles=await tx.vehicle.findMany({where,select:vehicleSelect,orderBy:[{plate:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25}),rows=[];for(const vehicle of vehicles){const record=await tx.systemSetting.findUnique({where:{key:'vehicle_preset_'+vehicle.id},select:{value:true}}),parsed=R.parse(record?.value??null);rows.push({vehicle,state:parsed.state,count:parsed.items?.length??null});}return {...envelope(a),page:q.page,size:25,total,rows};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function detail(a,id,q={},db=prisma){owner(a);noQuery(q);const vehicleId=R.id(id);if(!vehicleId)fail('PRESET_INVALID_REQUEST');return db.$transaction(async tx=>({...envelope(a),choice:await selected(tx,vehicleId)}),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('PRESET_INVALID_FIELDS');const c=await db.$transaction(tx=>selected(tx,p.vehicleId),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});if(!R.plan(c,p))fail('PRESET_REVIEW_REQUIRED',409);const requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:c,plan:R.plan(c,p)};}
const packet=(a,requestId,result)=>({...envelope(a),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(a,requestId,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId))fail('PRESET_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const r=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(a,requestId,r?.scope===scope?r.response:null);},{maxWait:15000,timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('PRESET_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('PRESET_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('PRESET_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('PRESET_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,p.vehicleId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('PRESET_REVIEW_EXPIRED',409);const c=await selected(tx,p.vehicleId,true);if(digest(c)!==claims.choiceDigest)fail('PRESET_CHANGED',409);const plan=R.plan(c,p);if(!plan)fail('PRESET_REVIEW_REQUIRED',409);
 const record=c.record?await tx.systemSetting.update({where:{id:c.record.id},data:{value:plan.afterValue,updatedAt:new Date(Math.max(Date.now(),Date.parse(c.record.updatedAt)+1))}}):await tx.systemSetting.create({data:{key:'vehicle_preset_'+p.vehicleId,value:plan.afterValue,notes:null}});
 const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:scope,entity:'Vehicle',entityId:String(p.vehicleId),metadata:{requestId:body.requestId,reason:p.reason,before:c,plan,after:json(record)}}});
 return packet(a,body.requestId,await requests.confirm(tx,request,{vehicleId:p.vehicleId,record,proposal:p,before:c,plan,auditId:audit.id}));},{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('PRESET_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(a,requestId,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['vehicleId'])||!R.pending(JSON.stringify({version:1,owner:subject,requestId,...body}),subject))fail('PRESET_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==body.vehicleId)fail('PRESET_REQUEST_CONFLICT',409);return packet(a,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:Number(a.userId||a.id),actor:subject,action:'VEHICLE_STOCK_PRESET_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(a,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.vehicleId,payloadHash:'cancelled'},{...body,record:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,detail,review,commit,result,cancel};
