'use strict';
// Only application-owned labels and messages belong here; never translate stored free text.
const messages = {
  "Documento gerado pelo sistema Cristal Water. Os dados históricos da instalação correspondem à revisão identificada.": {
    "en": "Document generated by Cristal Water. Historical installation details correspond to the identified review.",
    "fr": "Document généré par Cristal Water. Les données historiques de l’installation correspondent à la vérification indiquée.",
    "es": "Documento generado por Cristal Water. Los datos históricos de la instalación corresponden a la revisión indicada.",
    "de": "Dokument von Cristal Water erstellt. Die historischen Anlagendaten entsprechen der angegebenen Prüfung."
  },
  "Origem histórica revista": {
    "en": "Historical origin reviewed",
    "fr": "Origine historique vérifiée",
    "es": "Origen histórico revisado",
    "de": "Historischer Ursprung geprüft"
  },
  "Os dados da instalação foram confirmados para esta visita. Os dados atuais do equipamento e da casa técnica não estão incluídos.": {
    "en": "The installation details were confirmed for this visit. Current equipment and technical room details are not included.",
    "fr": "Les données de l’installation ont été confirmées pour cette visite. Les données actuelles de l’équipement et du local technique ne sont pas incluses.",
    "es": "Los datos de la instalación se confirmaron para esta visita. No se incluyen los datos actuales del equipo y del cuarto técnico.",
    "de": "Die Anlagendaten wurden für diesen Besuch bestätigt. Aktuelle Angaben zu Ausstattung und Technikraum sind nicht enthalten."
  },
  "Revisão registada:": {
    "en": "Review recorded:",
    "fr": "Vérification enregistrée :",
    "es": "Revisión registrada:",
    "de": "Prüfung erfasst:"
  },
  "Evidência da revisão administrativa": {
    "en": "Administrative review evidence",
    "fr": "Éléments de la vérification administrative",
    "es": "Evidencia de la revisión administrativa",
    "de": "Nachweis der Verwaltungsprüfung"
  },
  "Motivo:": {
    "en": "Reason:",
    "fr": "Motif :",
    "es": "Motivo:",
    "de": "Grund:"
  },
  "Dados da instalação: revisão histórica identificada": {"en":"Installation details: identified historical review","fr":"Installation : vérification historique indiquée","es":"Instalación: revisión histórica identificada", "de": "Anlagendaten: angegebene historische Prüfung"},
  "Revisão administrativa da visita": {"en": "Administrative visit review", "fr": "Examen administratif de la visite", "es": "Revisión administrativa de la visita", "de": "Verwaltungsprüfung des Besuchs"},
  "Origem por rever": {"en": "Origin requires review", "fr": "Origine à vérifier", "es": "Origen pendiente de revisión", "de": "Ursprung zu prüfen"},
  "O cliente registado na visita difere do cliente atual da instalação. Esta consulta não confirma a titularidade histórica nem autoriza a partilha com clientes. Os dados atuais da instalação foram omitidos.": {"en": "The client recorded on the visit differs from the current facility client. This review does not confirm historical ownership or authorize sharing with clients. Current facility data has been omitted.", "fr": "Le client enregistré pour la visite diffère du client actuel de l’installation. Cet examen ne confirme pas la titularité historique et n’autorise pas le partage avec les clients. Les données actuelles de l’installation ont été omises.", "es": "El cliente registrado en la visita difiere del cliente actual de la instalación. Esta consulta no confirma la titularidad histórica ni autoriza compartirla con clientes. Se han omitido los datos actuales de la instalación.", "de": "Der beim Besuch erfasste Kunde weicht vom aktuellen Kunden der Anlage ab. Diese Prüfung bestätigt weder die historische Zuordnung noch erlaubt sie die Weitergabe an Kunden. Aktuelle Anlagendaten wurden ausgelassen."},
  "Cliente registado na visita (ID)": {"en": "Client recorded on the visit (ID)", "fr": "Client enregistré pour la visite (ID)", "es": "Cliente registrado en la visita (ID)", "de": "Beim Besuch erfasster Kunde (ID)"},
  "Nome na ficha atual desse cliente": {"en": "Name on that client’s current record", "fr": "Nom dans la fiche actuelle de ce client", "es": "Nombre en la ficha actual de ese cliente", "de": "Name im aktuellen Datensatz dieses Kunden"},
  "Instalação registada na visita (ID)": {"en": "Facility recorded on the visit (ID)", "fr": "Installation enregistrée pour la visite (ID)", "es": "Instalación registrada en la visita (ID)", "de": "Beim Besuch erfasste Anlage (ID)"},
  "Revisão administrativa: registo da visita": {"en": "Administrative review: visit record", "fr": "Examen administratif : fiche de visite", "es": "Revisión administrativa: registro de la visita", "de": "Verwaltungsprüfung: Besuchsdatensatz"},
  "Relatório técnico completo": {
    "en": "Full technical report",
    "fr": "Rapport technique complet",
    "es": "Informe técnico completo",
    "de": "Vollständiger technischer Bericht"
  },
  "Relatório de manutenção": {
    "en": "Maintenance report",
    "fr": "Rapport d’entretien",
    "es": "Informe de mantenimiento",
    "de": "Wartungsbericht"
  },
  "Visita extra #": {
    "en": "Extra visit #",
    "fr": "Visite supplémentaire n°",
    "es": "Visita extra n.º",
    "de": "Zusätzlicher Besuch Nr. "
  },
  "Visita #": {
    "en": "Visit #",
    "fr": "Visite n°",
    "es": "Visita n.º",
    "de": "Besuch Nr. "
  },
  "Sim": {
    "en": "Yes",
    "fr": "Oui",
    "es": "Sí",
    "de": "Ja"
  },
  "Não": {
    "en": "No",
    "fr": "Non",
    "es": "No",
    "de": "Nein"
  },
  "Não registado": {
    "en": "Not recorded",
    "fr": "Non enregistré",
    "es": "No registrado",
    "de": "Nicht erfasst"
  },
  "Por confirmar": {
    "en": "To be confirmed",
    "fr": "À confirmer",
    "es": "Por confirmar",
    "de": "Zu bestätigen"
  },
  "Cliente": {
    "en": "Client",
    "fr": "Client",
    "es": "Cliente",
    "de": "Kunde"
  },
  "Instalação": {
    "en": "Facility",
    "fr": "Installation",
    "es": "Instalación",
    "de": "Anlage"
  },
  "Zona": {
    "en": "Area",
    "fr": "Zone",
    "es": "Zona",
    "de": "Bereich"
  },
  "Morada": {
    "en": "Address",
    "fr": "Adresse",
    "es": "Dirección",
    "de": "Adresse"
  },
  "Técnico atribuído (registo atual)": {
    "en": "Assigned technician (current record)",
    "fr": "Technicien affecté (fiche actuelle)",
    "es": "Técnico asignado (registro actual)",
    "de": "Zugewiesener Techniker (aktueller Datensatz)"
  },
  "Técnico": {
    "en": "Technician",
    "fr": "Technicien",
    "es": "Técnico",
    "de": "Techniker"
  },
  "Estado": {
    "en": "Status",
    "fr": "État",
    "es": "Estado",
    "de": "Status"
  },
  "Planeada (hora de Portugal)": {
    "en": "Planned (Portugal time)",
    "fr": "Prévue (heure du Portugal)",
    "es": "Prevista (hora de Portugal)",
    "de": "Geplant (Ortszeit Portugal)"
  },
  "Início (hora de Portugal)": {
    "en": "Start (Portugal time)",
    "fr": "Début (heure du Portugal)",
    "es": "Inicio (hora de Portugal)",
    "de": "Beginn (Ortszeit Portugal)"
  },
  "Fim (hora de Portugal)": {
    "en": "End (Portugal time)",
    "fr": "Fin (heure du Portugal)",
    "es": "Fin (hora de Portugal)",
    "de": "Ende (Ortszeit Portugal)"
  },
  "Dados da visita extra": {
    "en": "Extra visit details",
    "fr": "Détails de la visite supplémentaire",
    "es": "Datos de la visita extra",
    "de": "Angaben zum zusätzlichen Besuch"
  },
  "Dados da visita": {
    "en": "Visit details",
    "fr": "Détails de la visite",
    "es": "Datos de la visita",
    "de": "Besuchsangaben"
  },
  "Parâmetros da água": {
    "en": "Water readings",
    "fr": "Paramètres de l’eau",
    "es": "Parámetros del agua",
    "de": "Wasserwerte"
  },
  "Cloro": {
    "en": "Chlorine",
    "fr": "Chlore",
    "es": "Cloro",
    "de": "Chlor"
  },
  "Alcalinidade": {
    "en": "Alkalinity",
    "fr": "Alcalinité",
    "es": "Alcalinidad",
    "de": "Alkalinität"
  },
  "Sal": {
    "en": "Salt",
    "fr": "Sel",
    "es": "Sal",
    "de": "Salz"
  },
  "Temperatura": {
    "en": "Temperature",
    "fr": "Température",
    "es": "Temperatura",
    "de": "Temperatur"
  },
  "Trabalhos registados": {
    "en": "Recorded work",
    "fr": "Travaux enregistrés",
    "es": "Trabajos registrados",
    "de": "Erfasste Arbeiten"
  },
  "Limpeza geral": {
    "en": "General cleaning",
    "fr": "Nettoyage général",
    "es": "Limpieza general",
    "de": "Allgemeine Reinigung"
  },
  "Escovagem": {
    "en": "Brushing",
    "fr": "Brossage",
    "es": "Cepillado",
    "de": "Bürsten"
  },
  "Aspiração": {
    "en": "Vacuuming",
    "fr": "Aspiration",
    "es": "Aspiración",
    "de": "Absaugen"
  },
  "Cestos limpos": {
    "en": "Baskets cleaned",
    "fr": "Paniers nettoyés",
    "es": "Cestos limpios",
    "de": "Körbe gereinigt"
  },
  "Linha de água limpa": {
    "en": "Waterline cleaned",
    "fr": "Ligne d’eau nettoyée",
    "es": "Línea de agua limpia",
    "de": "Wasserlinie gereinigt"
  },
  "Retrolavagem": {
    "en": "Backwash",
    "fr": "Contre-lavage",
    "es": "Contralavado",
    "de": "Rückspülung"
  },
  "Químicos aplicados": {
    "en": "Chemicals applied",
    "fr": "Produits appliqués",
    "es": "Productos aplicados",
    "de": "Verwendete Chemikalien"
  },
  "Nenhum químico registado.": {
    "en": "No chemicals recorded.",
    "fr": "Aucun produit enregistré.",
    "es": "Ningún producto registrado.",
    "de": "Keine Chemikalien erfasst."
  },
  "Equipamento atual da instalação": {
    "en": "Current facility equipment",
    "fr": "Équipements actuels de l’installation",
    "es": "Equipamiento actual de la instalación",
    "de": "Aktuelle Ausstattung der Anlage"
  },
  "Bomba": {
    "en": "Pump",
    "fr": "Pompe",
    "es": "Bomba",
    "de": "Pumpe"
  },
  "Potência da bomba": {
    "en": "Pump power",
    "fr": "Puissance de la pompe",
    "es": "Potencia de la bomba",
    "de": "Pumpenleistung"
  },
  "Filtro": {
    "en": "Filter",
    "fr": "Filtre",
    "es": "Filtro",
    "de": "Filter"
  },
  "Meio filtrante": {
    "en": "Filter media",
    "fr": "Média filtrant",
    "es": "Medio filtrante",
    "de": "Filtermedium"
  },
  "Sistema de sal": {
    "en": "Salt system",
    "fr": "Système au sel",
    "es": "Sistema salino",
    "de": "Salzsystem"
  },
  "Quantidade de sal": {
    "en": "Salt quantity",
    "fr": "Quantité de sel",
    "es": "Cantidad de sal",
    "de": "Salzmenge"
  },
  "Luzes": {
    "en": "Lights",
    "fr": "Éclairages",
    "es": "Luces",
    "de": "Leuchten"
  },
  "Luzes avariadas": {
    "en": "Faulty lights",
    "fr": "Éclairages en panne",
    "es": "Luces averiadas",
    "de": "Defekte Leuchten"
  },
  "Tipo de luz": {
    "en": "Light type",
    "fr": "Type d’éclairage",
    "es": "Tipo de luz",
    "de": "Leuchtentyp"
  },
  "Casa técnica - registo atual": {
    "en": "Plant room - current record",
    "fr": "Local technique - fiche actuelle",
    "es": "Sala técnica - registro actual",
    "de": "Technikraum - aktueller Datensatz"
  },
  "Localização": {
    "en": "Location",
    "fr": "Emplacement",
    "es": "Ubicación",
    "de": "Standort"
  },
  "Ventilação": {
    "en": "Ventilation",
    "fr": "Ventilation",
    "es": "Ventilación",
    "de": "Belüftung"
  },
  "Elétrica": {
    "en": "Electrical",
    "fr": "Électricité",
    "es": "Electricidad",
    "de": "Elektrik"
  },
  "Notas": {
    "en": "Notes",
    "fr": "Notes",
    "es": "Notas",
    "de": "Notizen"
  },
  "Observações": {
    "en": "Observations",
    "fr": "Observations",
    "es": "Observaciones",
    "de": "Bemerkungen"
  },
  "Sem observações.": {
    "en": "No observations.",
    "fr": "Aucune observation.",
    "es": "Sin observaciones.",
    "de": "Keine Bemerkungen."
  },
  "Indicações de planeamento": {
    "en": "Planning instructions",
    "fr": "Consignes de planification",
    "es": "Indicaciones de planificación",
    "de": "Planungshinweise"
  },
  "Ocorrência registada": {
    "en": "Recorded issue",
    "fr": "Incident enregistré",
    "es": "Incidencia registrada",
    "de": "Erfasster Vorfall"
  },
  "Notas internas": {
    "en": "Internal notes",
    "fr": "Notes internes",
    "es": "Notas internas",
    "de": "Interne Notizen"
  },
  "Sem notas internas.": {
    "en": "No internal notes.",
    "fr": "Aucune note interne.",
    "es": "Sin notas internas.",
    "de": "Keine internen Notizen."
  },
  "Fotografias da visita": {
    "en": "Visit photographs",
    "fr": "Photos de la visite",
    "es": "Fotografías de la visita",
    "de": "Besuchsfotos"
  },
  "Nenhuma foto registada.": {
    "en": "No photographs recorded.",
    "fr": "Aucune photo enregistrée.",
    "es": "Ninguna fotografía registrada.",
    "de": "Keine Fotos erfasst."
  },
  "Imprimir / Guardar PDF": {
    "en": "Print / Save PDF",
    "fr": "Imprimer / Enregistrer le PDF",
    "es": "Imprimir / Guardar PDF",
    "de": "Drucken / PDF speichern"
  },
  "Documento gerado pelo sistema Cristal Water. Os dados da instalação correspondem ao registo atual.": {
    "en": "Document generated by Cristal Water. Facility details reflect the current record.",
    "fr": "Document généré par Cristal Water. Les données de l’installation correspondent à la fiche actuelle.",
    "es": "Documento generado por Cristal Water. Los datos de la instalación corresponden al registro actual.",
    "de": "Dokument von Cristal Water erstellt. Die Anlagendaten entsprechen dem aktuellen Datensatz."
  },
  "Caracteres por confirmar": {
    "en": "Characters to confirm",
    "fr": "Caractères à confirmer",
    "es": "Caracteres por confirmar",
    "de": "Zeichen zu bestätigen"
  },
  "Alguns caracteres não são suportados por este PDF e aparecem como [U+...]. Consulte o registo original para confirmar o texto.": {
    "en": "Some characters are not supported by this PDF and appear as [U+...]. Check the original record to confirm the text.",
    "fr": "Certains caractères ne sont pas pris en charge dans ce PDF et apparaissent sous la forme [U+...]. Consultez le document original pour vérifier le texte.",
    "es": "Algunos caracteres no son compatibles con este PDF y aparecen como [U+...]. Consulte el registro original para confirmar el texto.",
    "de": "Einige Zeichen werden in diesem PDF nicht unterstützt und als [U+...] angezeigt. Prüfen Sie den Originaldatensatz, um den Text zu bestätigen."
  },
  "Dados da instalação: registo atual": {
    "en": "Facility details: current record",
    "fr": "Données de l’installation : fiche actuelle",
    "es": "Datos de la instalación: registro actual",
    "de": "Anlagendaten: aktueller Datensatz"
  },
  "Consumo não registado.": {
    "en": "Consumption not recorded.",
    "fr": "Consommation non enregistrée.",
    "es": "Consumo no registrado.",
    "de": "Verbrauch nicht erfasst."
  },
  "Consumo por confirmar. Peça a revisão do registo.": {
    "en": "Consumption to be confirmed. Ask for the record to be reviewed.",
    "fr": "Consommation à confirmer. Demandez une vérification de la fiche.",
    "es": "Consumo por confirmar. Solicite la revisión del registro.",
    "de": "Verbrauch zu bestätigen. Bitten Sie um Prüfung des Datensatzes."
  },
  "Sem observações registadas.": {
    "en": "No observations recorded.",
    "fr": "Aucune observation enregistrée.",
    "es": "Sin observaciones registradas.",
    "de": "Keine Bemerkungen erfasst."
  },
  "Observações de execução não registadas.": {
    "en": "Work observations not recorded.",
    "fr": "Observations des travaux non enregistrées.",
    "es": "Observaciones de ejecución no registradas.",
    "de": "Bemerkungen zur Ausführung nicht erfasst."
  },
  "Observações de execução por confirmar.": {
    "en": "Work observations to be confirmed.",
    "fr": "Observations des travaux à confirmer.",
    "es": "Observaciones de ejecución por confirmar.",
    "de": "Bemerkungen zur Ausführung zu bestätigen."
  },
  "Antes": {
    "en": "Before",
    "fr": "Avant",
    "es": "Antes",
    "de": "Vorher"
  },
  "Depois": {
    "en": "After",
    "fr": "Après",
    "es": "Después",
    "de": "Nachher"
  },
  "Problema": {
    "en": "Problem",
    "fr": "Problème",
    "es": "Problema",
    "de": "Problem"
  },
  "Acesso": {
    "en": "Access",
    "fr": "Accès",
    "es": "Acceso",
    "de": "Zugang"
  },
  "Geral": {
    "en": "General",
    "fr": "Général",
    "es": "General",
    "de": "Allgemein"
  },
  "Registo": {
    "en": "Record",
    "fr": "Enregistrement",
    "es": "Registro",
    "de": "Datensatz"
  },
  "Fotografia": {
    "en": "Photograph",
    "fr": "Photo",
    "es": "Fotografía",
    "de": "Foto"
  },
  "Fotografia indisponível. Peça a revisão do registo.": {
    "en": "Photograph unavailable. Ask for the record to be reviewed.",
    "fr": "Photo indisponible. Demandez une vérification de la fiche.",
    "es": "Fotografía no disponible. Solicite la revisión del registro.",
    "de": "Foto nicht verfügbar. Bitten Sie um Prüfung des Datensatzes."
  },
  "Fotografia não incluída por exceder os limites do relatório.": {
    "en": "Photograph omitted because it exceeds report limits.",
    "fr": "Photo non incluse car elle dépasse les limites du rapport.",
    "es": "Fotografía no incluida por superar los límites del informe.",
    "de": "Foto nicht enthalten, da es die Berichtsgrenzen überschreitet."
  },
  " (primeiro fotograma)": {
    "en": " (first frame)",
    "fr": " (première image)",
    "es": " (primer fotograma)",
    "de": " (erstes Einzelbild)"
  },
  "Outras fotografias": {
    "en": "Other photographs",
    "fr": "Autres photos",
    "es": "Otras fotografías",
    "de": "Weitere Fotos"
  },
  "{count} fotografia(s) não incluída(s). Limite de {limit} por relatório; consulte o registo da visita.": {
    "en": "{count} photograph(s) omitted. Limit of {limit} per report; consult the visit record.",
    "fr": "{count} photo(s) non incluse(s). Limite de {limit} par rapport ; consultez la fiche de visite.",
    "es": "{count} fotografía(s) no incluida(s). Límite de {limit} por informe; consulte el registro de la visita.",
    "de": "{count} Foto(s) nicht enthalten. Höchstens {limit} pro Bericht; prüfen Sie den Besuchsdatensatz."
  }
};
const locales = Object.freeze({ pt: 'pt-PT', en: 'en-GB', fr: 'fr-FR', es: 'es-ES', de: 'de-DE' });
function language(value = 'pt') {
  if (typeof value !== 'string' || !Object.hasOwn(locales, value)) throw Object.assign(Error('Idioma do relatório inválido.'), { statusCode: 400 });
  return value;
}
function translator(value) {
  const lang = language(value);
  return (key, params = {}) => {
    const message = lang === 'pt' ? key : messages[key]?.[lang] ?? key;
    return message.replace(/\{(count|limit)\}/g, (match, name) => Object.hasOwn(params, name) ? String(params[name]) : match);
  };
}
module.exports = { language, translator, locales };
