'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-work-guide-start-rules');
const scope='WORK_GUIDE_START',audience='cristalwater-work-guide-start-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(a){if(!['ADMIN','TECHNICIAN','TEAM_LEADER'].includes(a?.role)||a.principalType==='ENV_ADMIN'||a.principalType==='USER'&&a.role!=='ADMIN'&&!R.positive(a.technicianId))fail('WORK_START_FORBIDDEN',403);return requests.owner(a);}
const envelope=a=>({ok:true,version:1,owner:owner(a),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('work-guide-start\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
const vehicleSelect={id:true,plate:true,active:true,deletedAt:true,currentKm:true,updatedAt:true},technicianSelect={id:true,name:true,vehicleId:true,active:true,deletedAt:true,updatedAt:true,authVersion:true},transportSelect={id:true,vehicleId:true,codeAT:true,status:true,createdAt:true,updatedAt:true},sourceItems={orderBy:{id:'asc'},take:101,select:{id:true,name:true,type:true,unit:true,quantity:true}};
const workSelect={id:true,vehicleId:true,technicianId:true,guideId:true,inheritedFromId:true,isDraft:true,status:true,startKm:true,endKm:true,notes:true,closedAt:true,createdAt:true,updatedAt:true,items:{orderBy:{id:'asc'},select:{id:true,workGuideId:true,name:true,type:true,unit:true,quantity:true,initialQty:true,usedQty:true,updatedAt:true}}};
function noQuery(q){if(!R.keys(q,[]))fail('WORK_START_INVALID_REQUEST');}
async function permission(db,a,lock=false){owner(a);if(a.role==='ADMIN')return null;const id=Number(a.technicianId||a.id);if(lock)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${id} FOR SHARE`;const t=await db.technician.findUnique({where:{id},select:technicianSelect});if(!t?.active||t.deletedAt||!t.vehicleId)fail('WORK_START_ASSIGNMENT_REQUIRED',403);return t;}
function visible(c){const {permission:_,sourceRecord:__,...value}=c;return value;}
async function selected(db,a,p,lock=false){
 if(lock){await require('./transportGuideCreationService').lockVehicle(db,p.vehicleId);await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE "vehicleId"=${p.vehicleId} AND status='OPEN' ORDER BY id FOR UPDATE`;}
 const permit=await permission(db,a,lock);if(permit&&(permit.vehicleId!==p.vehicleId||permit.id!==p.technicianId))fail('WORK_START_NOT_FOUND',404);
 if(lock&&p.technicianId)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${p.technicianId} FOR SHARE`;
 const technician=p.technicianId?await db.technician.findUnique({where:{id:p.technicianId},select:technicianSelect}):null;
 if(p.technicianId&&(!technician?.active||technician.deletedAt||technician.vehicleId!==p.vehicleId))fail('WORK_START_ASSIGNMENT_CHANGED',409);
 if(lock)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${p.vehicleId} FOR UPDATE`;
 const vehicle=await db.vehicle.findUnique({where:{id:p.vehicleId},select:vehicleSelect});if(!vehicle?.active||vehicle.deletedAt)fail('WORK_START_NOT_FOUND',404);
 if(await db.workGuide.count({where:{vehicleId:p.vehicleId,status:'OPEN'}}))fail('WORK_START_ALREADY_OPEN',409);
 if(lock)await db.$queryRaw`SELECT id FROM "TransportGuide" WHERE "vehicleId"=${p.vehicleId} AND (status='ACTIVE' OR id=(SELECT id FROM "TransportGuide" WHERE "vehicleId"=${p.vehicleId} ORDER BY "createdAt" DESC,id DESC LIMIT 1)) ORDER BY id FOR SHARE`;
 const active=await db.transportGuide.findMany({where:{vehicleId:p.vehicleId,status:'ACTIVE'},select:transportSelect,orderBy:{id:'asc'},take:2});if(active.length>1)fail('WORK_START_ASSOCIATION_REVIEW',409);
 let transport=active[0]||null,source=transport?'TRANSPORT_GUIDE':'EMPTY',sourceRecord=null,items=[];
 if(transport&&await db.workGuide.count({where:{guideId:transport.id}}))fail('WORK_START_CLOSED_WORK',409);
 if(!transport){const key='vehicle_preset_'+p.vehicleId;if(lock)await db.$queryRaw`SELECT id FROM "SystemSetting" WHERE key=${key} FOR SHARE`;sourceRecord=await db.systemSetting.findUnique({where:{key}});
  if(sourceRecord){const parsed=require('../../frontend/cw-vehicle-stock-preset-rules').parse(sourceRecord.value);if(!['VALID','EMPTY'].includes(parsed.state))fail('WORK_START_PRESET_REVIEW',409);source='VEHICLE_PRESET';items=parsed.items;}
  else{transport=await db.transportGuide.findFirst({where:{vehicleId:p.vehicleId},select:transportSelect,orderBy:[{createdAt:'desc'},{id:'desc'}]});if(transport)source='LAST_GUIDE';}
 }
 if(transport){if(lock)await db.$queryRaw`SELECT id FROM "TransportGuideItem" WHERE "guideId"=${transport.id} ORDER BY id FOR SHARE`;items=(await db.transportGuide.findUnique({where:{id:transport.id},select:{items:sourceItems}})).items;}
 const c=json({vehicle,technician:technician?(({authVersion,...t})=>t)(technician):null,transport,source,items:items.map(i=>({name:i.name,type:i.type??null,unit:i.unit,quantity:i.quantity})),permission:permit,sourceRecord});
 if(!R.plan(c,p))fail('WORK_START_REVIEW_REQUIRED',409);return c;
}
async function list(a,raw={},db=prisma){owner(a);const q=R.query(raw);if(!q)fail('WORK_START_INVALID_QUERY');return db.$transaction(async tx=>{const permit=await permission(tx,a),where={active:true,deletedAt:null,...(q.vehicleId?{id:q.vehicleId}:{}),...(permit?{AND:[{id:permit.vehicleId}]}:{}),...(q.q?{plate:{contains:q.q,mode:'insensitive'}}:{})},total=await tx.vehicle.count({where}),vehicles=await tx.vehicle.findMany({where,select:vehicleSelect,orderBy:[{plate:'asc'},{id:'asc'}],skip:(q.page-1)*25,take:25}),rows=[];
 for(const vehicle of vehicles){const technicians=await tx.technician.findMany({where:{vehicleId:vehicle.id,active:true,deletedAt:null,...(permit?{id:permit.id}:{})},select:technicianSelect,orderBy:{id:'asc'},take:101}),openWorkCount=await tx.workGuide.count({where:{vehicleId:vehicle.id,status:'OPEN'}}),existing=await tx.workGuide.findFirst({where:{vehicleId:vehicle.id,status:'OPEN',...(permit?{technicianId:permit.id}:{})},select:{id:true},orderBy:{id:'asc'}});const row=json({vehicle,technicians:technicians.map(({authVersion,...t})=>t),openWorkCount,existingWorkId:existing?.id||null});if(!R.row(row))fail('WORK_START_DATA_REVIEW',409);rows.push(row);}
 return {...envelope(a),page:q.page,size:25,total,rows};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:20000});}
async function review(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);const p=R.input(body);if(!p)fail('WORK_START_INVALID_FIELDS');const c=await db.$transaction(tx=>selected(tx,a,p),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000}),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(a),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:visible(c),plan:R.plan(c,p)};}
const packet=(a,requestId,result)=>({...envelope(a),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(a,requestId,q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId))fail('WORK_START_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(a,requestId,saved?.scope===scope?saved.response:null);},{maxWait:15000,timeout:15000});}
async function commit(a,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('WORK_START_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('WORK_START_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('WORK_START_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('WORK_START_REVIEW_REQUIRED',409);
 const request=requests.context(a,scope,p.vehicleId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(a,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('WORK_START_REVIEW_EXPIRED',409);const c=await selected(tx,a,p,true);if(digest(c)!==claims.choiceDigest)fail('WORK_START_CHANGED',409);const plan=R.plan(c,p);
 const work=await tx.workGuide.create({data:{vehicleId:p.vehicleId,technicianId:p.technicianId,guideId:plan.guideId,inheritedFromId:plan.inheritedFromId,startKm:plan.startKm,notes:p.notes,status:'OPEN',isDraft:plan.isDraft,items:{create:c.items.map(i=>({...i,initialQty:i.quantity,usedQty:0}))}},select:workSelect});
 const vehicle=plan.updateVehicle?await tx.vehicle.update({where:{id:p.vehicleId},data:{currentKm:plan.vehicleKmAfter,updatedAt:new Date(Math.max(Date.now(),Date.parse(c.vehicle.updatedAt)+1))},select:vehicleSelect}):c.vehicle;
 let lockId=null,notificationId=null;if(plan.missingTransportGuide){const title='Guia de transporte AT em falta',message=c.vehicle.plate+' iniciou uma guia de obra provisória. Reveja e associe a guia de transporte.',metadata={vehicleId:p.vehicleId,technicianId:p.technicianId,workGuideId:work.id,reason:'REVIEWED_WORK_START',source:c.source};const hold=await tx.operationalLock.create({data:{lockType:'MISSING_TRANSPORT_GUIDE',severity:'WARNING',status:'PENDING',entity:'WorkGuide',entityId:work.id,technicianId:p.technicianId,vehicleId:p.vehicleId,title,message,payload:metadata,requestedBy:subject}});lockId=hold.id;const notification=await tx.notification.create({data:{type:'WARNING',eventType:'TRANSPORT_GUIDE_MISSING',title,message,role:'ADMIN',severity:'WARNING',metadata}});notificationId=notification.id;}
 const audit=await tx.userAuditLog.create({data:{userId:a.role==='ADMIN'||a.principalType==='USER'?Number(a.userId||a.id):null,actor:subject,action:scope,entity:'WorkGuide',entityId:String(work.id),metadata:{requestId:body.requestId,reason:p.reason,before:visible(c),sourceRecord:c.sourceRecord,plan,lockId,notificationId}}});
 return packet(a,body.requestId,await requests.confirm(tx,request,{vehicleId:p.vehicleId,work,vehicle,proposal:p,before:visible(c),plan,lockId,notificationId,auditId:audit.id}));},{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('WORK_START_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(a,requestId,body={},q={},db=prisma){const subject=owner(a);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['vehicleId'])||!R.positive(body.vehicleId))fail('WORK_START_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==body.vehicleId)fail('WORK_START_REQUEST_CONFLICT',409);return packet(a,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:a.role==='ADMIN'||a.principalType==='USER'?Number(a.userId||a.id):null,actor:subject,action:'WORK_GUIDE_START_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(a,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.vehicleId,payloadHash:'cancelled'},{...body,work:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,commit,result,cancel};
