'use strict';
const {prisma}=require('../prismaClient'),jwt=require('jsonwebtoken'),{createHmac,randomUUID}=require('node:crypto'),{getJwtSecret}=require('../utils/jwtSecret'),requests=require('./fieldWriteRequestService'),R=require('../../frontend/cw-work-guide-close-rules');
const scope='WORK_GUIDE_CLOSE',audience='cristalwater-work-guide-close-v1',fail=(code,statusCode=400)=>{throw Object.assign(Error(code),{code,statusCode});};
function owner(actor){if(!['ADMIN','TECHNICIAN','TEAM_LEADER'].includes(actor?.role)||actor.principalType==='ENV_ADMIN'||actor.principalType==='USER'&&actor.role!=='ADMIN'&&!R.positive(actor.technicianId))fail('WORK_CLOSE_FORBIDDEN',403);return requests.owner(actor);}
const envelope=actor=>({ok:true,version:1,owner:owner(actor),asOf:new Date().toISOString()}),digest=v=>createHmac('sha256',getJwtSecret()).update('work-guide-close\0'+JSON.stringify(v)).digest('hex'),json=v=>JSON.parse(JSON.stringify(v));
const workSelect={id:true,vehicleId:true,technicianId:true,guideId:true,status:true,isDraft:true,inheritedFromId:true,startKm:true,endKm:true,notes:true,closedAt:true,createdAt:true,updatedAt:true},vehicleSelect={id:true,plate:true,status:true,active:true,deletedAt:true,currentKm:true,updatedAt:true},itemSelect={id:true,workGuideId:true,name:true,type:true,unit:true,quantity:true,usedQty:true,initialQty:true,updatedAt:true},transportSelect={id:true,vehicleId:true,codeAT:true,status:true,isDraft:true,updatedAt:true};
function noQuery(q){if(!R.keys(q,[]))fail('WORK_CLOSE_INVALID_REQUEST');}
async function permission(db,actor,lock=false){owner(actor);if(actor.role==='ADMIN')return null;const id=Number(actor.technicianId||actor.id);if(lock)await db.$queryRaw`SELECT id FROM "Technician" WHERE id=${id} FOR SHARE`;const tech=await db.technician.findUnique({where:{id},select:{id:true,vehicleId:true,active:true,deletedAt:true,authVersion:true}});if(!tech?.active||tech.deletedAt||!tech.vehicleId)fail('WORK_CLOSE_ASSIGNMENT_REQUIRED',403);return tech;}
function visible(c){const {permission:_,...value}=c;return value;}
async function selected(db,actor,p,lock=false){
 const initial=await db.workGuide.findUnique({where:{id:p.workGuideId},select:{vehicleId:true}});
 // Shared vehicle lock and work-first row order match transport management/opening.
 if(lock&&initial?.vehicleId)await require('./transportGuideCreationService').lockVehicle(db,initial.vehicleId);
 if(lock)await db.$queryRaw`SELECT id FROM "WorkGuide" WHERE id=${p.workGuideId} FOR UPDATE`;
 const permit=await permission(db,actor,lock),work=await db.workGuide.findUnique({where:{id:p.workGuideId},select:workSelect});
 if(!work||permit&&(work.vehicleId!==permit.vehicleId||work.technicianId!==permit.id))fail('WORK_CLOSE_NOT_FOUND',404);
 if(work.vehicleId!==initial?.vehicleId)fail('WORK_CLOSE_CHANGED',409);
 if(lock&&work.vehicleId)await db.$queryRaw`SELECT id FROM "Vehicle" WHERE id=${work.vehicleId} FOR UPDATE`;
 const vehicle=work.vehicleId?await db.vehicle.findUnique({where:{id:work.vehicleId},select:vehicleSelect}):null;
 if(permit&&(!vehicle?.active||vehicle.deletedAt))fail('WORK_CLOSE_ASSIGNMENT_REQUIRED',403);
 if(lock&&work.guideId)await db.$queryRaw`SELECT id FROM "TransportGuide" WHERE id=${work.guideId} FOR SHARE`;
 const transport=work.guideId?await db.transportGuide.findUnique({where:{id:work.guideId},select:transportSelect}):null;
 if(lock)await db.$queryRaw`SELECT id FROM "WorkGuideItem" WHERE "workGuideId"=${work.id} ORDER BY id FOR UPDATE`;
 const items=await db.workGuideItem.findMany({where:{workGuideId:work.id},select:itemSelect,orderBy:{id:'asc'},take:101}),technician=work.technicianId?await db.technician.findUnique({where:{id:work.technicianId},select:{id:true,name:true}}):null;
 const choice=json({work,vehicle,transport,technician,items,permission:permit});if(!R.plan(choice,p))fail('WORK_CLOSE_REVIEW_REQUIRED',409);return choice;
}
async function list(actor,raw={},db=prisma){owner(actor);const q=R.query(raw);if(!q)fail('WORK_CLOSE_INVALID_QUERY');return db.$transaction(async tx=>{const permit=await permission(tx,actor),where={status:'OPEN',...(permit?{vehicleId:permit.vehicleId,technicianId:permit.id,vehicle:{is:{active:true,deletedAt:null}}}:{}),...(q.workGuideId?{id:q.workGuideId}:{}),...(q.q?{OR:[{vehicle:{plate:{contains:q.q,mode:'insensitive'}}},{technician:{name:{contains:q.q,mode:'insensitive'}}}]}:{})};const rows=await tx.workGuide.findMany({where,select:{...workSelect,vehicle:{select:vehicleSelect},technician:{select:{id:true,name:true}},guide:{select:transportSelect},items:{select:itemSelect,orderBy:{id:'asc'},take:101}},orderBy:{id:'desc'},skip:(q.page-1)*25,take:25});const guides=rows.map(({vehicle,technician,guide,items,...work})=>({work,vehicle,technician,transport:guide,items}));return {...envelope(actor),page:q.page,size:25,total:await tx.workGuide.count({where}),guides};},{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000});}
async function review(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);const p=R.input(body);if(!p)fail('WORK_CLOSE_INVALID_FIELDS');const c=await db.$transaction(tx=>selected(tx,actor,p),{isolationLevel:'RepeatableRead',maxWait:15000,timeout:15000}),requestId=randomUUID(),reviewToken=jwt.sign({proposalDigest:digest(p),choiceDigest:digest(c)},getJwtSecret(),{algorithm:'HS256',audience,subject,jwtid:requestId,expiresIn:300});return {...envelope(actor),requestId,reviewToken,expiresAt:new Date(jwt.decode(reviewToken).exp*1000).toISOString(),proposal:p,choice:visible(c),plan:R.plan(c,p)};}
const packet=(actor,requestId,result)=>({...envelope(actor),requestId,status:result?.cancelled?'CANCELLED':result?'CONFIRMED':'UNCONFIRMED',result:result||null});
async function result(actor,requestId,q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId))fail('WORK_CLOSE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});return packet(actor,requestId,saved?.scope===scope?saved.response:null);},{maxWait:15000,timeout:15000});}
async function commit(actor,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.keys(body,['proposal','requestId','reviewToken'])||!R.uuid(body.requestId)||typeof body.reviewToken!=='string'||body.reviewToken.length>4000)fail('WORK_CLOSE_INVALID_REQUEST');const p=R.input(body.proposal);if(!p)fail('WORK_CLOSE_INVALID_FIELDS');let claims;try{claims=jwt.verify(body.reviewToken,getJwtSecret(),{algorithms:['HS256'],audience,subject,ignoreExpiration:true});}catch(_){fail('WORK_CLOSE_REVIEW_REQUIRED',409);}if(claims.jti!==body.requestId||claims.proposalDigest!==digest(p)||typeof claims.choiceDigest!=='string'||!Number.isInteger(claims.exp))fail('WORK_CLOSE_REVIEW_REQUIRED',409);
 const request=requests.context(actor,scope,p.workGuideId,body.requestId,{proposalDigest:claims.proposalDigest,reviewToken:body.reviewToken});
 try{return await db.$transaction(async tx=>{const saved=await requests.recover(tx,request);if(saved)return packet(actor,body.requestId,saved);if(claims.exp*1000<=Date.now())fail('WORK_CLOSE_REVIEW_EXPIRED',409);const c=await selected(tx,actor,p,true);if(digest(c)!==claims.choiceDigest)fail('WORK_CLOSE_CHANGED',409);const plan=R.plan(c,p),now=new Date(),work=await tx.workGuide.update({where:{id:c.work.id},data:{status:'CLOSED',closedAt:now,endKm:plan.endKm},select:workSelect});
  if(p.updateVehicle)await tx.vehicle.update({where:{id:c.vehicle.id},data:{currentKm:plan.vehicleKmAfter}});
  const audit=await tx.userAuditLog.create({data:{userId:actor.role==='ADMIN'||actor.principalType==='USER'?Number(actor.userId||actor.id):null,actor:subject,action:scope,entity:'WorkGuide',entityId:String(c.work.id),metadata:{requestId:body.requestId,reason:p.reason,before:visible(c),plan,closedAt:now.toISOString()}}});
  return packet(actor,body.requestId,await requests.confirm(tx,request,{workGuideId:c.work.id,work,proposal:p,reason:p.reason,before:visible(c),plan,appliedAt:now.toISOString(),auditId:audit.id}));
 },{maxWait:15000,timeout:25000});}catch(e){if(e.code==='FIELD_REQUEST_REUSED')fail('WORK_CLOSE_REQUEST_CONFLICT',409);throw e;}
}
async function cancel(actor,requestId,body={},q={},db=prisma){const subject=owner(actor);noQuery(q);if(!R.uuid(requestId)||!R.keys(body,['workGuideId'])||!R.positive(body.workGuideId))fail('WORK_CLOSE_INVALID_REQUEST');return db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${`field-request:${subject}:${requestId}`}))::text`;const saved=await tx.fieldWriteRequest.findUnique({where:{owner_requestId:{owner:subject,requestId}}});if(saved){if(saved.scope!==scope||saved.resourceId!==body.workGuideId)fail('WORK_CLOSE_REQUEST_CONFLICT',409);return packet(actor,requestId,saved.response);}const audit=await tx.userAuditLog.create({data:{userId:actor.role==='ADMIN'||actor.principalType==='USER'?Number(actor.userId||actor.id):null,actor:subject,action:'WORK_GUIDE_CLOSE_CANCELLED',entity:'FieldWriteRequest',entityId:requestId,metadata:body}});return packet(actor,requestId,await requests.confirm(tx,{owner:subject,scope,requestId,resourceId:body.workGuideId,payloadHash:'cancelled'},{...body,work:null,cancelled:true,auditId:audit.id}));},{maxWait:15000,timeout:15000});}
module.exports={owner,list,review,commit,result,cancel};
