import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-admin-legacy-entry'),now=1800000000000;
const credential=claims=>Buffer.from('{"alg":"HS256"}').toString('base64url')+'.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.browser-fixture';
const values=(claims,user={id:claims.id,role:claims.role},canonical=false)=>{const token=credential({...claims,exp:claims.exp??now/1000+60});return canonical?[token,null,null,JSON.stringify(user),null]:[null,token,null,null,JSON.stringify(user)];};
describe('legacy administrative entry navigation',()=>{
 it('sends each coherent role to its existing area, preserving only a supported language',()=>{for(const [role,path] of [['ADMIN','/admin-master-control'],['CLIENT','/client-portal'],['TECHNICIAN','/technician-field-mode'],['TEAM_LEADER','/technician-field-mode']])for(const canonical of [false,true])expect(R.destination(values({id:7,role},undefined,canonical),'?lang=fr&clientId=999&returnTo=https://bad.test&token=private',now)).toBe(path+'?lang=fr');});
 it('keeps User and technician identities distinct for team leaders',()=>{expect(R.destination(values({id:7,userId:7,technicianId:11,principalType:'USER',role:'TEAM_LEADER'},{id:7,technicianId:11,role:'TEAM_LEADER'}),'',now)).toBe('/technician-field-mode');expect(R.destination(values({id:11,technicianId:11,principalType:'TECHNICIAN',role:'TEAM_LEADER'},{id:11,technicianId:11,role:'TEAM_LEADER'}),'',now)).toBe('/technician-field-mode');});
 it('refuses expired, mismatched and inconsistent identity aliases',()=>{const good=values({id:7,role:'ADMIN'});for(const v of [values({id:7,role:'ADMIN'},{id:8,role:'ADMIN'}),values({id:7,role:'CLIENT'},{id:7,role:'ADMIN'}),[credential({id:8,role:'ADMIN',exp:now/1000+60}),...good.slice(1)],good.map((v,i)=>i===3?'{bad':v)])expect(R.destination(v,'',now)).toBe('/login?reason=invalid_session');expect(R.destination(values({id:7,role:'ADMIN',exp:1}),'',now)).toBe('/login?reason=session_expired');expect(R.destination([null,null,null,null,null],'',now)).toBe('/login?reason=no_session');});
 it('does not propagate unknown or repeated language parameters or mutate the input',()=>{const v=values({id:7,role:'ADMIN'}),original=[...v];for(const query of ['?lang=xx','?lang=pt&lang=de','?lang=constructor','?lang=https://bad.test'])expect(R.destination(v,query,now)).toBe('/admin-master-control');expect(v).toEqual(original);});
});
