import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),R=require('../frontend/cw-admin-catalogue'),source=fs.readFileSync('frontend/crystal-os-v2-nav.js','utf8'),context={window:{}};
vm.runInNewContext(source.slice(source.indexOf('  const NAV ='),source.indexOf('  function flatLinks')),context);const navigation=context.window.CWAdminNavigation,rows=R.build(navigation);
describe('administrative catalogue navigation',()=>{
 it('uses every live ADMIN shell entry and merges repeated links across areas',()=>{const paths=[...new Set(navigation.groups.flatMap(g=>g.links.map(l=>R.canonical(l[0]))))];expect(paths.every(p=>rows.some(r=>r.key===p))).toBe(true);expect(new Set(rows.map(r=>r.key)).size).toBe(rows.length);expect(rows.find(r=>r.key==='/admin-live-map').groups).toEqual(['1','4']);expect(Object.isFrozen(navigation.groups[0].links[0])).toBe(true);});
 it('refuses unrecognized, external, protocol-relative, credential or encoded destinations',()=>{for(const href of ['https://bad.test','//bad.test','javascript:alert(1)','/admin-menu/../../x','/admin-menu?token=secret&x=1','/%2f%2fbad.test','/admin-menu#<img>'])expect(R.safeHref(href)).toBe(false);for(const value of ['/not-a-real-module','https://bad.test']){const changed=JSON.parse(JSON.stringify(navigation));changed.groups[0].links[0][0]=value;expect(()=>R.build(changed)).toThrow();}});
 it('routes a technical sheet through pool selection and stock links to actual anchors',()=>{expect(rows.find(r=>r.key==='/admin-pool-technical')).toMatchObject({href:'/admin-pools',context:'pool'});expect(rows.find(r=>r.key==='/admin-inventory?tab=products').href).toBe('/admin-inventory#stock');expect(rows.find(r=>r.key==='/admin-inventory?tab=movements').href).toBe('/admin-inventory#movements');});
 it('rejects partial navigation and reordered or missing groups',()=>{expect(()=>R.build({})).toThrow();const changed=JSON.parse(JSON.stringify(navigation));changed.groups.reverse();expect(()=>R.build(changed)).toThrow();});
 it('validates filter multiplicity, language, area and bounded literal query',()=>{for(const query of ['?q=a&q=b','?group=01','?group=13','?lang=xx','?lang=pt&lang=de','?returnTo=https://bad.test','?q=%00','?q='+('x'.repeat(101))])expect(R.filters(query)).toBeNull();expect(R.filters('?q=A%26B+%3Cimg%3E&lang=de&group=6')).toEqual({q:'A&B <img>',lang:'de',group:'6'});});
 it('matches accent-insensitive names and every supported language, without regex semantics',()=>{expect(R.search(rows,{q:'seguranca',group:''}).map(r=>r.key)).toEqual(['/admin-security']);expect(R.search(rows,{q:'faturas',group:''}).map(r=>r.key)).toEqual(['/invoices']);expect(R.search(rows,{q:'Wartung',group:''}).map(r=>r.key)).toEqual(['/admin-operational-settings#equipmentReminderControls']);expect(R.search(rows,{q:'.*',group:''})).toEqual([]);expect(R.search(rows,{q:'seguranca',group:'1'})).toEqual([]);});
 it('forwards only a supported language while retaining a verified anchor',()=>{const row=rows.find(r=>r.key==='/admin-vehicles#works');expect(R.href(row,'fr')).toBe('/admin-vehicles?lang=fr#works');expect(()=>R.href(row,'https://bad.test')).toThrow();expect(R.href(rows.find(r=>r.key==='/admin-email-review'),'de')).toBe('/admin-email-review?lang=de');});
 it('contains only existing root pages and existing declared anchor targets',()=>{for(const row of rows){const url=new URL(row.href,'https://catalogue.invalid'),html=fs.readFileSync('frontend'+url.pathname+'.html','utf8');if(url.hash)expect(html).toMatch(new RegExp('id=["\']'+url.hash.slice(1)+'["\']'));expect(html.length).toBeGreaterThan(100);}});
});
