import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-admin-day-rules'),S=require('../src/services/adminDayService');
const date='2026-09-25',range=R.bounds(date),f=R.filters({date}),row={key:'REGULAR:1',kind:'REGULAR',id:1,status:'NOT_DONE',group:'NOT_DONE',scheduledAt:range.start,scheduleSource:'plannedDate',startAt:null,endAt:null,client:{id:1,name:'Old 50%_x'},pool:{id:2,name:'P'},technician:null,recordedTechnicianName:'',legacyUser:null},packet={ok:true,version:1,owner:'ADMIN:1',asOf:'2026-09-25T12:00:00.000Z',timeZone:R.timeZone,basis:'SCHEDULED_DAY',day:date,range,filters:f,pageSize:50,total:1,pages:1,hasPrevious:false,hasNext:false,totals:R.totals([row]),rows:[row]};
describe('administrative day visits',()=>{
 it('never treats NOT_DONE or arbitrary substrings as completed',()=>{for(const s of ['NOT_DONE','not done','Não concluída','INCOMPLETE','FAILED'])expect(R.group(s)).toBe('NOT_DONE');for(const s of ['UNDONE','DONE_LATER','NOT_IN_PROGRESS','ARCHIVED',''])expect(R.group(s)).toBe('OTHER');for(const s of ['DONE','completed','Concluída'])expect(R.group(s)).toBe('DONE');});
 it('uses Lisbon civil days at both summer and winter boundaries',()=>{expect(range).toEqual({start:'2026-09-24T23:00:00.000Z',end:'2026-09-25T23:00:00.000Z'});expect(R.bounds('2026-01-25')).toEqual({start:'2026-01-25T00:00:00.000Z',end:'2026-01-26T00:00:00.000Z'});expect(R.localDay('2026-09-24T23:00:00Z')).toBe(date);});
 it('keeps 23 and 25 hour days at clock changes',()=>{for(const [d,h] of [['2026-03-29',23],['2026-10-25',25]]){const b=R.bounds(d);expect((Date.parse(b.end)-Date.parse(b.start))/3600000).toBe(h);expect(R.localDay(b.start)).toBe(d);expect(R.localDay(new Date(Date.parse(b.end)-1))).toBe(d);}});
 it('rejects invalid dates, unknown filters, ambiguous arrays and page overflow',()=>{for(const raw of [{date:'2026-02-30'},{date:'25-09-2026'},{date:'1999-01-01'},{date:['2026-09-25']},{page:'01'},{page:'42949674'},{group:'FAILED'},{kind:'user'},{extra:'x'}])expect(R.filters(raw)).toBeNull();expect(R.filters({date:'2024-02-29'})).not.toBeNull();});
 it('keeps literal search and typed visit identities',()=>{expect(R.matches(row,R.filters({q:'50%_x'}))).toBe(true);expect(R.matches(row,R.filters({q:'50Zxx'}))).toBe(false);expect(R.matches(row,R.filters({q:'REGULAR:1'}))).toBe(true);expect(R.matches(row,R.filters({kind:'EXTRA'}))).toBe(false);});
 it('uses a recorded date only when a regular planned date is absent',()=>{const v={id:1,status:'PLANNED',plannedDate:null,date:new Date(range.start),startAt:new Date(range.end),endAt:null,client:null,pool:{id:2,name:'Transferred',clientId:999},technician:null,technicianName:null};const projected=S.project('REGULAR',v);expect(projected.scheduleSource).toBe('date');expect(projected.scheduledAt).toBe(range.start);expect(projected.client).toBeNull();});
 it('includes the beginning and excludes the end of the selected day',()=>{expect(R.row(row,range)).toBe(true);expect(R.row({...row,scheduledAt:range.end},range)).toBe(false);expect(R.row({...row,scheduledAt:new Date(Date.parse(range.start)-1).toISOString()},range)).toBe(false);});
 it('accepts the same numeric ID across types and rejects duplicate keys at different times',()=>{const extra={...row,key:'EXTRA:1',kind:'EXTRA',scheduleSource:'scheduledAt',recordedTechnicianName:null},rows=[extra,row];expect(R.packet({...packet,total:2,rows,totals:R.totals(rows)},f,'ADMIN:1')).toBe(true);const duplicates=[row,{...row,scheduledAt:new Date(Date.parse(range.start)+1000).toISOString()}];expect(R.packet({...packet,total:2,rows:duplicates,totals:R.totals(duplicates)},f,'ADMIN:1')).toBe(false);});
 it('refuses wrong day, owner, totals, range, row order and status classification',()=>{expect(R.packet(packet,f,'ADMIN:1')).toBe(true);for(const change of [{owner:'ADMIN:2'},{day:'2026-09-24'},{range:{...range,end:'2026-09-26T00:00:00.000Z'}},{total:2},{rows:[{...row,group:'DONE'}]},{totals:{...packet.totals,DONE:1}}])expect(R.packet({...packet,...change},f,'ADMIN:1')).toBe(false);});
 it('resolves a blank day from the server snapshot, independent of browser timezone',()=>{const filters=R.filters({});expect(R.packet({...packet,filters,asOf:'2026-09-24T23:30:00.000Z'},filters,'ADMIN:1')).toBe(true);expect(R.packet({...packet,filters,asOf:'2026-09-24T22:59:00.000Z'},filters,'ADMIN:1')).toBe(false);});
 it('checks identity and filters before any database reads',async()=>{const db={$transaction:()=>{throw Error('Unexpected query');}};await expect(S.read({id:1,role:'TECHNICIAN'},{date},db)).rejects.toMatchObject({statusCode:403});await expect(S.read({id:1,role:'ADMIN'},{date:'bad'},db)).rejects.toMatchObject({statusCode:400});});
});
