import {describe,it,expect} from 'vitest';
const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../frontend/cw-auth.js'),'utf8');
function fixture({pathname='/technician-field-mode',fetcher=async()=>new Response('{}',{status:401})}={}){
 const events={},handlers={},nodes=new Set(),stored=new Map([['token','qa-token-A'],['cristalwater_jwt','qa-token-A'],['user','{"id":41,"role":"TECHNICIAN"}'],['cristalwater_user','{"id":41,"role":"TECHNICIAN"}'],['cwFieldDrafts','literal <b>{owner}</b>']]),timers=[],redirects=[];let observer,failRemoval=false;
 function make(tag){const node={tag,style:{},attributes:{},isConnected:false,hidden:false,children:[],get textContent(){return this.text||'';},set textContent(value){this.text=String(value);this.firstChild={text:this.text};},setAttribute(key,value){this.attributes[key]=value;},removeAttribute(key){delete this.attributes[key];},append(...values){this.children.push(...values);if(this.isConnected)for(const child of values)connect(child);},appendChild(value){this.append(value);},prepend(value){this.children.unshift(value);connect(value);},remove(){this.isConnected=false;for(const child of this.children)child.remove();},closest(){return null;}};nodes.add(node);return node;}
 function connect(node){node.isConnected=true;for(const child of node.children)connect(child);}
 const root={lang:'pt'},body=make('body');connect(body);
 const context={document:{documentElement:root,body,createElement:make,getElementById:id=>[...nodes].find(node=>node.id===id&&node.isConnected)||null,addEventListener:(type,fn)=>(handlers[type]??=[]).push(fn)},localStorage:{getItem:key=>stored.get(key)||null,setItem:(key,value)=>stored.set(key,value),removeItem:key=>{if(failRemoval)throw Error('Original removal failure');stored.delete(key);}},location:{pathname,hostname:'field.test',port:'',protocol:'https:',origin:'https://field.test',href:'https://field.test'+pathname,search:'',replace:path=>redirects.push(path)},navigator:{serviceWorker:{getRegistration:async()=>null}},fetch:fetcher,Headers,URL,URLSearchParams,AbortSignal,MutationObserver:class{constructor(fn){observer=fn;}observe(){}},setTimeout:(fn,delay)=>{timers.push({fn,delay});return timers.length;},clearTimeout:()=>{}};
 context.window=context;context.addEventListener=(type,fn)=>events[type]=fn;
 vm.runInNewContext(source,context);
 return {context,stored,timers,redirects,handlers,node:id=>context.document.getElementById(id),locale(value){root.lang=value;observer();events['cw-language-change']();},failRemoval(){failRemoval=true;},settle:async()=>{for(let i=0;i<16;i++)await Promise.resolve();}};
}
describe('owned auth presentation without session changes',()=>{
 it('keeps field expiry local, preserves records and paints the original banner leaves',async()=>{const f=fixture(),before=[...f.stored];expect((await f.context.fetch('/api/qa')).status).toBe(401);const banner=f.node('cwSessionExpired'),[message,link]=banner.children;f.locale('en');expect(message.textContent).toContain('same account');expect(link.textContent).toBe('Sign in again');expect(link.href).toBe('/technician-login');expect(banner.attributes.role).toBe('alert');expect(message.attributes['data-cw-no-i18n']).toBe('');f.locale('de-DE');expect(link.textContent).toBe('Erneut anmelden');f.locale('invalid');expect(link.textContent).toBe('Voltar a entrar');expect([...f.stored]).toEqual(before);expect(f.redirects).toEqual([]);expect(f.context.CristalAuth.isSessionExpired()).toBe(true);});
 it('does not expire on foreign credentials or foreign origins',async()=>{const f=fixture();await f.context.fetch('/api/qa',{headers:{Authorization:'Bearer another-account'}});await f.context.fetch('https://other.test/api/qa');expect(f.node('cwSessionExpired')).toBe(null);expect(f.context.CristalAuth.isSessionExpired()).toBe(false);});
 it('ignores a held 401 after token renewal',async()=>{let release;const f=fixture({fetcher:()=>new Promise(resolve=>{release=resolve;})});const work=f.context.fetch('/api/qa');await f.context.CristalAuth.persistSession('qa-token-B',{id:41,role:'TECHNICIAN'});release(new Response('{}',{status:401}));await work;expect(f.node('cwSessionExpired')).toBe(null);expect(f.context.CristalAuth.getToken()).toBe('qa-token-B');});
 it('removes the banner only when a new token is persisted and preserves the draft',async()=>{const f=fixture();await f.context.fetch('/api/qa');await f.context.CristalAuth.persistSession('qa-token-A',{id:41,role:'TECHNICIAN'});expect(f.node('cwSessionExpired')).not.toBe(null);await f.context.CristalAuth.persistSession('qa-token-B',{id:41,role:'TECHNICIAN'});f.locale('en');expect(f.node('cwSessionExpired')).toBe(null);expect(f.context.CristalAuth.isSessionExpired()).toBe(false);expect(f.stored.get('cwFieldDrafts')).toBe('literal <b>{owner}</b>');});
 it('keeps network error identity and the original toast deadline across languages',async()=>{const raw=new TypeError('Original <b>{owner}</b>'),f=fixture({fetcher:async()=>{throw raw;}}),before=[...f.stored];await expect(f.context.fetch('/api/qa')).rejects.toBe(raw);const node=f.node('cw-v21-toast'),timer=node._t;expect(f.timers.map(timer=>timer.delay)).toEqual([4200]);for(const language of ['en','fr','es','de','pt']){f.locale(language);expect(node._t).toBe(timer);expect(f.timers).toHaveLength(1);}f.locale('en');expect(node.textContent).toBe('Unstable connection. Your session was retained and your data will be preserved.');expect([...f.stored]).toEqual(before);f.timers[0].fn();f.locale('de');expect(node.style.display).toBe('none');});
 it('does not notify or clear the session on AbortError',async()=>{const raw=new DOMException('Original abort','AbortError'),f=fixture({fetcher:async()=>{throw raw;}});await expect(f.context.fetch('/api/qa')).rejects.toBe(raw);expect(f.node('cw-v21-toast')).toBe(null);expect(f.context.CristalAuth.getToken()).toBe('qa-token-A');expect(f.timers).toEqual([]);});
 it('leaves a foreign producer literal even with identical Portuguese text',async()=>{const f=fixture({fetcher:async()=>{throw Error('Original');}});await f.context.fetch('/api/qa').catch(()=>{});const literal=f.node('cw-v21-toast').textContent;f.context.CristalAuth.toast(literal);f.locale('en');expect(f.node('cw-v21-toast').textContent).toBe(literal);});
 it('keeps literal replacements and detached nodes outside repaint',async()=>{const f=fixture();await f.context.fetch('/api/qa');const [message,link]=f.node('cwSessionExpired').children;message.textContent='<b>foreign</b>';link.remove();f.locale('en');expect(message.textContent).toBe('<b>foreign</b>');expect(link.textContent).toBe('Voltar a entrar');});
 it('uses the existing logout failure path and resets busy state without clearing records',async()=>{const f=fixture(),before=[...f.stored],button={disabled:false,attributes:{},setAttribute(key,value){this.attributes[key]=value;},removeAttribute(key){delete this.attributes[key];}};f.failRemoval();await f.handlers.click[0]({target:{closest:()=>button},preventDefault(){}});f.locale('en');expect(f.node('cw-v21-toast').textContent).toBe('Could not sign out. Try again.');expect(button.disabled).toBe(false);expect(button.attributes['aria-busy']).toBe(undefined);expect([...f.stored]).toEqual(before);expect(f.redirects).toEqual([]);expect(f.timers[0].delay).toBe(4200);});
 it('retains the protected non-field 401 logout behavior',async()=>{const f=fixture({pathname:'/admin-master-control'});await f.context.fetch('/api/qa');await f.settle();expect(f.context.CristalAuth.getToken()).toBe('');expect(f.redirects).toEqual(['/login']);expect(f.stored.get('cwFieldDrafts')).toBe('literal <b>{owner}</b>');});
});
