import {describe,it,expect} from 'vitest';
const fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../frontend/cw-browser-push.js'),'utf8');
function fixture({token='A',response={configured:true,publicKey:'AQID'},fetcher}={}){
 const nodes=[],events={};let observer,permission=async()=>'denied',retired=[];
 const root={lang:'pt'},card={append(...values){nodes.push(...values);}};
 const node=()=>({isConnected:true,setAttribute(){},get textContent(){return this.text||'';},set textContent(value){this.text=String(value);this.firstChild={text:this.text};}});
 const context={document:{documentElement:root,querySelector:()=>card,createElement:node},localStorage:{getItem:()=>token},navigator:{serviceWorker:{register:async()=>({pushManager:{getSubscription:async()=>null,subscribe:async()=>({endpoint:'literal',toJSON:()=>({endpoint:'literal'})})}}),ready:Promise.resolve()}},PushManager:function(){},isSecureContext:true,Notification:{requestPermission:()=>permission()},fetch:fetcher|| (async()=>({ok:true,json:async()=>response})),MutationObserver:class{constructor(fn){observer=fn;}observe(){}},atob:value=>Buffer.from(value,'base64').toString('binary'),Uint8Array};
 context.window=context;context.CristalAuth={getToken:()=>token,retirePushSubscription:async(...args)=>retired.push(args)};context.addEventListener=(name,fn)=>events[name]=fn;
 vm.runInNewContext(source,context);
 return {nodes,root,retired,setToken:value=>{token=value;},setPermission:fn=>{permission=fn;},locale(value){root.lang=value;observer();events['cw-language-change']();},settle:async()=>{for(let i=0;i<12;i++)await Promise.resolve();}};
}
describe('owned browser push presentation',()=>{
 it('uses locale normalization and Portuguese fallback without changing nodes',async()=>{const f=fixture();await f.settle();f.locale('de-DE');expect(f.nodes[0].textContent).toBe('Handy-Hinweise aktivieren');f.locale('unknown');expect(f.nodes[0].textContent).toBe('Ativar avisos no telemóvel');});
 it('keeps initial missing-session error local and translated',async()=>{const f=fixture({token:''});await f.settle();f.locale('en');expect(f.nodes[1].textContent).toBe('Connect to the network to enable alerts.');await f.nodes[0].onclick();expect(f.nodes[1].textContent).toBe('The session changed. Enable alerts in the current account.');expect(f.nodes[0].disabled).toBe(false);});
 it('translates a changed session during public-key retrieval',async()=>{let release;const f=fixture({fetcher:()=>new Promise(resolve=>{release=resolve;})});f.setToken('B');release({ok:true,json:async()=>({configured:true,publicKey:'AQID'})});await f.settle();f.locale('en');expect(f.nodes[1].textContent).toBe('The session changed. Refresh the page to enable alerts.');expect(f.nodes[0].disabled).toBe(true);});
 it('does not register after an account change during permission',async()=>{let release;const f=fixture();await f.settle();f.setPermission(()=>new Promise(resolve=>{release=resolve;}));const work=f.nodes[0].onclick();f.setToken('B');release('granted');await work;f.locale('en');expect(f.nodes[1].textContent).toBe('The session changed. Refresh the page to enable alerts in the current account.');expect(f.nodes[0].disabled).toBe(true);expect(f.retired).toEqual([]);});
 it('releases a status replaced by another producer even with identical text',async()=>{const f=fixture();await f.settle();const text=f.nodes[1].textContent;f.nodes[1].textContent=text;f.locale('en');expect(f.nodes[1].textContent).toBe(text);expect(f.nodes[0].textContent).toBe('Enable phone alerts');});
 it('releases externally changed status and disconnected button ownership',async()=>{const f=fixture();await f.settle();f.nodes[1].textContent='<b>literal {owner}</b>';f.nodes[0].isConnected=false;f.locale('de');expect(f.nodes[1].textContent).toBe('<b>literal {owner}</b>');expect(f.nodes[0].textContent).toBe('Ativar avisos no telemóvel');});
 it('keeps a server error literal even when its text equals an owned message',async()=>{let call=0;const f=fixture({fetcher:async()=>++call===1?{ok:true,json:async()=>({configured:true,publicKey:'AQID'})}:{ok:false,status:503,json:async()=>({error:'Permissão de notificações não concedida.'})}});await f.settle();f.setPermission(async()=>'granted');await f.nodes[0].onclick();f.locale('en');expect(f.nodes[1].textContent).toBe('Permissão de notificações não concedida.');expect(f.nodes[0].disabled).toBe(false);});
});
