import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-client-technical-rules'),copy=require('../frontend/cw-client-technical-copy');
const row=()=>({id:3,clientId:7,poolId:null,poolName:null,technicianName:null,date:'2026-09-25T00:00:00.000Z',plannedDate:null,startAt:null,endAt:null,status:'LEGACY',notes:'<img src=x>',products:'original',readings:{ph:0,chlorine:null,alkalinity:1e-12,salt:-1,temperature:12.3456789,orpMv:null},chemicals:[{name:'original',quantity:0,unit:null}]});
const packet=()=>({ok:true,version:1,clientId:7,asOf:'2026-09-25T01:02:03.456Z',timeZone:'UTC',basis:'RECORDED_CLIENT_VISITS',filters:R.filters(),pageSize:50,total:1,pages:1,hasPrevious:false,hasNext:false,visits:[row()]});
describe('client technical history contract',()=>{
 it('requires canonical bounded page, pool and actual UTC dates',()=>{expect(R.filters({from:'2024-02-29',poolId:'12',page:'2'})).toEqual({poolId:12,from:'2024-02-29',to:'',page:2});for(const v of [{clientId:'1'},{poolId:'01'},{poolId:'2147483648'},{page:'0'},{page:'42949674'},{page:['1','2']},{from:'2026-02-29'},{from:'2026-02-28',to:'2026-02-01'}])expect(R.filters(v)).toBeNull();});
 it('keeps null, zero, precision, negative readings and historical text distinct',()=>{const v=row(),original=structuredClone(v);expect(R.row(v,7)).toBe(true);expect(v).toEqual(original);expect(R.row({...v,internalNotes:'PRIVATE'},7)).toBe(false);expect(R.row({...v,clientId:8},7)).toBe(false);expect(R.row({...v,readings:{...v.readings,ph:NaN}},7)).toBe(false);});
 it('rejects mismatched identity, totals, page, filters, duplicate IDs and order',()=>{expect(R.packet(packet(),R.filters(),7)).toBe(true);for(const change of [v=>v.clientId=8,v=>v.total=2,v=>v.pageSize=300,v=>v.visits[0].clientId=8,v=>v.filters.poolId=1,v=>v.basis='CURRENT_POOL_OWNER',v=>{v.total=2;v.visits.push(row());},v=>{v.total=2;v.visits.push({...row(),id:4});}]){const v=packet();change(v);expect(R.packet(v,R.filters(),7)).toBe(false);}});
 it('provides the same own-page copy keys for all five languages',()=>{const keys=Object.keys(copy.pt).sort();expect(Object.keys(copy).sort()).toEqual(['de','en','es','fr','pt']);for(const lang of Object.keys(copy)){expect(Object.keys(copy[lang]).sort()).toEqual(keys);expect(Object.values(copy[lang]).every(v=>typeof v==='string'&&v.length>0)).toBe(true);}});
});
