import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-collection-summary-rules'),S=require('../src/services/collectionSummaryService');
const now=Date.parse('2026-09-25T12:00:00.000Z');
const client={id:2,name:'Literal 50%_ <script>',status:'PAUSED',email:null,phone:null,lastReminderAt:null,invoices:[]};
const invoice=(id,amount,extra={})=>({id,status:'PENDING',amount,total:0,totalAmount:0,amountPaid:0,amountOpen:0,dueDate:null,...extra});
describe('collection summary',()=>{
  it('counts open documents and separates paused status from arrears',()=>{const row=S.project({...client,invoices:[invoice(1,10.11),invoice(2,20.22,{dueDate:new Date(now-1)}),invoice(3,80,{status:'DRAFT'}),invoice(4,90,{status:'CANCELLED'}),invoice(5,7,{amountPaid:7})]},now);expect(row).toMatchObject({clientStatus:'PAUSED',paymentStatus:'OVERDUE',openInvoices:2,overdueInvoices:1,amountCents:3033,overdueCents:2022});});
  it('uses document balances without subtracting unallocated credit or counting fully paid documents',()=>{expect(S.project({...client,creditBalance:999,invoices:[invoice(1,100,{amountPaid:30}),invoice(2,100,{amountOpen:2.34}),invoice(3,100,{amountPaid:100})]},now)).toMatchObject({amountCents:7234,openInvoices:2,paymentStatus:'PENDING'});});
  it('does not infer arrears from missing due dates or an equal consultation instant',()=>{expect(S.project({...client,invoices:[invoice(1,1),invoice(2,2,{dueDate:new Date(now)})]},now)).toMatchObject({overdueInvoices:0,paymentStatus:'PENDING'});expect(S.project({...client,invoices:[invoice(3,3,{status:'OVERDUE'})]},now)).toMatchObject({overdueInvoices:1,overdueCents:300});});
  it('keeps literal search characters and rejects ambiguous filters',()=>{for(const f of [{page:'01'},{page:'0'},{page:'42949674'},{paymentStatus:'PAUSED'},{q:['one','two']},{q:'\n'},{other:'x'}])expect(R.filters(f)).toBeNull();const row=S.project({...client,invoices:[invoice(1,1)]},now);expect(R.matches(row,R.filters({q:'50%_'}))).toBe(true);expect(R.matches(row,R.filters({q:'50Zx'}))).toBe(false);});
  it('refuses mixed identity, incompatible totals and missing clients',()=>{const row=S.project({...client,invoices:[invoice(1,1)]},now),filters=R.filters({}),packet={ok:true,version:1,owner:'ADMIN:1',asOf:new Date(now).toISOString(),timeZone:'UTC',basis:'RECEIVABLE_DOCUMENT_BALANCES_ALL_CLIENT_STATUSES',filters,pageSize:50,total:1,pages:1,hasPrevious:false,hasNext:false,totals:R.totals([row]),clients:[row]};expect(R.packet(packet,filters,'ADMIN:1')).toBe(true);for(const bad of [{owner:'ADMIN:2'},{total:2},{clients:[]},{totals:{...packet.totals,amountCents:101}},{clients:[{...row,openInvoices:0}]},{clients:[{...row,paymentStatus:'PAUSED'}]}])expect(R.packet({...packet,...bad},filters,'ADMIN:1')).toBe(false);});
  it('rejects non-administrators and malformed queries before reading',async()=>{const database={$transaction:()=>{throw Error('Unexpected lookup');}};await expect(S.read({id:1,role:'CLIENT'},{},database)).rejects.toMatchObject({statusCode:403});await expect(S.read({id:1,role:'ADMIN'},{page:['1','2']},database)).rejects.toMatchObject({statusCode:400});});
});
