import { describe, it, expect } from 'vitest';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url),r=require('../frontend/cw-company-closure-rules'),service=require('../src/services/companyClosureService');
const fields={title:'Férias',closureType:'HOLIDAY',status:'PLANNED',startDate:'2095-02-07',endDate:'2095-02-08',messageTitle:'Aviso',messageBody:'De {startDate} a {endDate}',emergencyPhone:'',emergencyEmail:'',routeAction:'PREVIEW_ONLY',...Object.fromEntries(r.booleans.map(k=>[k,true]))};
const create={requestId:'77e45e3a-a28b-4d09-9ae3-2c8b34d17450',operation:'CREATE',closureId:null,expectedVersion:null,fields};
describe('recoverable company closure rules',()=>{
 it('requires exact, possible calendar dates and ordered days',()=>{expect(r.fields(fields)).toBe(true);for(const day of ['2095-02-29','2095-02-30','2095-02-08suffix','1899-12-31','9999-01-01'])expect(r.fields({...fields,startDate:day})).toBe(false);expect(r.fields({...fields,startDate:'2095-02-09'})).toBe(false);});
 it('rejects unknown fields, untyped booleans, empty titles and arbitrary states',()=>{for(const patch of [{createdByUserId:7},{notifyClients:'false'},{title:' '},{status:'DELETED'},{routeAction:'DELETE_VISITS'},{messageBody:'a'.repeat(6001)}])expect(r.fields({...fields,...patch})).toBe(false);});
 it('binds create to no prior row and every other operation to a reviewed version',()=>{expect(r.command(create)).toBe(true);expect(r.command({...create,closureId:1})).toBe(false);expect(r.command({...create,operation:'ACTIVATE',fields:{}})).toBe(false);const command={...create,operation:'CANCEL',closureId:7,expectedVersion:'company-closure-v2:'+'a'.repeat(64),fields:{reason:'Adiado'}};expect(r.command(command)).toBe(true);expect(r.command({...command,fields:{reason:' '}})).toBe(false);});
 it('does not put a new request ID into the immutable intent hash',()=>{expect(r.intent(create)).not.toHaveProperty('requestId');expect(r.envelope(create).resourceId).toBe(1);expect(r.equal({b:2,a:1},{a:1,b:2})).toBe(true);});
 it('substitutes only dates in the outgoing notice without rewriting the source',()=>{const source={...fields,startDate:new Date(fields.startDate),endDate:new Date(fields.endDate)},before=JSON.stringify(source);expect(service.publicMessage(source).message).toBe('De 2095-02-07 a 2095-02-08');expect(JSON.stringify(source)).toBe(before);});
 it('strictly validates IDs and list filters',()=>{for(const value of ['01','7.1','0','2147483648',null])expect(()=>service.id(value)).toThrow();expect(service.id('7')).toBe(7);for(const query of [{from:'2095-02-30'},{status:['ACTIVE']},{unknown:1},{from:'2095-02-10',to:'2095-02-01'}])expect(()=>service.filters(query)).toThrow();expect(service.filters({})).toEqual({status:'',from:'',to:''});});
});
