import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-email-history-rules'),S=require('../src/services/emailHistoryService');
const row={id:2,to:'real50%_x@example.test',toEmail:'legacy@example.test',subject:'Literal 50%_x <script>',eventType:'MONTHLY_REPORT',type:null,mode:'MANUAL',status:'UNKNOWN',error:null,retryCount:0,lastRetryAt:null,createdAt:'2026-09-25T23:59:59.999Z'};
const f=R.filters({}),packet={ok:true,version:1,owner:'ADMIN:1',asOf:row.createdAt,timeZone:'UTC',filters:f,page:1,pageSize:25,total:1,totalPages:1,hasPrevious:false,hasNext:false,items:[row]};
describe('email history',()=>{
 it('validates real UTC dates, leap days, boundaries and unambiguous pagination',()=>{expect(R.filters({from:'2024-02-29',to:'2024-02-29'})).not.toBeNull();for(const q of [{from:'2026-02-29'},{to:'2026-13-01'},{from:'2026-09-26',to:'2026-09-25'},{page:'01'},{page:'0'},{page:'2147483647'},{pageSize:'101'},{page:['1','2']},{q:'\n'},{unknown:'x'}])expect(R.filters(q)).toBeNull();});
 it('matches both recorded recipient and type fields while preserving literal search',()=>{for(const q of [{recipient:'50%_x'},{recipient:'LEGACY@'},{type:'MONTHLY_REPORT'},{q:'50%_x'},{from:'2026-09-25',to:'2026-09-25'}])expect(R.matches(row,R.filters(q))).toBe(true);for(const q of [{recipient:'50Zxx'},{q:'50Zxx'},{to:'2026-09-24'},{status:'SENT'}])expect(R.matches(row,R.filters(q))).toBe(false);});
 it('accepts historical statuses without inventing delivery or exposing content',()=>{expect(R.row({...row,status:'HISTORICAL_CUSTOM'})).toBe(true);expect(R.row({...row,html:'private'})).toBe(false);expect(R.row({...row,text:'private'})).toBe(false);expect(R.row({...row,retryCount:-1})).toBe(false);expect(R.row({...row,lastRetryAt:'not-a-date'})).toBe(false);});
 it('rejects another owner, stale filters, missing rows and invalid totals',()=>{expect(R.packet(packet,f,'ADMIN:1')).toBe(true);for(const bad of [{owner:'ADMIN:2'},{items:[]},{total:2},{filters:{...f,q:'other'}},{page:2},{hasNext:true}])expect(R.packet({...packet,...bad},f,'ADMIN:1')).toBe(false);});
 it('requires stable descending date and ID order without duplicates',()=>{const larger={...packet,total:2,items:[row,{...row,id:1}]};expect(R.packet(larger,f,'ADMIN:1')).toBe(true);for(const items of [[row,row],[{...row,id:1},row],[row,{...row,id:1,createdAt:'2026-09-26T00:00:00.000Z'}]])expect(R.packet({...larger,items},f,'ADMIN:1')).toBe(false);});
 it('rejects unauthorized or invalid requests before touching storage',async()=>{const database={$transaction:()=>{throw Error('Unexpected lookup');}};await expect(S.read({id:1,role:'CLIENT'},{},database)).rejects.toMatchObject({statusCode:403});await expect(S.read({id:1,role:'ADMIN'},{recipient:['a','b']},database)).rejects.toMatchObject({statusCode:400});});
});
