import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),rules=require('../frontend/cw-equipment-time-review-rules'),time=require('../src/services/equipmentWorkTimeService'),writes=require('../src/services/fieldWriteRequestService'),clone=v=>JSON.parse(JSON.stringify(v));
const at=n=>new Date(Date.UTC(2008,0,1)+n).toISOString(),span=(a,b)=>({startAt:at(a),endAt:at(b)}),visit={id:1,poolId:2,clientId:3,technicianId:4,startAt:new Date(at(0)),endAt:new Date(at(10000))};
function fixture(){
  const old=time.create(span(0,1000),visit,'REGULAR'),row={id:9,planId:7,requestId:'96923c84-abcb-4f1e-aa9c-eb0a08fb56d4',fingerprint:'a'.repeat(64),completedAt:new Date(at(5000)),result:{completion:{workTime:old}}},receipts=[{requestId:row.requestId,response:row.result}],original=time.journal.original(row,receipts),record=time.create({intervals:[span(0,250),span(750,1000)]},visit,'REGULAR');
  const v={schema:1,basis:rules.basis,completionId:9,origin:{visitType:'REGULAR',visitId:1,poolId:2,clientId:3,technicianId:4},original,baseHash:writes.hash(original),previous:{headHash:null,action:'ORIGINAL',record:old},proposed:{action:'REPLACE',record},targetHash:'b'.repeat(64),sourceHash:'c'.repeat(64),beforeState:'RECORDED',afterState:'RECORDED',afterReasons:[],affectedShares:[]},preview={available:true,...v,hash:writes.hash(v)};
  const body={requestId:'ad8ff8c7-06ce-462e-827c-a63801ea2f5d',action:'REPLACE',workTime:rules.asInput(record),previewHash:preview.hash,reason:'Tempos e comprovativos conferidos',confirmed:true},revision={schema:1,id:body.requestId,owner:'ADMIN:5',completionId:9,reason:body.reason,createdAt:at(6000),preview},request=writes.context({id:5,role:'ADMIN'},rules.scope,9,body.requestId,Object.fromEntries(Object.entries(body).filter(([k])=>k!=='requestId'))),response={ok:true,applied:true,envelope:body,revision,revisionHash:writes.hash(revision),receipt:{...request,confirmedAt:at(6001)}};
  return {row,receipts,preview,body,response,request};
}
describe('administrative equipment time correction',()=>{
  it('uses the same strict positive millisecond input in Node and browser',()=>{const context={CWEquipmentMaterialReviewRules:require('../frontend/cw-equipment-material-review-rules')};vm.runInNewContext(fs.readFileSync(new URL('../frontend/cw-equipment-time-review-rules.js',import.meta.url),'utf8'),context);for(const v of [span(0,1),{intervals:[span(0,1),span(3,5)]}])expect(clone(context.CWEquipmentTimeReviewRules.input(v))).toEqual(time.parse(v));for(const v of [{intervals:[]},{intervals:[span(0,2),span(1,3)]},{intervals:Array(21).fill(span(0,1))},{...span(0,1),intervals:[span(0,1)]}])expect(()=>rules.input(v)).toThrow();});
  it('preserves the original and rejects proposed times beyond its execution or a substituted origin',async()=>{const f=fixture();expect(await rules.preview(f.preview,writes.hash)).toBe(f.preview);for(const mutate of [p=>p.proposed.record.intervals[1].endAt=at(6000),p=>p.proposed.record.durationMs=1000,p=>p.proposed.record.origin.technicianId=6,p=>p.afterState='REVIEW',p=>p.original.resultHash='d'.repeat(64)]){const p=clone(f.preview);mutate(p);p.hash=writes.hash(rules.facts(p));await expect(rules.preview(p,writes.hash)).rejects.toThrow();}});
  it('binds confirmation to the administrator, full intervals, original request and timestamp',async()=>{const f=fixture();expect(await rules.response(f.response,f.body,'ADMIN:5',9,writes.hash)).toBe(f.response);for(const mutate of [r=>r.revision.preview.proposed.record.intervals.reverse(),r=>r.revision.owner='ADMIN:6',r=>r.receipt.confirmedAt=at(5999),r=>r.envelope.reason='Outro motivo']){const r=clone(f.response);mutate(r);await expect(rules.response(r,f.body,'ADMIN:5',9,writes.hash)).rejects.toThrow();}});
  it('keeps invalid historical chains unavailable instead of selecting an unproved latest row',async()=>{const f=fixture(),event={...f.request,response:f.response},db={fieldWriteRequest:{findMany:async()=>[event]}};let state=(await time.journal.read(db,[f.row],f.receipts)).get(9);expect(state.valid).toBe(true);expect(state.record.durationMs).toBe(500);event.payloadHash='f'.repeat(64);expect((await time.journal.read(db,[f.row],f.receipts)).get(9).valid).toBe(false);event.payloadHash=f.request.payloadHash;const changed={...f.row,fingerprint:'e'.repeat(64)};expect((await time.journal.read(db,[changed],f.receipts)).get(9).valid).toBe(false);});
  it('links a new financial proof to the exact administrative revision and work record',async()=>{const f=fixture(),p={completionId:9,workTime:f.preview.proposed.record,workTimeRevision:{revision:f.response.revision,hash:f.response.revisionHash}};expect(await rules.share(p,writes.hash)).toBe(p);await expect(rules.share({...p,completionId:10},writes.hash)).rejects.toThrow();await expect(rules.share({...p,workTime:f.preview.previous.record},writes.hash)).rejects.toThrow();});
  it('allows explicit withdrawal while rejecting fictitious zero-time records or silent reassignment',async()=>{const f=fixture(),p=clone(f.preview);p.proposed={action:'WITHDRAW',record:null};p.afterState='WITHDRAWN';p.hash=writes.hash(rules.facts(p));expect(await rules.preview(p,writes.hash)).toBe(p);p.previous.record=null;p.hash=writes.hash(rules.facts(p));await expect(rules.preview(p,writes.hash)).rejects.toThrow();expect(()=>rules.input(span(0,0))).toThrow();});
});
