import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-extra-history-rules'),copy=require('../frontend/cw-extra-history-copy');
const record={id:2,clientId:3,clientName:'Original',poolId:4,poolName:'Pool',poolClientId:5,clientReview:'POOL_CHANGED',billed:true,billedAt:'2097-11-08T00:00:00.000Z',scheduledAt:'2097-11-07T12:34:56.789Z',status:'DONE',billingMode:'LEGACY',priceRaw:'12.34',priceCents:1234,notes:null};
const selection=R.filters({}),packet=extras=>({ok:true,version:1,owner:'ADMIN:1',asOf:'2097-11-08T01:00:00.000Z',timeZone:'UTC',basis:'EXTRA_VISIT_BILLED_MARKER',filters:selection,pageSize:50,total:extras.length,pages:1,hasPrevious:false,hasNext:false,extras});
describe('original extra visit history',()=>{
 it('rejects ambiguous filters and impossible days before querying',()=>{for(const value of [{clientId:'01'},{poolId:'-1'},{q:['a']},{q:'x\n'},{page:'0'},{page:'42949674'},{from:'2097-02-29'},{from:'2097-02-03',to:'2097-02-02'},{unknown:'x'}])expect(R.filters(value)).toBeNull();expect(R.filters({q:' text ',poolId:'5'})).toEqual({...selection,q:'text',poolId:5});});
 it('projects exact decimal cents without rounding tiny or sub-cent values',()=>{for(const [value,cents] of [['12.34',1234],['0',0],['-2.25',-225],['10000000',1000000000]])expect(R.cents(value)).toBe(cents);for(const value of ['1.005','1e-12','1e-7','1e+21','NaN','Infinity','-Infinity','9007199254740992','01','12.340'])expect(R.cents(value)).toBeNull();});
 it('keeps original customer, missing relations and null marking dates distinct',()=>{expect(R.row(record)).toBe(true);expect(R.row({...record,clientReview:'RECORDED'})).toBe(false);const orphan={...record,id:1,clientId:null,clientName:null,poolId:null,poolName:null,poolClientId:null,clientReview:'MISSING',billedAt:null};expect(R.packet(packet([record,orphan]),selection,'ADMIN:1')).toBe(true);expect(R.packet(packet([orphan,record]),selection,'ADMIN:1')).toBe(false);expect(R.row({...orphan,clientName:'Inferred'})).toBe(false);});
 it('refuses mismatched owner, selection, count, order, duplicate or rounded source',()=>{const p=packet([record,{...record,id:1}]);expect(R.packet(p,selection,'ADMIN:1')).toBe(true);for(const change of [{owner:'ADMIN:2'},{filters:{...selection,clientId:5}},{total:3},{extras:[record,record]},{extras:[{...record,id:1},record]},{extras:[{...record,priceRaw:'1.005',priceCents:101},{...record,id:1}]}])expect(R.packet({...p,...change},selection,'ADMIN:1')).toBe(false);});
 it('covers all five languages with matching placeholders and source warnings',()=>{expect(Object.keys(copy)).toEqual(['pt','en','fr','es','de']);for(const c of Object.values(copy)){expect(Object.keys(c)).toEqual(Object.keys(copy.pt));for(const key of Object.keys(c)){expect(c[key]?.trim(),key).toBeTruthy();expect(c[key].match(/\{\w+\}/g)).toEqual(copy.pt[key].match(/\{\w+\}/g));}for(const key of ['basis','missingClient','changedClient','missingDate','invalidAmount','session'])expect(c[key]).toBeTruthy();}});
});
