import { describe, it, expect } from 'vitest';
const fs=require('node:fs'),vm=require('node:vm');
function harness() {
  const data=new Map(),session={owner:'TECH:7',technicianId:7,token:'header.'+Buffer.from(JSON.stringify({role:'TECHNICIAN'})).toString('base64')+'.signature'};let active=true;
  const window={CWFieldWriteStore:{session:()=>session,same:captured=>active&&captured===session}};
  vm.runInNewContext(fs.readFileSync('frontend/cw-field-route-cache.js','utf8'),{window,atob:value=>Buffer.from(value,'base64').toString(),localStorage:{getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)}});
  const cache=window.CWFieldRouteCache,context=cache.scope(),visit={id:9,visitType:'REGULAR',technician:{id:7},status:'PLANNED'},value=cache.fromResponse({ok:true,complete:true,date:context.day,technicianId:7,total:1,visits:[visit]},context);
  return {cache,context,value,visit,data,session,change:()=>{active=false;}};
}
describe('Modern route cache account/day contract',()=>{
  it('separates typed identities, roles and days without storing credentials',()=>{const h=harness();const key=h.cache.key(h.context);for(const next of [{...h.context,session:{...h.session,owner:'USER:7:TECH:7'}},{...h.context,role:'TEAM_LEADER'},{...h.context,day:'2000-01-01'}])expect(h.cache.key(next)).not.toBe(key);h.cache.save(h.value,h.context);expect(h.cache.read(h.context)).toEqual(h.value);expect([...h.data.values()].join('')).not.toContain(h.session.token);});
  it.each([{owner:'TECH:8'},{role:'TEAM_LEADER'},{day:'2000-01-01'},{technicianId:8},{visits:[{id:9,visitType:'REGULAR',technician:{id:8},status:'PLANNED'}]},{visits:[{id:9,visitType:'REGULAR',technician:{id:7},status:'PLANNED',assistSource:'tomorrow'}]}])('preserves and refuses a mismatching cache %j',changes=>{const h=harness(),key=h.cache.key(h.context),raw=JSON.stringify({...h.value,...changes});h.data.set(key,raw);expect(()=>h.cache.read(h.context)).toThrow();expect(()=>h.cache.save(h.value,h.context)).toThrow();expect(h.data.get(key)).toBe(raw);});
  it('keeps regular/extra visits with the same numeric id separate and rejects duplicates',()=>{const h=harness(),extra={...h.visit,visitType:'EXTRA'};expect(h.cache.validate({...h.value,visits:[h.visit,extra]},h.context).visits).toHaveLength(2);expect(()=>h.cache.validate({...h.value,visits:[h.visit,h.visit]},h.context)).toThrow();});
  it('does not import or erase numeric histories',()=>{const h=harness(),raw='{"private":"historic"}',key='cwFieldRoute:7';h.data.set(key,raw);expect(()=>h.cache.read(h.context)).toThrow(/antiga/);h.cache.save(h.value,h.context);expect(h.data.get(key)).toBe(raw);});
  it('preserves corruption and refuses an expired context before writes',()=>{const h=harness(),key=h.cache.key(h.context);h.data.set(key,'{broken');expect(()=>h.cache.save(h.value,h.context)).toThrow(/ilegível/);expect(h.data.get(key)).toBe('{broken');h.change();expect(()=>h.cache.save(h.value,h.context)).toThrow(/sessão/);});
  it('requires response account/day/count and leaves stored data intact on a wrong reply',()=>{const h=harness();h.cache.save(h.value,h.context);for(const changes of [{technicianId:8},{date:'2000-01-01'},{total:2},{complete:false},{complete:undefined},{ok:false}])expect(()=>h.cache.fromResponse({ok:true,complete:true,date:h.context.day,technicianId:7,total:1,visits:[h.visit],...changes},h.context)).toThrow();expect(h.cache.read(h.context)).toEqual(h.value);});
  it('local changes preserve the server consultation time and exclude assistance/tomorrow additions',()=>{const h=harness();h.cache.save(h.value,h.context);const result=h.cache.update(h.value,[{...h.visit,status:'IN_PROGRESS'},{...h.visit,id:10,assistSource:'tomorrow'}],h.context);expect(result.serverConfirmedAt).toBe(h.value.serverConfirmedAt);expect(result.visits).toHaveLength(1);expect(result.visits[0].status).toBe('IN_PROGRESS');});
});
