import {describe,it,expect} from 'vitest';
import fs from 'node:fs';
import vm from 'node:vm';
const P=require('../frontend/cw-field-guide-projection'),S=require('../src/services/fieldGuideReadService');
describe('field guide read boundaries',()=>{
 it('keeps operational fields and removes contact/cost/credential fields at every relation',()=>{const tech={id:1,name:'T',email:'SECRET',pin:'SECRET',hourlyCost:12},vehicle={id:2,plate:'AA',notes:'SECRET',cost:12},guide={id:3,vehicleId:2,vehicle,notes:' Exact note ',workGuides:[{id:4,technician:tech,vehicle,guide:{id:3,vehicle},items:[{id:8,name:'Salt',unit:' KG ',quantity:-1,cost:33}]}]},result=P.transport(guide);expect(JSON.stringify(result)).not.toMatch(/SECRET|hourlyCost|email|cost/);expect(result.notes).toBe(' Exact note ');expect(result.workGuides[0].items[0]).toMatchObject({name:'Salt',unit:' KG ',quantity:-1});expect(P.work({technician:tech,startKm:0,endKm:null})).toMatchObject({startKm:0,endKm:null,technician:{id:1,name:'T'}});});
 it('never forwards arbitrary JSON metadata in notes or official pointers',()=>{const notes=JSON.stringify({cwGuideMovement:true,userNotes:' Exact ',location:' Site ',readings:{ph:0,cost:300,email:'SECRET'},cost:44,private:{pin:'SECRET'}});expect(P.metadata(notes)).toMatchObject({userNotes:' Exact ',location:' Site ',readings:{ph:0}});expect(JSON.stringify(P.movement({id:1,notes}))).not.toMatch(/SECRET|cost|private/);expect(P.maintenance({id:1,notes:'{"cost":44,"pin":"SECRET"}',cost:50})).toEqual({id:1,notes:''});expect(P.document({url:'/api/transport-guide-documents/current/3',originalName:' Exact.pdf ',uploadedBy:'SECRET',extra:{cost:2}})).toEqual({url:'/api/transport-guide-documents/current/3',originalName:' Exact.pdf '});});
 it.each(['/uploads/old.pdf','https://example.test/a.pdf','javascript:alert(1)','/api/transport-guide-documents/current/03'])('rejects unsafe pointer %s',url=>expect(()=>P.document({url})).toThrow());
 it('rejects nested private data masquerading as scalar fields',()=>{expect(()=>P.document({url:'/api/transport-guide-documents/current/3',originalName:{email:'SECRET'}})).toThrow();expect(()=>P.item({id:1,quantity:{cost:33}})).toThrow();expect(()=>P.item({id:1,quantity:NaN})).toThrow();});
 it('binds User and PIN field identities separately and refuses unlinked User identities',()=>{expect(S.owner({id:7,role:'TECHNICIAN'})).toBe('TECH:7');expect(S.owner({id:8,technicianId:7,principalType:'USER',role:'TEAM_LEADER'})).toBe('USER:8:TECH:7');for(const actor of [{id:1,role:'ADMIN'},{id:1,role:'CLIENT'},{id:1,role:'TECHNICIAN',principalType:'USER'}])expect(()=>S.owner(actor)).toThrow();});
 it('rejects coerced, duplicate, unbounded and ignored filters',()=>{expect(S.query('movements',{vehicleId:'2',limit:'25',offset:'0',workGuideId:'3'})).toMatchObject({vehicleId:2,limit:25,offset:0,workGuideId:3});for(const q of [{vehicleId:'01'},{technicianId:['1','2']},{limit:'201'},{offset:'-1'},{limit:'1e2'},{visitId:'1'},{q:'ignored'}])expect(()=>S.query('movements',q)).toThrow();expect(()=>S.query('stock',{limit:'25'})).toThrow();});
 it('refuses another technicians work in live and saved field documents',()=>{const context={window:{CWFieldWriteStore:{same:()=>true},CWFieldRouteCache:{today:()=> '2026-09-26'},CWFieldGuideProjection:P},localStorage:{getItem:()=>null},atob:s=>Buffer.from(s,'base64').toString(),Date};vm.runInNewContext(fs.readFileSync(new URL('../frontend/cw-field-documents.js',import.meta.url),'utf8'),context);const api=context.window.CWFieldDocuments,scope={session:{technicianId:7,owner:'TECH:7'},role:'TECHNICIAN',vehicleId:2,day:'2026-09-26'},data={ok:true,workGuide:{id:3,vehicleId:2,technicianId:7,vehicle:{id:2}},stock:[],movements:[],transportGuideDocument:null,missingTransportGuide:true};expect(api.validateData('work',data,scope)).toBe(data);expect(()=>api.validateData('work',{...data,workGuide:{...data.workGuide,technicianId:8}},scope)).toThrow();expect(()=>api.validateData('work',{...data,movements:[{workGuideId:3,vehicleId:2,technicianId:8}]},scope)).toThrow();expect(api.key(scope)).toMatch(/^cwFieldDocuments:v3:/);expect(()=>api.validate({v:2,owner:'TECH:7',role:'TECHNICIAN',technicianId:7,vehicleId:2,day:scope.day,sections:{}},scope)).toThrow();});
});
