import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),R=require('../frontend/cw-fleet-management-rules'),fields={plate:' aa-00-aa ',name:' Van ',brand:' Make ',model:' Model ',year:2024,currentKm:0,notes:' first\nsecond ',status:'ACTIVE'},owner='ADMIN:2',requestId='01234567-89ab-4def-8123-456789abcdef';
describe('reviewed fleet management',()=>{
 for(const wrapper of ['direct','data','body'])it('accepts the '+wrapper+' API client response while distinguishing HTTP status from CONFIRMED',async()=>{
  for(const [module,entity,input]of [['create-reviewed-technician','technician',{name:'QA',pin:'001234'}],['create-reviewed-vehicle','vehicle',{plate:'AA-00-AA'}]]){
   const create=require('../scripts/helpers/'+module),seen=[];
   const call=async(method,url,body)=>{seen.push({method,url,body});const packet=url.endsWith('/review')?{requestId,reviewToken:'signed-review'}:{status:'CONFIRMED',result:{[entity]:{id:42}}};return wrapper==='direct'?packet:{status:200,[wrapper]:packet};};
   expect(await create(call,input)).toEqual({id:42});expect(seen).toHaveLength(2);expect(seen[1].body.requestId).toBe(requestId);expect(seen[1].body.reviewToken).toBe('signed-review');
   let calls=0;await expect(create(async()=>{calls++;return {status:403,body:{ok:false}};},input)).rejects.toThrow(/review failed: 403/);expect(calls).toBe(1);
  }
 });
 it('normalizes explicit identity fields while retaining zero kilometres and multiline notes',()=>{expect(R.fields('CREATE',fields)).toEqual({...fields,plate:'AA-00-AA',name:'Van',brand:'Make',model:'Model',notes:'first\nsecond'});});
 it('keeps unknown optional numbers distinct from zero',()=>{expect(R.fields('CREATE',{...fields,year:null,currentKm:null})).toMatchObject({year:null,currentKm:null});for(const value of ['',false,{},'0'])expect(R.fields('CREATE',{...fields,currentKm:value})).toBeNull();});
 it('refuses empty plates, invalid dates, negative/nonfinite distance and unsupported statuses',()=>{for(const patch of [{plate:' '},{plate:'x\ny'},{year:0},{year:2024.5},{year:2201},{currentKm:-1},{currentKm:Infinity},{currentKm:NaN},{status:'ARCHIVED'}])expect(R.fields('CREATE',{...fields,...patch})).toBeNull();});
 it('requires full editable fields and separates state from identity edits',()=>{const {status,...edit}=fields;expect(R.fields('EDIT',edit)).not.toBeNull();expect(R.fields('EDIT',fields)).toBeNull();expect(R.fields('EDIT',{name:'Only'})).toBeNull();});
 it('requires an explicit operating status when restoring',()=>{expect(R.fields('RESTORE',{})).toBeNull();expect(R.fields('RESTORE',{status:'MAINTENANCE'})).toEqual({status:'MAINTENANCE'});expect(R.fields('RESTORE',{status:'ARCHIVED'})).toBeNull();});
 it('never lets archival commands rewrite operational fields',()=>{expect(R.fields('ARCHIVE',{})).toEqual({});expect(R.fields('ARCHIVE',{currentKm:0})).toBeNull();expect(R.fields('STATUS',{status:'INACTIVE'})).toEqual({status:'INACTIVE'});});
 it('rejects relations, timestamps and arbitrary state assignment',()=>{for(const key of ['id','active','archiveStatus','deletedAt','assignedTechnicians','workGuides','createdAt'])expect(R.fields('CREATE',{...fields,[key]:1})).toBeNull();});
 it('bounds paging and refuses alternative ID spellings',()=>{expect(R.query({page:'2',active:'all',q:' Van '})).toEqual({page:2,active:'all',q:'Van'});for(const q of [{page:'01'},{page:'0'},{page:'1000001'},{active:'yes'},{q:['x']}])expect(R.query(q)).toBeNull();for(const id of ['01','1.0','1e0','-1','2147483648'])expect(R.id(id)).toBeNull();});
 it('persists only a reference owned by this account and operation',()=>{const p={version:1,owner,operation:'ARCHIVE',vehicleId:5,requestId};expect(R.pending(JSON.stringify(p),owner)).toEqual(p);for(const patch of [{owner:'ADMIN:3'},{vehicleId:null},{fields:{}},{reviewToken:'proof'},{operation:'DELETE'}])expect(R.pending(JSON.stringify({...p,...patch}),owner)).toBe(false);});
 it('rejects partial or duplicated pages instead of implying an empty or complete list',()=>{const row={id:1,plate:'A',active:true,updatedAt:'2026-09-25T16:00:00.000Z'},p={ok:true,version:1,owner,asOf:row.updatedAt,page:1,size:25,total:1,vehicles:[row]};expect(R.listPacket(p,owner,1)).toBe(true);expect(R.listPacket({...p,total:2},owner,1)).toBe(false);expect(R.listPacket({...p,total:2,vehicles:[row,row]},owner,1)).toBe(false);expect(R.listPacket(p,'ADMIN:3',1)).toBe(false);});
 it('rejects a receipt for another vehicle or operation',()=>{const p={version:1,owner,operation:'EDIT',vehicleId:5,requestId},packet={ok:true,version:1,owner,asOf:'2026-09-25T16:00:00.000Z',requestId,status:'CONFIRMED',result:{operation:'EDIT',vehicleId:5,auditId:1,vehicle:{id:6,plate:'Other',active:true,updatedAt:'2026-09-25T16:00:00.000Z'},receipt:{owner,requestId,confirmedAt:'2026-09-25T16:00:00.000Z'}}};expect(R.resultPacket(packet,owner,p)).toBe(false);packet.result.vehicle.id=5;expect(R.resultPacket(packet,owner,p)).toBe(true);});
 it('provides identical own-copy keys in five languages',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../frontend/cw-fleet-management-copy.js',import.meta.url),'utf8'),context);const copy=context.window.CWFleetManagementCopy;expect(Object.keys(copy)).toEqual(['pt','en','fr','es','de']);for(const language of Object.values(copy)){expect(Object.keys(language).sort()).toEqual(Object.keys(copy.pt).sort());expect(Object.values(language).every(s=>typeof s==='string'&&s.length>0)).toBe(true);}});
});
