import {describe,it,expect} from 'vitest';
import fs from 'node:fs';
import vm from 'node:vm';
const R=require('../frontend/cw-fleet-history-rules'),at='2026-03-29T01:00:00.000Z',owner='ADMIN:7';
const record={id:8,vehicleId:2,vehicle:{id:2,plate:'AA',active:false,deletedAt:at},createdAt:at,updatedAt:at,closedAt:null,status:'HISTORIC',isDraft:true,itemCount:1,workCount:0,codeAT:null,validFrom:at,validUntil:null,document:{state:'MISSING',url:null,name:null}};
const packet=(raw={},rows=[record])=>({ok:true,version:1,owner,asOf:at,kind:'transport',page:1,size:25,total:rows.length,maxId:8,query:R.query(raw),rows});
describe('fleet history read contracts',()=>{
 it('normalizes strict filters and retains zero as an explicit empty insertion boundary',()=>{expect(R.query({q:' Salt ',maxId:'0'})).toMatchObject({kind:'transport',page:1,q:'Salt',maxId:0});for(const raw of [{page:'01'},{page:'1e0'},{recordId:8},{vehicleId:'0'},{maxId:null},{kind:'work',workGuideId:'8'},{technicianId:'1'},{unexpected:'1'},{q:['a','b']},{from:'2026-02-30'},{from:'2026-03-30',to:'2026-03-29'},{to:'2200-01-01'}])expect(R.query(raw)).toBeNull();});
 it('uses inclusive Lisbon dates across spring and autumn daylight saving changes',()=>{const spring=R.bounds('2026-03-29','2026-03-29'),autumn=R.bounds('2026-10-25','2026-10-25');expect(spring).toEqual({from:'2026-03-29T00:00:00.000Z',to:'2026-03-29T23:00:00.000Z'});expect((Date.parse(spring.to)-Date.parse(spring.from))/3600000).toBe(23);expect((Date.parse(autumn.to)-Date.parse(autumn.from))/3600000).toBe(25);expect(R.bounds('2199-12-31','2199-12-31').to).toBe('2200-01-01T00:00:00.000Z');});
 it('rejects owner, query, row count, insertion limit and identity mismatches',()=>{const p=packet();expect(R.listPacket(p,owner,{})).toBe(true);for(const patch of [{owner:'ADMIN:8'},{total:2},{maxId:7},{size:20},{query:R.query({q:'other'})},{rows:[{...record,vehicle:{...record.vehicle,id:3}}]},{rows:[{...record,itemCount:null}]}])expect(R.listPacket({...p,...patch},owner,{})).toBe(false);});
 it('rejects duplicate and unordered pages and rows outside the requested date',()=>{const second={...record,id:7};expect(R.listPacket(packet({},[record,second]),owner,{})).toBe(true);for(const rows of [[record,record],[second,record]])expect(R.listPacket(packet({},rows),owner,{})).toBe(false);const raw={from:'2026-03-30'};expect(R.listPacket(packet(raw),owner,raw)).toBe(false);});
 it('accepts missing historical relations and exact signed quantities without coercion',()=>{const movement={id:8,vehicleId:99,vehicle:null,technicianId:98,technician:null,workGuideId:null,transportGuideId:null,visitId:null,extraVisitId:null,itemName:' Exact <img> ',itemType:null,unit:' KG ',quantity:-0.000001,movementType:'ADJUSTMENT',source:null,createdAt:at};expect(R.row('movement',movement)).toBe(true);for(const quantity of ['-1',NaN,Infinity])expect(R.row('movement',{...movement,quantity})).toBe(false);expect(R.row('movement',{...movement,technician:{id:97,name:'Wrong'}})).toBe(false);});
 it('accepts only a current protected document URL bound to the transport record',()=>{expect(R.row('transport',{...record,document:{state:'RECORDED',url:'/api/transport-guide-documents/current/8',name:'Exact <img>.pdf'}})).toBe(true);for(const url of ['https://elsewhere.test','/uploads/a.pdf','/api/transport-guide-documents/current/9'])expect(R.row('transport',{...record,document:{state:'RECORDED',url,name:null}})).toBe(false);});
 it('requires complete, ordered and correctly associated detail materials',()=>{const item={id:5,guideId:8,name:'Same',type:null,unit:'KG',quantity:-1},p={ok:true,version:1,owner,asOf:at,kind:'transport',id:8,record:{...record,notes:' Exact\nnotes ',origin:null,destination:null,inheritedFromId:null},page:1,size:25,total:1,items:[item]};expect(R.detailPacket(p,owner,'transport',8,1)).toBe(true);for(const patch of [{total:2},{items:[]},{items:[{...item,guideId:9}]},{items:[{...item,quantity:'1'}]},{record:{...p.record,notes:undefined}}])expect(R.detailPacket({...p,...patch},owner,'transport',8,1)).toBe(false);expect(R.detailPacket({...p,total:2,record:{...p.record,itemCount:2},items:[{...item,id:6},item]},owner,'transport',8,1)).toBe(false);});
 it('keeps zero mileage distinct from unknown and accepts historic status values',()=>{const work={...record,technicianId:null,technician:null,guideId:null,transport:null,startKm:0,endKm:null};expect(R.row('work',work)).toBe(true);expect(R.row('work',{...work,startKm:'0'})).toBe(false);});
 it('provides complete copy in five languages',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../frontend/cw-fleet-history-copy.js',import.meta.url),'utf8'),context);const copy=context.window.CWFleetHistoryCopy;expect(Object.keys(copy)).toEqual(['pt','en','fr','es','de']);for(const value of Object.values(copy)){expect(Object.keys(value).sort()).toEqual(Object.keys(copy.pt).sort());expect(Object.values(value).every(v=>typeof v==='string'&&v.length)).toBe(true);}});
});
