import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),R=require('../frontend/cw-live-map-rules'),S=require('../src/services/liveMapService');
const now=Date.parse('2026-09-25T12:00:00.000Z'),location={id:2,latitude:0,longitude:0,updatedAt:new Date(now).toISOString()},row={key:'TECHNICIAN:1',kind:'TECHNICIAN',id:1,name:'Literal 50%_ <script>',location,state:'RECENT'};
const f=R.filters({}),packet={ok:true,version:1,owner:'ADMIN:1',asOf:new Date(now).toISOString(),timeZone:'UTC',basis:'LATEST_EXPLICIT_IDENTITY',freshMs:900000,filters:f,pageSize:50,total:1,pages:1,hasPrevious:false,hasNext:false,totals:R.totals([row]),rows:[row]};
describe('live map positions',()=>{
 it('keeps zero and global coordinates without coercing missing values',()=>{expect(R.point(location)).toEqual([0,0]);expect(R.point({latitude:-90,longitude:180})).toEqual([-90,180]);for(const p of [{latitude:null,longitude:0},{latitude:'37',longitude:0},{latitude:91,longitude:0},{latitude:0,longitude:181},{latitude:NaN,longitude:0}])expect(R.point(p)).toBeNull();});
 it('classifies exact freshness boundaries, future dates and unknown positions',()=>{expect(R.positionState(location,now)).toBe('RECENT');expect(R.positionState(location,now+900000)).toBe('RECENT');expect(R.positionState(location,now+900001)).toBe('STALE');expect(R.positionState(location,now-1)).toBe('FUTURE');expect(R.positionState(null,now)).toBe('MISSING');expect(R.positionState({...location,latitude:91},now)).toBe('INVALID');});
 it('uses an explicit source identity and never a profile coordinate fallback',()=>{const person={id:1,name:'A',latitude:37,longitude:-8};expect(S.project('TECHNICIAN',person,null,now)).toMatchObject({key:'TECHNICIAN:1',location:null,state:'MISSING'});expect(S.project('USER',person,{...location,updatedAt:new Date(now)},now)).toMatchObject({key:'USER:1',state:'RECENT'});});
 it('keeps searches literal and rejects ambiguous filters',()=>{for(const q of [{page:'01'},{page:'0'},{page:'42949674'},{state:'AVAILABLE'},{q:['a','b']},{other:'x'}])expect(R.filters(q)).toBeNull();expect(R.matches(row,R.filters({q:'50%_'}))).toBe(true);expect(R.matches(row,R.filters({q:'50Zx'}))).toBe(false);});
 it('accepts same numeric IDs in different namespaces but refuses duplicates',()=>{const user={...row,kind:'USER',key:'USER:1'},rows=[row,user],body={...packet,total:2,rows,totals:R.totals(rows)};expect(R.packet(body,f,'ADMIN:1')).toBe(true);expect(R.packet({...body,rows:[row,row]},f,'ADMIN:1')).toBe(false);expect(R.packet({...body,rows:[user,row]},f,'ADMIN:1')).toBe(false);});
 it('refuses mixed owner, missing rows, invented freshness and inconsistent totals',()=>{expect(R.packet(packet,f,'ADMIN:1')).toBe(true);for(const change of [{owner:'ADMIN:2'},{rows:[]},{total:2},{rows:[{...row,state:'STALE'}]},{totals:{...packet.totals,STALE:1}},{freshMs:999999}])expect(R.packet({...packet,...change},f,'ADMIN:1')).toBe(false);});
 it('rejects invalid access and filters before reading the database',async()=>{const db={$transaction:()=>{throw Error('Unexpected lookup');}};await expect(S.read({id:1,role:'TECHNICIAN'},{},db)).rejects.toMatchObject({statusCode:403});await expect(S.read({id:1,role:'ADMIN'},{page:['1','2']},db)).rejects.toMatchObject({statusCode:400});});
});
