import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const R=require('../frontend/cw-payment-ledger-rules');
describe('administrative payment history review',()=>{
  it('rejects ambiguous IDs, duplicate query values and impossible dates before any lookup',()=>{for(const query of [{clientId:'01'},{clientId:'-1'},{clientId:'2147483648'},{clientId:['1','2']},{from:'2097-02-29'},{from:'2097-12-01',to:'2097-11-30'},{page:'0'},{page:'1.1'},{page:'42949674'},{q:'x'.repeat(121)},{method:'x\n'},{unknown:'value'}])expect(R.filters(query)).toBeNull();});
  it('keeps customer selection explicit and accepts literal historical methods',()=>{expect(R.filters({clientId:'2147483647',method:'historical %_ method',q:'  CW-000123  '})).toEqual({q:'CW-000123',clientId:2147483647,method:'historical %_ method',from:'',to:'',page:1});});
  it('preserves ordinary and negative records without calling them cash totals',()=>{expect(R.money('12.34',1234)).toEqual({amountCents:1234,amountReview:'MATCH'});expect(R.money('-2.25',-225)).toEqual({amountCents:-225,amountReview:'MATCH'});});
  it('exposes differing amounts and historical default cents instead of selecting a replacement',()=>{expect(R.money('12.34',0)).toEqual({amountCents:1234,amountReview:'LEGACY_ZERO_CENTS'});expect(R.money('12.34',1235)).toEqual({amountCents:1234,amountReview:'CONFLICT'});expect(R.money('0',1234)).toEqual({amountCents:0,amountReview:'CONFLICT'});});
  it('does not round sub-cent or unrepresentable historical values into a confirmed amount',()=>{for(const value of ['1.005','NaN','Infinity','-Infinity','9007199254740992','not a number'])expect(R.money(value,0)).toEqual({amountCents:null,amountReview:'INVALID_AMOUNT'});});
  it('refuses a different owner, filter, count or row order in a confirmed page',()=>{const filters=R.filters({}),row={id:2,invoiceId:1,clientId:1,clientName:'Original',documentReference:null,documentStatus:'PAID',monthRef:null,method:'CASH',notes:null,paidAt:'2097-11-08T00:00:00.000Z',internalCredit:false,amountRaw:'12.34',storedAmountCents:1234,...R.money('12.34',1234)},data={ok:true,version:1,owner:'ADMIN:1',asOf:'2097-11-08T01:00:00.000Z',timeZone:'UTC',basis:'PAYMENT_RECORDS_INCLUDING_INTERNAL_CREDIT',filters,pageSize:50,total:2,pages:1,hasPrevious:false,hasNext:false,payments:[row,{...row,id:1}]};expect(R.packet(data,filters,'ADMIN:1')).toBe(true);for(const changed of [{owner:'ADMIN:2'},{filters:{...filters,clientId:2}},{total:3},{payments:[{...row,id:1},row]},{payments:[row,{...row}]}])expect(R.packet({...data,...changed},filters,'ADMIN:1')).toBe(false);});
});
