import {describe,it,expect} from 'vitest';
const D=require('../frontend/cw-pool-calculator-drafts'),R=require('../frontend/cw-pool-calculator-rules');
const review=id=>{const pool={id,clientId:1,client:{id:1,name:'Client'},name:'Pool '+id,type:'RECTANGULAR',volumeM3:75};return {ok:true,scope:R.scope,poolId:id,version:'pool-calculator-v2:'+'a'.repeat(64),pool,profile:null,fields:R.form(pool,null)};};
function memory(){const values=new Map();return {values,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};}
describe('Calculator drafts',()=>{
 it('partitions pools and accounts without mutating values or reviewed versions',()=>{const storage=memory(),one=D.open('ADMIN:1',storage),two=D.open('ADMIN:2',storage),a=review(3),b=review(4);one.save(a,{...a.fields,notes:'One',phCurrent:'0',averageDepthM:'1.06634'});one.save(b,{...b.fields,notes:'Other pool'});two.save(a,{...a.fields,notes:'Other owner'});expect(one.read(3).fields.notes).toBe('One');expect(one.read(4).fields.notes).toBe('Other pool');expect(two.read(3).fields.notes).toBe('Other owner');expect(one.read(3).fields.phCurrent).toBe('0');expect(one.read(3).review).toEqual(a);});
 it('preserves malformed and unattributed bytes and rejects replacement',()=>{for(const raw of ['{broken',JSON.stringify({schema:1,owner:'ADMIN:2',poolId:3,review:review(3),fields:review(3).fields})]){const storage=memory(),store=D.open('ADMIN:1',storage),key=store.key(3);storage.setItem(key,raw);expect(()=>store.read(3)).toThrow();expect(()=>store.save(review(3),review(3).fields)).toThrow();expect(storage.getItem(key)).toBe(raw);}});
 it('refuses ignored writes and an original changed outside the opened form',()=>{const storage=memory(),store=D.open('ADMIN:1',storage),r=review(3);store.read(3);storage.setItem=()=>{};expect(()=>store.save(r,r.fields)).toThrow();storage.values.set(store.key(3),'changed');expect(()=>store.save(r,r.fields)).toThrow();expect(storage.getItem(store.key(3))).toBe('changed');});
 it('finishes only the exact fields and version transferred to the confirmed request',()=>{const storage=memory(),store=D.open('ADMIN:1',storage),r=review(3),fields={...r.fields,notes:'First'},record={poolId:3,command:{expectedVersion:r.version,fields}};store.save(r,fields);store.finish({...record,command:{...record.command,fields:{...fields,notes:'Other'}}});expect(store.read(3)).not.toBeNull();store.finish({...record,command:{...record.command,expectedVersion:'pool-calculator-v2:'+'b'.repeat(64)}});expect(store.read(3)).not.toBeNull();store.finish(record);expect(store.read(3)).toBeNull();});
 it('verifies deletion and conserves a draft when removing it was ignored',()=>{const storage=memory(),store=D.open('ADMIN:1',storage),r=review(3);store.save(r,r.fields);storage.removeItem=()=>{};expect(()=>store.discard(3)).toThrow();expect(store.read(3).fields).toEqual(r.fields);});
});
