import {describe,it,expect} from 'vitest';
const R=require('../frontend/cw-pool-calculator-rules');
describe('Reviewed calculator preservation',()=>{
 const pool={id:7,clientId:9,client:{id:9,name:'Client'},name:'Pool',type:'CIRCULAR',volumeM3:80};
 const profile={id:3,poolId:7,...Object.fromEntries(R.modelKeys.map(key=>[key,R.numbers.includes(key)?null:key==='covered'?false:null])),shape:'CIRCULAR',poolLoad:'HISTORIC',volumeM3:75,cop:0,lastResultJson:{chemistry:{phCurrent:0,targetPh:7.4,orpCurrentMv:620}}};
 const review={ok:true,scope:R.scope,poolId:7,version:'pool-calculator-v2:'+'a'.repeat(64),pool,profile,fields:R.form(pool,profile)};
 it('preserves untouched nulls, zero, original volume and historical options',()=>{expect(R.state(review)).toBe(true);const fields={...review.fields,notes:'Changed'};expect(R.patch(pool,profile,fields)).toEqual({changed:['notes'],profile:{notes:'Changed'}});expect(fields.volumeM3).toBe('75');expect(fields.cop).toBe('0');expect(fields.phCurrent).toBe('0');expect(fields.poolLoad).toBe('HISTORIC');});
 it('uses parent volume only where the profile has none',()=>{expect(R.form(pool,{...profile,volumeM3:null}).volumeM3).toBe('80');expect(R.form(pool,null).shape).toBe('CIRCULAR');expect(R.patch(pool,null,R.form(pool,null)).profile.volumeM3).toBe(80);});
 it('refuses omitted, extra, nonfinite and nondecimal fields',()=>{for(const field of [{...review.fields,volumeM3:'0x10'},{...review.fields,volumeM3:'1e309'},{...review.fields,volumeM3:' '},{...review.fields,privateData:'extra'},{...review.fields,notes:undefined}])expect(R.fields(field)).toBe(false);expect(R.fields({...review.fields,volumeM3:'1.34e1'})).toBe(true);});
 it('refuses divergent pool, profile and field projections',()=>{for(const value of [{...review,fields:{...review.fields,volumeM3:'80'}},{...review,pool:{...pool,clientId:10}},{...review,profile:{...profile,poolId:8}}])expect(R.state(value)).toBe(false);});
 it('does not accept malformed confirmations or throw for a missing profile',()=>{const command={requestId:'93b55fb9-8b9e-4d16-9c48-3e06a2e05c3a',expectedVersion:review.version,fields:review.fields},record={poolId:7,command,review,payloadHash:'a'.repeat(64)},receipt={owner:'ADMIN:1',scope:R.scope,resourceId:7,requestId:command.requestId,payloadHash:record.payloadHash,confirmedAt:'2026-09-25T00:00:00Z'},result={ok:true,applied:false,context:R.intent(command),code:'CALCULATOR_STALE',message:'Changed',receipt};expect(R.confirmation(result,record,'ADMIN:1')).toBe(true);expect(R.confirmation(result,record,'ADMIN:2')).toBe(false);expect(R.confirmation({...result,applied:true,state:{...review,profile:null,fields:R.form(pool,null)}},record,'ADMIN:1')).toBe(false);expect(R.confirmation(result,{},'ADMIN:1')).toBe(false);});
});
