import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),writes=require('../src/services/fieldWriteRequestService'),resources=require('../frontend/cw-reminder-resource-rules'),rules=require('../frontend/cw-reminder-material-rules');
const clone=v=>JSON.parse(JSON.stringify(v)),hash=writes.hash,sha='a'.repeat(64),owner='ADMIN:1',declarationId='d145d52b-922a-40eb-936f-9b8bc0a0ee11',consumptionId='d145d52b-922a-40eb-936f-9b8bc0a0ee12';
function receipt(scope,body,event){const {requestId,...payload}=body;return {ok:true,applied:true,envelope:body,event,eventHash:hash(event),receipt:{...writes.context({id:1,role:'ADMIN'},scope,1,requestId,payload),confirmedAt:event.createdAt}};}
function fixture(){
  const source={id:1,title:'Serviço',description:null,category:'POOL_SERVICE_REMINDER',status:'DONE',completedAt:'2008-07-11T12:00:00.000Z',clientId:2,poolId:4,technicianId:null},target={type:'MAINTENANCE_REMINDER',id:1,clientId:2,poolId:4,status:'CONFIRMED',startAt:null,endAt:source.completedAt,executionBasis:'CONFIRMED_MAINTENANCE_EXECUTION_AND_DECISION',decisionId:5,decisionFingerprint:sha,executionFingerprint:sha,originVisitType:null,originVisitId:null},origin={reminderId:1,clientId:2,poolId:4,technicianId:3};
  const proposed={technicianId:3,materials:{mode:'DECLARED',items:[{productName:'CLORO',unit:'KG',quantity:'1'}]},workTime:null},d={schema:1,basis:resources.basis,reminderId:1,action:'DECLARE',recordId:null,recordHash:null,origin,contextHash:sha,source,sourceHash:hash(source),target,targetHash:hash(target),proposed,durationSeconds:null},dp={available:true,...d,hash:hash(d)},db={requestId:declarationId,action:'DECLARE',recordId:null,data:proposed,previewHash:dp.hash,reason:'Materiais conferidos',confirmed:true},de={schema:1,basis:resources.basis,id:declarationId,owner,reminderId:1,recordId:9,reason:db.reason,createdAt:'2008-07-12T00:00:00.000Z',preview:dp},declaration=receipt(resources.scope,db,de);
  const selection={action:'CONSUME',recordId:null,declarationId:9,items:[{itemIndex:1,balanceId:10}]},balance={id:10,scope:'CENTRAL',vehicleId:null,productId:null,productName:'CLORO',category:null,unit:'KG',quantity:'3'},p={schema:1,basis:rules.basis,reminderId:1,selection,origin,previousHash:null,contextHash:sha,declaration,original:null,items:[{itemIndex:1,balance,quantity:'1',afterQuantity:'2',reservedQuantity:'0',reservationHash:sha}],affectedCosts:null},preview={available:true,...p,hash:hash(p)},body={requestId:consumptionId,...selection,previewHash:preview.hash,reason:'Consumo e origem conferidos',confirmed:true};
  const event={schema:1,basis:rules.basis,id:consumptionId,owner,reminderId:1,reason:body.reason,createdAt:'2008-07-13T00:00:00.000Z',preview,movements:[{id:17,movementType:'CONSUMPTION',scopeFrom:'CENTRAL',scopeTo:'REMINDER',vehicleId:null,productId:null,productName:'CLORO',category:null,unit:'KG',quantity:'1',purchaseId:null,transportGuideId:null,workGuideId:null,extraVisitId:null,visitId:null,clientId:2,poolId:4,technicianId:3,documentPath:null,notes:'Consumo próprio · Lembrete #1 · '+consumptionId,createdBy:owner,createdAt:'2008-07-13T00:00:00.000Z'}]},consumption=receipt(rules.scope,body,event);
  const value={version:8,kind:'MATERIAL',service:target,item:{id:11,purchaseId:12,productId:null,productName:'CLORO',unit:'KG',quantity:3,unitCost:1/3,totalCost:1,lot:null,purchase:{status:'OPEN',invoiceDate:'2008-07-01',totalAmount:1}},movements:clone(event.movements),materialBasis:rules.basis,consumption};
  return {preview,body,consumption,value,target};
}
const calculation=(before='0',cents=0,amount=33)=>({quantity:'1',quantityUnit:'KG',amountCents:amount,method:'CONFIRMED_PURCHASE_LINE',rounding:before==='2'?'FINAL_POOL_REMAINDER':'NEAREST_CENT',poolQuantityBefore:before,poolAmountBeforeCents:cents,measuredQuantityBefore:'0',baseQuantity:'3',baseAmountCents:100});
describe('independent reminder material proof',()=>{
  it('uses the same declaration and stock receipt checks in Node and the browser',async()=>{const c=vm.createContext({});for(const name of ['cw-maintenance-material-rules','cw-equipment-material-review-rules','cw-reminder-resource-rules','cw-reminder-material-rules'])vm.runInContext(fs.readFileSync(new URL('../frontend/'+name+'.js',import.meta.url),'utf8'),c);const f=fixture();await expect(rules.response(f.consumption,f.body,owner,1,hash)).resolves.toBe(f.consumption);expect(clone(await c.CWReminderMaterialRules.source(f.value,f.target,hash))).toEqual(await rules.source(f.value,f.target,hash));});
  it('rejects wrong products, units, balances and stock effects even with a new outer hash',async()=>{for(const change of [p=>p.items[0].quantity='0.5',p=>p.items[0].afterQuantity='3',p=>p.items[0].balance.quantity='0',p=>p.items[0].balance.productName='OUTRO',p=>p.items[0].balance.unit='L',p=>p.items[0].balance.id=11,p=>p.items[0].balance.scope='REPAIR',p=>p.items[0].balance.vehicleId=2,p=>p.items[0].reservedQuantity='3',p=>p.selection.declarationId=10,p=>p.origin.clientId=3]){const f=fixture();change(f.preview);f.preview.hash=hash(rules.facts(f.preview));await expect(rules.preview(f.preview,hash)).rejects.toThrow();}});
  it('rejects changed movement ownership, quantity, date and other service parents',async()=>{for(const change of [m=>m.quantity='0.5',m=>m.visitId=1,m=>m.extraVisitId=1,m=>m.scopeTo='REPAIR',m=>m.clientId=3,m=>m.technicianId=4,m=>m.createdBy='ADMIN:2',m=>m.createdAt='2008-07-11T00:00:00.000Z',m=>m.notes='Reassigned']){const f=fixture();change(f.consumption.event.movements[0]);f.consumption.eventHash=hash(f.consumption.event);await expect(rules.response(f.consumption,f.body,owner,1,hash)).rejects.toThrow();}});
  it('binds the valued movements to the original receipt and typed historical service',async()=>{for(const change of [v=>v.version=2,v=>v.service.type='REPAIR',v=>v.service.clientId=5,v=>v.movements[0].id=18,v=>v.movements[0].quantity='2',v=>v.item.productName='OUTRO',v=>v.item.unit='L',v=>v.consumption.event.reason='Other proof']){const f=fixture();change(f.value);await expect(rules.source(f.value,f.target,hash)).rejects.toThrow();}});
  it('conserves shared purchase quantities and final cents',()=>{const f=fixture();for(const c of [calculation(),calculation('1',33),calculation('2',66,34)])expect(rules.calculation(c,f.value)).toBe(c);for(const change of [c=>c.amountCents=34,c=>c.baseQuantity='4',c=>c.baseAmountCents=101,c=>c.poolQuantityBefore='3',c=>c.poolAmountBeforeCents=100,c=>c.measuredQuantityBefore='1',c=>c.quantity='1.1',c=>c.quantityUnit='L',c=>c.rounding='FINAL_POOL_REMAINDER']){const c=calculation();change(c);expect(()=>rules.calculation(c,f.value)).toThrow();}expect(()=>rules.calculation(calculation('2',66,33),f.value)).toThrow();});
  it('requires explicit origin selection and bounded distinct balance identities',()=>{for(const body of [{action:'CONSUME',recordId:null,declarationId:9,items:[]},{action:'CONSUME',recordId:null,declarationId:9,items:[{itemIndex:1,balanceId:2147483648}]},{action:'CONSUME',recordId:null,declarationId:9,items:[{itemIndex:1,balanceId:10},{itemIndex:2,balanceId:10}]},{action:'REVERSE',recordId:consumptionId,declarationId:9,items:null}])expect(()=>rules.input(body)).toThrow();});
  it('checks the original proof before a reversal and refuses nested reversals',async()=>{const f=fixture(),p={...f.preview,selection:{action:'REVERSE',recordId:consumptionId,declarationId:null,items:null},declaration:null,original:f.consumption,items:[{itemIndex:1,balance:{...f.preview.items[0].balance,quantity:'2'},quantity:'1',afterQuantity:'3'}],affectedCosts:[{allocationId:4,expenseId:8,amountCents:33,allocationHash:sha}]};p.hash=hash(rules.facts(p));await expect(rules.preview(p,hash)).resolves.toBe(p);p.items[0].afterQuantity='4';p.hash=hash(rules.facts(p));await expect(rules.preview(p,hash)).rejects.toThrow();p.original.event.preview.selection.action='REVERSE';p.hash=hash(rules.facts(p));await expect(rules.preview(p,hash)).rejects.toThrow();});
});
