import {describe,it,expect} from 'vitest';
const R=require('../frontend/cw-technician-guide-read-rules'),P=require('../frontend/cw-field-guide-projection'),a={owner:'TECH:7',technicianId:7},at='2026-09-26T07:00:00.000Z',vehicle={id:2,plate:'AA',active:true,deletedAt:null},base={ok:true,scope:{version:1,owner:a.owner,technicianId:7,vehicleId:2}},item={id:4,workGuideId:3,name:' Exact ',type:null,unit:null,quantity:0,initialQty:0,usedQty:-0.000001},work={id:3,vehicleId:2,technicianId:7,status:'OPEN',createdAt:at,startKm:0,endKm:null,notes:null,vehicle,technician:{id:7,name:'Tech'},guideId:null,guide:null,items:[item]},stock={...base,workGuide:work,stock:[item],itemCount:1,movements:[],movementsIncluded:false,transportGuideDocument:null,missingTransportGuide:true},query={vehicleId:2,workGuideId:3,movementType:null,maxId:null,offset:0},move=P.movement({id:10,vehicleId:2,technicianId:null,workGuideId:3,itemName:' Salt ',quantity:-0.000001,unit:null,movementType:'LOAD',createdAt:at,notes:' Exact note '}),packet={...base,total:1,limit:25,offset:0,hasMore:false,maxId:10,filters:{workGuideId:3,transportGuideId:null,movementType:null},movements:[move]};
describe('technician guide confirmed reads',()=>{
 it('preserves exact materials, signed values, missing units and zero readings',()=>{expect(R.stock(stock,a,2)).toBe(true);expect(stock.stock[0].unit).toBeNull();expect(stock.workGuide.startKm).toBe(0);expect(R.movements(packet,a,query)).toBe(true);});
 it('requires complete stock and explicit omission of embedded movements',()=>{for(const p of [{itemCount:2},{stock:[]},{movementsIncluded:true},{movements:undefined},{workGuide:undefined}])expect(R.stock({...stock,...p},a,2)).toBe(false);});
 it('rejects private nested fields in confirmed stock and vehicles',()=>{expect(R.stock({...stock,workGuide:{...work,technician:{id:7,name:'Tech',email:'private'}}},a,2)).toBe(false);const v={...vehicle,assignedTechnicians:[{id:7,name:'Tech',vehicleId:2}]};expect(R.vehicles({...base,vehicles:[v]},a)).toBe(true);expect(R.vehicles({...base,vehicles:[{...v,cost:3}]},a)).toBe(false);});
 it('rejects wrong technician, vehicle and scope even with success',()=>{for(const p of [{technicianId:8},{vehicleId:5},{status:'CLOSED'},{notes:undefined}])expect(R.stock({...stock,workGuide:{...work,...p}},a,2)).toBe(false);expect(R.stock({...stock,scope:{...base.scope,owner:'TECH:8'}},a,2)).toBe(false);});
 it('distinguishes an unassigned vehicle and no open work from partial data',()=>{expect(R.vehicles({...base,scope:{...base.scope,vehicleId:null},vehicles:[]},a)).toBe(true);expect(R.vehicles({...base,vehicles:[]},a)).toBe(false);expect(R.stock({...stock,workGuide:null,stock:[],itemCount:0,missingTransportGuide:false},a,2)).toBe(true);});
 it('accepts only protected pointers for the exact linked guide',()=>{expect(R.document({guideId:5,url:'/api/transport-guide-documents/current/5'},5,2)).toBe(true);for(const url of ['/api/transport-guide-documents/current/6','/uploads/a.pdf','https://example.test/a.pdf'])expect(R.document({guideId:5,url},5,2)).toBe(false);});
 it('rejects partial, duplicate and reordered movement pages',()=>{for(const patch of [{total:2},{hasMore:true},{limit:200},{offset:25},{movements:[]},{movements:[move,move],total:2}])expect(R.movements({...packet,...patch},a,query)).toBe(false);expect(R.movements({...packet,total:2,maxId:11,movements:[move,{...move,id:11}]},a,query)).toBe(false);});
 it('binds movement filters and insertion window',()=>{expect(R.movements(packet,a,{...query,maxId:10})).toBe(true);expect(R.movements(packet,a,{...query,maxId:11})).toBe(false);expect(R.movements(packet,a,{...query,movementType:'LOAD'})).toBe(false);expect(R.movements({...packet,filters:{...packet.filters,movementType:'LOAD'}},a,{...query,movementType:'LOAD'})).toBe(true);});
 it('rejects private metadata and foreign ownership in movements',()=>{for(const patch of [{technicianId:8},{workGuideId:8},{quantity:NaN},{cost:3},{guideMeta:{...move.guideMeta,email:'private'}},{readings:{ph:0,cost:3}}])expect(R.movements({...packet,movements:[{...move,...patch}]},a,query)).toBe(false);});
 it('rejects invalid page positions and nonliteral filter encodings',()=>{for(const patch of [{offset:-25},{offset:1},{maxId:-1},{movementType:''},{movementType:'LOAD\n'},{vehicleId:'2'}])expect(R.query({...query,...patch})).toBe(false);});
 it('confirms the final empty page and zero insertion boundary',()=>{expect(R.movements({...packet,total:0,maxId:0,movements:[]},a,query)).toBe(true);expect(R.movements({...packet,total:25,offset:25,movements:[]},a,{...query,offset:25})).toBe(true);});
});
