import {describe,it,expect} from 'vitest';
const R=require('../frontend/cw-vehicle-maintenance-rules'),D=require('../frontend/cw-onboarding-rules'),at='2026-09-25T20:00:01.123Z',owner='ADMIN:1',requestId='53b16078-d5c2-46a9-8f1b-453c0579dbae';
const c={record:{id:4,vehicleId:2,type:'GENERAL',title:'Original',status:'PENDING',dueDate:'2027-10-25T01:30:09.456Z',completedAt:null,km:null,cost:null,notes:'Original note',createdAt:at,updatedAt:at},vehicle:{id:2,plate:'AA',currentKm:100,active:true,deletedAt:null,updatedAt:at},expense:null,sourceHash:'a'.repeat(64)},p={operation:'EDIT',maintenanceId:4,vehicleId:2,reason:'Reviewed correction',changes:{notes:'Changed'}};
const linked={...c,expense:{id:7,version:1,cancelledAt:null,sourceHash:c.sourceHash,updatedAt:at}};
describe('reviewed vehicle maintenance',()=>{
 it('preserves omitted precise dates, cost, distance and completion',()=>{expect(R.plan(c,p).after).toEqual({...R.metadata(c.record),notes:'Changed'});expect(R.plan(c,p).vehicleKmUnchanged).toBe(true);});
 it('creates only pending records with all choices explicit',()=>{const create={...p,operation:'CREATE',maintenanceId:null,changes:{type:'GENERAL',title:'New',dueDate:null,km:null,cost:'0',notes:null}};expect(R.plan({...c,record:null,sourceHash:null},create).after).toEqual({...create.changes,cost:0,status:'PENDING',completedAt:null});expect(R.input({...create,changes:{title:'New'}})).toBeNull();});
 it('distinguishes missing, zero and empty text',()=>{for(const[k,value]of[['km','0'],['cost','0'],['notes','']])expect(R.plan(c,{...p,changes:{[k]:value}}).after[k]).toBe(k==='notes'?'':0);expect(R.plan(c,{...p,changes:{notes:null}}).after.notes).toBeNull();});
 it.each(['1e3','-1','01','NaN','1.001','21474836.48'])('rejects invalid cost %s',cost=>expect(R.input({...p,changes:{cost}})).toBeNull());
 it('requires bounded precision without coercions or unknown fields',()=>{for(const changes of [{km:'1.0001'},{cost:0},{title:null},{type:'CUSTOM'},{vehicleId:9},{completedAt:at},{status:'DONE'}])expect(R.input({...p,changes})).toBeNull();expect(R.input({...p,changes:{cost:'12.50',km:'100.125'}}).changes).toEqual({km:'100.125',cost:'12.5'});expect(R.input({...p,actor:owner})).toBeNull();});
 it('requires actual pending completion and protects previous completion date',()=>{const complete={...p,operation:'COMPLETE',changes:{}};expect(R.plan(c,complete).after.completedAt).toBe('ON_CONFIRMATION');for(const record of [{...c.record,status:'DONE',completedAt:at},{...c.record,status:'PENDING',completedAt:at},{...c.record,status:'UNKNOWN'}])expect(R.plan({...c,record},complete)).toBeNull();expect(R.input({...complete,changes:{title:'Override'}})).toBeNull();const done={...c,record:{...c.record,status:'DONE',completedAt:at}};expect(R.plan(done,p).after.completedAt).toBe(at);});
 it('refuses no-op edits and vehicle substitution, supports historical missing vehicles',()=>{expect(R.plan(c,{...p,changes:{notes:c.record.notes}})).toBeNull();expect(R.plan(c,{...p,vehicleId:9})).toBeNull();expect(R.plan({...c,vehicle:null},p)).not.toBeNull();});
 it('marks source-sensitive changes for expense review while conserving notes-only edits',()=>{expect(R.plan(linked,p).expenseReviewAfter).toBe(false);for(const changes of [{title:'Changed'},{cost:'1'},{dueDate:null}])expect(R.plan(linked,{...p,changes}).expenseReviewAfter).toBe(true);expect(R.plan(linked,{...p,changes:{km:'150'}}).expenseReviewAfter).toBe(false);expect(R.plan(linked,{...p,changes:{dueDate:'2027-10-25T09:30:00.000Z'}}).expenseReviewAfter).toBe(false);expect(R.plan({...linked,sourceHash:'b'.repeat(64)},p).expenseReviewBefore).toBe(true);expect(R.plan(linked,{...p,operation:'COMPLETE',changes:{}}).expenseReviewAfter).toBe(true);});
 it('resolves Lisbon gap/fold explicitly and preserves dates when not replaced',()=>{expect(D.resolve('2027-03-28T01:30','')).toBeNull();expect(D.resolve('2027-10-31T01:30','')).toBeNull();expect(D.resolve('2027-10-31T01:30','second')).toBe('2027-10-31T01:30:00.000Z');expect(R.plan(c,p).after.dueDate).toBe(c.record.dueDate);});
 it('checks complete lists, exact review and cross-owner replies',()=>{const r={ok:true,version:1,owner,asOf:at,requestId,expiresAt:'2026-09-25T20:05:00.000Z',reviewToken:'x'.repeat(100),proposal:p,choice:c,plan:R.plan(c,p)};expect(R.reviewPacket(r,owner,p)).toBe(true);expect(R.reviewPacket({...r,plan:{...r.plan,expenseId:7}},owner,p)).toBe(false);expect(R.listPacket({...r,kind:'records',page:1,size:25,total:1,rows:[c]},owner,1,'records')).toBe(true);expect(R.listPacket({...r,kind:'records',page:1,size:25,total:2,rows:[c]},owner,1,'records')).toBe(false);expect(R.reviewPacket(r,'ADMIN:2',p)).toBe(false);});
 it('verifies recovered JSONB receipt and exact retained dates',()=>{const plan=R.plan(c,p),r={operation:p.operation,maintenanceId:4,vehicleId:2,record:{...c.record,...plan.after},proposal:p,before:c,plan,appliedAt:at,auditId:9,receipt:{owner,requestId,scope:'VEHICLE_MAINTENANCE_REVIEW',resourceId:4,confirmedAt:at}},packet={ok:true,version:1,owner,asOf:at,requestId,status:'CONFIRMED',result:r},pending={...p,requestId};expect(R.resultPacket(packet,owner,pending)).toBe(true);for(const patch of [{cost:0},{dueDate:null},{completedAt:at},{vehicleId:9}])expect(R.resultPacket({...packet,result:{...r,record:{...r.record,...patch}}},owner,pending)).toBe(false);const reverse=v=>Array.isArray(v)?v.map(reverse):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().reverse().map(k=>[k,reverse(v[k])])):v;expect(R.resultPacket(reverse(packet),owner,pending)).toBe(true);});
 it('accepts field projections without costs and refuses field cost changes',()=>{const{cost,...record}=c.record,field={...c,record,financialAccess:false,expense:null};expect(R.choice(field)).toBe(true);expect(R.plan(field,p).after).not.toHaveProperty('cost');expect(R.plan(field,{...p,changes:{cost:'0'}})).toBeNull();expect(R.choice({...field,record:c.record})).toBe(false);expect(R.choice({...field,expense:linked.expense})).toBe(false);});
 it('stores only an owner-scoped operation reference',()=>{const v={version:1,owner,operation:'EDIT',maintenanceId:4,vehicleId:2,requestId};expect(R.pending(JSON.stringify(v),owner)).toEqual(v);expect(R.pending(JSON.stringify({...v,cost:20}),owner)).toBe(false);expect(R.pending(JSON.stringify(v),'ADMIN:2')).toBe(false);});
});
