import {describe,it,expect} from 'vitest';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),rules=require('../frontend/cw-visit-report-origin-rules'),{hash}=require('../src/services/fieldWriteRequestService'),{technicalSource}=require('../src/services/visitReportOriginService');
const details={poolName:'Instalação original',zone:'Zona antiga',address:'Morada antiga',evidence:'Ordem de serviço original conferida no arquivo.'};
function fixture(type='REGULAR'){
 const source={visitType:type,visitId:7,clientId:3,poolId:4,technicianId:5,status:'DONE',startAt:'2020-01-01T10:00:00.000Z',endAt:'2020-01-01T11:00:00.000Z',content:{notes:'Registo original'}};
 const p={available:true,schema:1,basis:rules.basis,source,sourceHash:hash(source),client:{id:3,name:'Cliente original'},currentPool:{id:4,clientId:8,name:'Instalação atual',clientName:'Novo cliente'},selection:{action:'REPLACE',details:{...details}},previous:{hash:null,action:'ORIGINAL',details:null}};
 return seal(p);
}
function seal(p){p.sourceHash=hash(p.source);p.contextHash=hash(rules.contextFacts(p));p.hash=hash(rules.facts(p));return p;}
function receipt(p){const body={requestId:randomUUID(),...p.selection,previewHash:p.hash,reason:'Arquivo original consultado',confirmed:true},{requestId,...payload}=body,event={schema:1,id:requestId,owner:'ADMIN:1',visitType:p.source.visitType,visitId:7,reason:body.reason,createdAt:'2026-01-01T10:00:00.000Z',preview:p};return {body,result:{ok:true,applied:true,envelope:body,event,eventHash:hash(event),receipt:{owner:'ADMIN:1',requestId,scope:rules.scope(p.source.visitType),resourceId:7,payloadHash:hash({v:1,scope:rules.scope(p.source.visitType),resourceId:7,payload}),confirmedAt:event.createdAt}}};}
describe('historical visit report origin proofs',()=>{
 it('keeps the recorded client even when the pool has a new owner',async()=>{const p=fixture();expect(await rules.preview(p,hash)).toEqual(p);p.client.id=8;seal(p);await expect(rules.preview(p,hash)).rejects.toThrow();});
 it('requires an original client, closed status and a positive canonical visit interval',async()=>{for(const patch of [{clientId:null},{status:'PLANNED'},{endAt:'2020-01-01T10:00:00.000Z'},{startAt:'2020-01-01T10:00:00Z'},{visitId:'7'}]){const p=fixture();Object.assign(p.source,patch);seal(p);await expect(rules.preview(p,hash)).rejects.toThrow();}});
 it('rejects missing evidence, extra owner selection, controls and silent trimming',()=>{for(const value of [{...details,evidence:'curto'},{...details,clientId:8},{...details,poolName:' antiga '},{...details,address:'x\u0000y'}])expect(()=>rules.details(value)).toThrow();expect(rules.details({...details,address:'Linha 1\nLinha 2'}).address).toContain('\n');});
 it('binds both typed visit identity and the exact confirmed historical data',async()=>{const {body,result}=receipt(fixture());await rules.response(result,body,'ADMIN:1','REGULAR',7,hash);await expect(rules.response(result,body,'ADMIN:1','EXTRA',7,hash)).rejects.toThrow();await expect(rules.response(result,body,'ADMIN:2','REGULAR',7,hash)).rejects.toThrow();await expect(rules.response(result,{...body,details:{...details,poolName:'Outra instalação'}},'ADMIN:1','REGULAR',7,hash)).rejects.toThrow();});
 it('rejects rehashed previews with the wrong source context and future confirmations',async()=>{let p=fixture();p.contextHash='a'.repeat(64);p.hash=hash(rules.facts(p));await expect(rules.preview(p,hash)).rejects.toThrow();p=fixture();p.source.endAt='2030-01-01T11:00:00.000Z';seal(p);const {body,result}=receipt(p);await expect(rules.response(result,body,'ADMIN:1','REGULAR',7,hash)).rejects.toThrow();});
 it('requires an active previous review for withdrawal and preserves its exact hash',async()=>{const p=fixture();p.selection={action:'WITHDRAW',details:null};seal(p);await expect(rules.preview(p,hash)).rejects.toThrow();p.previous={hash:'b'.repeat(64),action:'REPLACE',details};p.source.status='PLANNED';seal(p);await rules.preview(p,hash);p.previous.details=null;seal(p);await expect(rules.preview(p,hash)).rejects.toThrow();});
 it('binds refusal receipts to the command and excludes unconfirmed events',async()=>{const {body,result}=receipt(fixture('EXTRA'));Object.assign(result,{applied:false,code:'PREVIEW_CHANGED',message:'Consulte novamente.'});delete result.event;delete result.eventHash;await rules.response(result,body,'ADMIN:1','EXTRA',7,hash);result.event={};await expect(rules.response(result,body,'ADMIN:1','EXTRA',7,hash)).rejects.toThrow();});
 it('keeps technical fingerprints independent of billing while binding photos beyond display limits',()=>{for(const type of rules.types){const visit={id:7,clientId:3,poolId:4,technicianId:5,status:'DONE',startAt:new Date('2020-01-01T10:00:00Z'),endAt:new Date('2020-01-01T11:00:00Z'),photos:Array.from({length:25},(_,i)=>({id:i+1,type:'GENERAL',url:'original-'+i})),chemicals:[{id:1,name:'Produto',quantity:1,unit:'kg'}],technician:{name:'Técnico'}};const original=hash(technicalSource(type,visit));Object.assign(visit,{billed:true,revenue:123,price:456,updatedAt:new Date()});expect(hash(technicalSource(type,visit))).toBe(original);visit.photos[24].url='alterada';expect(hash(technicalSource(type,visit))).not.toBe(original);}});
});
