import {describe,it,expect} from 'vitest';
const R=require('../frontend/cw-work-guide-close-rules'),at='2026-09-25T20:00:01.123Z',owner='ADMIN:1',requestId='53b16078-d5c2-46a9-8f1b-453c0579dbae';
const c={work:{id:4,vehicleId:2,technicianId:7,guideId:3,status:'OPEN',closedAt:null,startKm:90,endKm:null,notes:'Original',updatedAt:at},vehicle:{id:2,plate:'AA',currentKm:100,active:true,deletedAt:null},technician:{id:7,name:'Tech'},transport:{id:3},items:[{id:20,workGuideId:4,name:'Salt',type:null,unit:'KG',initialQty:3,quantity:2,usedQty:1,updatedAt:at}]};
const p={workGuideId:4,reason:'Reviewed closure',endKmMode:'KEEP',endKm:null,updateVehicle:false},set=(value,updateVehicle=false)=>({...p,endKmMode:'SET',endKm:value,updateVehicle});
describe('reviewed work closure',()=>{
 it('preserves missing reading and distinguishes explicit zero',()=>{expect(R.plan(c,p).endKm).toBeNull();expect(R.plan({...c,work:{...c.work,startKm:null}},set('0')).endKm).toBe(0);expect(R.plan({...c,work:{...c.work,endKm:95}},p).endKm).toBe(95);});
 it('normalizes decimal text and retains reason separately',()=>{expect(R.input(set('120.250')).endKm).toBe('120.25');expect(R.plan(c,set('120.250')).vehicleKmAfter).toBe(100);expect(R.plan(c,set('120.250',true)).vehicleKmAfter).toBe(120.25);expect(c.work.notes).toBe('Original');});
 it('requires explicit monotonic vehicle change and coherent starting km',()=>{expect(R.plan(c,set('95'))).not.toBeNull();expect(R.plan(c,set('95',true))).toBeNull();expect(R.plan(c,set('89'))).toBeNull();expect(R.input({...p,updateVehicle:true})).toBeNull();});
 it.each(['','-1','01','1e3','Infinity','1.0001','1,5','1000000000'])('rejects ambiguous reading %s',endKm=>expect(R.input(set(endKm))).toBeNull());
 it('rejects coercions, clearing, unknown fields, missing reason and bad identifiers',()=>{for(const patch of [{endKm:0,endKmMode:'SET'},{endKmMode:'CLEAR'},{updateVehicle:'false'},{workGuideId:'4'},{actor:owner},{reason:'  '},{reason:'a\u0000b'}])expect(R.input({...p,...patch})).toBeNull();});
 it('refuses closed/inconsistent work and invalid stock; allows empty and orphan work',()=>{for(const patch of [{status:'CLOSED',closedAt:at},{closedAt:at}])expect(R.plan({...c,work:{...c.work,...patch}},p)).toBeNull();expect(R.plan({...c,items:[{...c.items[0],quantity:-1}]},p)).toBeNull();expect(R.plan({...c,items:[]},p)).not.toBeNull();expect(R.plan({...c,work:{...c.work,vehicleId:null},vehicle:null},p)).not.toBeNull();});
 it('prevents vehicle updates for archived or missing vehicles',()=>{for(const vehicle of [{...c.vehicle,active:false},{...c.vehicle,deletedAt:at}]){expect(R.plan({...c,vehicle},set('120',true))).toBeNull();expect(R.plan({...c,vehicle},p)).not.toBeNull();}});
 it('recomputes complete signed review and refuses partial or crossed lists',()=>{const r={ok:true,version:1,owner,asOf:at,requestId,expiresAt:'2026-09-25T20:05:00.000Z',reviewToken:'x'.repeat(100),proposal:p,choice:c,plan:R.plan(c,p)};expect(R.reviewPacket(r,owner,p)).toBe(true);expect(R.reviewPacket({...r,plan:{...r.plan,endKm:0}},owner,p)).toBe(false);expect(R.listPacket({...r,page:1,size:25,total:1,guides:[c]},owner,1)).toBe(true);expect(R.listPacket({...r,page:1,size:25,total:2,guides:[c]},owner,1)).toBe(false);expect(R.reviewPacket(r,'ADMIN:2',p)).toBe(false);});
 it('checks recovered receipt even after JSONB key reordering',()=>{const r={workGuideId:4,work:{...c.work,status:'CLOSED',closedAt:at},proposal:p,reason:p.reason,before:c,plan:R.plan(c,p),appliedAt:at,auditId:9,receipt:{owner,requestId,scope:'WORK_GUIDE_CLOSE',resourceId:4,confirmedAt:at}},packet={ok:true,version:1,owner,asOf:at,requestId,status:'CONFIRMED',result:r},pending={workGuideId:4,requestId};expect(R.resultPacket(packet,owner,pending)).toBe(true);const reorder=v=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,reorder(v[k])])):v;expect(R.resultPacket(reorder(packet),owner,pending)).toBe(true);for(const patch of [{endKm:0},{notes:'Overwritten'},{closedAt:null},{vehicleId:9}])expect(R.resultPacket({...packet,result:{...r,work:{...r.work,...patch}}},owner,pending)).toBe(false);});
 it('retains only the owner-scoped reference, never the reason or odometer',()=>{const value={version:1,owner,workGuideId:4,requestId};expect(R.pending(JSON.stringify(value),owner)).toEqual(value);expect(R.pending(JSON.stringify({...value,reason:p.reason}),owner)).toBe(false);expect(R.pending(JSON.stringify(value),'ADMIN:2')).toBe(false);});
});
