import {describe,it,expect} from 'vitest';
const R=require('../frontend/cw-work-guide-start-rules'),at='2026-09-26T05:00:00.000Z',owner='ADMIN:1',requestId='53b16078-d5c2-46a9-8f1b-453c0579dbae';
const vehicle={id:2,plate:'AA',active:true,deletedAt:null,currentKm:100,updatedAt:at},technician={id:7,name:'Tech',vehicleId:2,active:true,deletedAt:null,updatedAt:at},material={name:' Salt <img src=x> ',type:null,unit:' KG ',quantity:1.000001},c={vehicle,technician,source:'VEHICLE_PRESET',transport:null,items:[material]},p={vehicleId:2,technicianId:7,startKmMode:'NONE',startKm:null,notes:' Exact\nnotes ',reason:'Reviewed opening'},set=v=>({...p,startKmMode:'SET',startKm:v});
describe('reviewed work opening',()=>{
 it('keeps missing mileage distinct from explicit zero',()=>{expect(R.plan(c,p).startKm).toBeNull();expect(R.plan(c,p).vehicleKmAfter).toBe(100);expect(R.plan({...c,vehicle:{...vehicle,currentKm:null}},set('0')).startKm).toBe(0);});
 it('does not lower the vehicle reading',()=>{expect(R.plan(c,set('99.999'))).toBeNull();expect(R.plan(c,set('100')).vehicleKmAfter).toBe(100);expect(R.input(set('100.250')).startKm).toBe('100.25');});
 it.each(['','-1','01','1e3','Infinity','1.0001','1,5','1000000000'])('rejects ambiguous mileage %s',v=>expect(R.input(set(v))).toBeNull());
 it('requires typed exact fields and retains the original work notes',()=>{expect(R.input(p).notes).toBe(p.notes);for(const patch of [{vehicleId:'2'},{startKmMode:'SET',startKm:0},{startKmMode:'KEEP'},{startKm:'0'},{reason:''},{actor:owner},{technicianId:0}])expect(R.input({...p,...patch})).toBeNull();});
 it('distinguishes active AT, fallback, empty preset and empty source',()=>{const transport={id:9,vehicleId:2,status:'ACTIVE',codeAT:null,createdAt:at,updatedAt:at};expect(R.plan({...c,source:'TRANSPORT_GUIDE',transport},p)).toMatchObject({guideId:9,inheritedFromId:9,isDraft:false,missingTransportGuide:false});expect(R.plan({...c,source:'LAST_GUIDE',transport:{...transport,status:'CLOSED'}},p)).toMatchObject({guideId:null,inheritedFromId:9,isDraft:true});expect(R.plan({...c,items:[]},p).source).toBe('VEHICLE_PRESET');expect(R.plan({...c,source:'EMPTY',items:[]},p).itemCount).toBe(0);expect(R.plan({...c,source:'EMPTY'},p)).toBeNull();});
 it('preserves exact duplicate material names, types and units without coercion',()=>{expect(R.plan({...c,items:[material,material]},p).itemCount).toBe(2);for(const patch of [{quantity:'1'},{quantity:-1},{quantity:0.0000001},{quantity:1000001},{unit:null},{type:4}])expect(R.plan({...c,items:[{...material,...patch}]},p)).toBeNull();});
 it('bounds material volume and checks current assignment and active vehicle',()=>{expect(R.plan({...c,items:Array(101).fill(material)},p)).toBeNull();expect(R.plan({...c,technician:{...technician,vehicleId:3}},p)).toBeNull();expect(R.plan({...c,vehicle:{...vehicle,active:false}},p)).toBeNull();expect(R.plan({...c,technician:null},{...p,technicianId:null})).not.toBeNull();});
 it('verifies complete owner-scoped lists and recomputes review',()=>{const base={ok:true,version:1,owner,asOf:at},r={...base,requestId,reviewToken:'x'.repeat(100),expiresAt:'2026-09-26T05:05:00.000Z',choice:c,proposal:p,plan:R.plan(c,p)};expect(R.reviewPacket(r,owner,p)).toBe(true);expect(R.reviewPacket({...r,plan:{...r.plan,startKm:0}},owner,p)).toBe(false);const list={...base,page:1,size:25,total:1,rows:[{vehicle,technicians:[technician],openWorkCount:0,existingWorkId:null}]};expect(R.listPacket(list,owner,1)).toBe(true);expect(R.listPacket({...list,total:2},owner,1)).toBe(false);expect(R.listPacket(list,'TECH:7',1)).toBe(false);});
 it('verifies exact recovered work and material rows after JSONB reordering',()=>{const plan=R.plan(c,p),work={id:20,vehicleId:2,technicianId:7,guideId:null,inheritedFromId:null,status:'OPEN',isDraft:true,startKm:null,endKm:null,closedAt:null,notes:p.notes,createdAt:at,updatedAt:at,items:[{...material,id:30,workGuideId:20,usedQty:0,initialQty:material.quantity,updatedAt:at}]},result={vehicleId:2,work,vehicle,proposal:p,before:c,plan,lockId:40,notificationId:41,auditId:42,receipt:{owner,requestId,scope:'WORK_GUIDE_START',resourceId:2,confirmedAt:at}},packet={ok:true,version:1,owner,asOf:at,requestId,status:'CONFIRMED',result},pending={vehicleId:2,requestId};expect(R.resultPacket(packet,owner,pending)).toBe(true);const reorder=v=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,reorder(v[k])])):v;expect(R.resultPacket(reorder(packet),owner,pending)).toBe(true);for(const patch of [{notes:'Other'},{startKm:0},{technicianId:null},{items:[]},{status:'CLOSED'}])expect(R.resultPacket({...packet,result:{...result,work:{...work,...patch}}},owner,pending)).toBe(false);expect(R.resultPacket({...packet,result:{...result,notificationId:null}},owner,pending)).toBe(false);});
 it('persists only the owner and vehicle reference, not notes or readings',()=>{const pending={version:1,owner,vehicleId:2,requestId};expect(R.pending(JSON.stringify(pending),owner)).toEqual(pending);expect(R.pending(JSON.stringify({...pending,notes:p.notes}),owner)).toBe(false);expect(R.pending(JSON.stringify(pending),'TECH:7')).toBe(false);});
});
